# Generated by Django 6.0.3 on 2026-04-03 11:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('name', models.CharField(max_length=100)),
                ('provider_key', models.CharField(db_index=True, max_length=100)),
                ('category', models.CharField(choices=[('hrms', 'HRMS'), ('email', 'Email'), ('calendar', 'Calendar'), ('job_board', 'Job Board'), ('assessment', 'Assessment Tool'), ('background_verification', 'Background Verification'), ('payroll', 'Payroll'), ('offer', 'Offer Tool')], db_index=True, max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('error', 'Error'), ('pending', 'Pending')], db_index=True, default='inactive', max_length=20)),
                ('config_json', models.JSONField(blank=True, default=dict)),
                ('auth_data_json', models.JSONField(blank=True, default=dict)),
                ('is_connected', models.BooleanField(default=False)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'icc_integrations',
                'unique_together': {('tenant_id', 'provider_key')},
            },
        ),
    ]
