# Generated by Django 6.0.3 on 2026-03-26 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0003_placement_commission'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='commissionrecord',
            new_name='pipeline_co_company_5e3ff6_idx',
            old_name='cr_company_pstatus_idx',
        ),
        migrations.RenameIndex(
            model_name='commissionrecord',
            new_name='pipeline_co_requisi_0cccca_idx',
            old_name='cr_req_pstatus_idx',
        ),
        migrations.RenameIndex(
            model_name='placement',
            new_name='pipeline_pl_tenant__893e34_idx',
            old_name='pl_tenant_status_idx',
        ),
        migrations.RenameIndex(
            model_name='placement',
            new_name='pipeline_pl_requisi_e714a7_idx',
            old_name='pl_req_status_idx',
        ),
    ]
