# Generated by Django 6.0.3 on 2026-03-20 11:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationStageHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('application_id', models.UUIDField(db_index=True)),
                ('from_stage_id', models.UUIDField(blank=True, null=True)),
                ('to_stage_id', models.UUIDField(blank=True, null=True)),
                ('from_status', models.CharField(blank=True, max_length=50)),
                ('to_status', models.CharField(blank=True, max_length=50)),
                ('changed_by', models.UUIDField(blank=True, null=True)),
                ('changed_by_tenant_id', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pipeline_application_stage_history',
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('candidate_id', models.UUIDField(db_index=True)),
                ('job_id', models.UUIDField(db_index=True)),
                ('current_stage_id', models.UUIDField(blank=True, null=True)),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('screening', 'Screening'), ('shortlisted', 'Shortlisted'), ('interview', 'Interview'), ('assessment', 'Assessment'), ('offer', 'Offer'), ('joined', 'Joined'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('on_hold', 'On Hold')], default='applied', max_length=50)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('source_detail', models.TextField(blank=True)),
                ('submitted_by', models.UUIDField(blank=True, null=True)),
                ('submitted_by_tenant_id', models.UUIDField(blank=True, null=True)),
                ('agency_id', models.UUIDField(blank=True, null=True)),
                ('is_agency_submission', models.BooleanField(default=False)),
                ('match_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('rejection_category', models.CharField(blank=True, max_length=100)),
                ('withdrawn_reason', models.TextField(blank=True)),
                ('offer_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('offer_currency', models.CharField(default='INR', max_length=10)),
                ('offer_date', models.DateField(blank=True, null=True)),
                ('offer_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('joined_at', models.DateTimeField(blank=True, null=True)),
                ('application_form_data', models.JSONField(blank=True, default=dict)),
                ('product', models.CharField(choices=[('ats', 'ATS'), ('cafe', 'Cafe'), ('marketplace', 'Marketplace')], default='ats', max_length=20)),
            ],
            options={
                'db_table': 'pipeline_application',
                'ordering': ['-created_at'],
                'unique_together': {('tenant_id', 'candidate_id', 'job_id')},
            },
        ),
    ]
