# Generated by Django 6.0.3 on 2026-03-26 18:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacementGuarantee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('application_id', models.UUIDField(db_index=True)),
                ('candidate_id', models.UUIDField(db_index=True)),
                ('requisition_id', models.UUIDField(db_index=True)),
                ('agency_tenant_id', models.UUIDField(db_index=True)),
                ('company_tenant_id', models.UUIDField(db_index=True)),
                ('agency_relationship_id', models.UUIDField(db_index=True)),
                ('guarantee_start_date', models.DateField()),
                ('guarantee_end_date', models.DateField(db_index=True)),
                ('guarantee_resolution_type', models.CharField(default='replacement_only', max_length=40)),
                ('refund_mode', models.CharField(blank=True, max_length=40)),
                ('refund_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('replacement_attempt_limit', models.CharField(default='1', max_length=20)),
                ('current_attempt_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('breached', 'Breached'), ('replacement_requested', 'Replacement Requested'), ('refund_requested', 'Refund Requested'), ('resolved', 'Resolved'), ('expired', 'Expired'), ('waived', 'Waived')], db_index=True, default='active', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'pipeline_placement_guarantee',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company_tenant_id', 'status'], name='pipeline_pl_company_ca24d7_idx'), models.Index(fields=['requisition_id', 'status'], name='pipeline_pl_requisi_7c0dd9_idx')],
            },
        ),
    ]
