# Generated by Django 6.0.3 on 2026-03-25 12:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentTranslation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content_type', models.CharField(db_index=True, max_length=100)),
                ('object_id', models.UUIDField(db_index=True)),
                ('field_name', models.CharField(max_length=100)),
                ('original_language', models.CharField(max_length=10)),
                ('translated_language', models.CharField(db_index=True, max_length=10)),
                ('translated_content', models.TextField()),
                ('translation_source', models.CharField(choices=[('machine', 'Machine (auto)'), ('human', 'Human reviewed'), ('user', 'User provided')], default='machine', max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'translations_content',
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='trans_content_lookup')],
                'unique_together': {('content_type', 'object_id', 'field_name', 'translated_language')},
            },
        ),
        migrations.CreateModel(
            name='TranslationOverride',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(db_index=True, max_length=255)),
                ('language_code', models.CharField(db_index=True, max_length=10)),
                ('value', models.TextField()),
                ('module', models.CharField(blank=True, db_index=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'translations_override',
                'ordering': ['module', 'key', 'language_code'],
                'unique_together': {('key', 'language_code', 'tenant_id')},
            },
        ),
    ]
