# Generated by Django 6.0.3 on 2026-04-05 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automation_tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='workflowtaskdependency',
            name='unique_task_dependency',
        ),
        migrations.RenameIndex(
            model_name='workflowtaskdependency',
            new_name='automation__tenant__8256b0_idx',
            old_name='wf_task_dep_tenant_idx',
        ),
        migrations.RenameIndex(
            model_name='workflowtaskescalation',
            new_name='automation__tenant__1dd0f5_idx',
            old_name='wf_task_esc_tenant_at_idx',
        ),
        migrations.RenameIndex(
            model_name='workflowtaskexecution',
            new_name='automation__tenant__10ba44_idx',
            old_name='wf_task_exec_tenant_status_idx',
        ),
        migrations.RenameIndex(
            model_name='workflowtaskexecution',
            new_name='automation__tenant__7cd4f4_idx',
            old_name='wf_task_exec_assignee_idx',
        ),
        migrations.RenameIndex(
            model_name='workflowtaskexecution',
            new_name='automation__tenant__4d67ae_idx',
            old_name='wf_task_exec_pri_status_idx',
        ),
        migrations.RenameIndex(
            model_name='workflowtaskexecution',
            new_name='automation__tenant__48f637_idx',
            old_name='wf_task_exec_due_status_idx',
        ),
        migrations.RenameIndex(
            model_name='workflowtaskrule',
            new_name='automation__tenant__dd8e9d_idx',
            old_name='wf_task_rule_tenant_wf_idx',
        ),
        migrations.RenameIndex(
            model_name='workflowtaskrule',
            new_name='automation__tenant__7271fd_idx',
            old_name='wf_task_rule_active_idx',
        ),
        migrations.AlterUniqueTogether(
            name='workflowtaskdependency',
            unique_together={('task_execution', 'depends_on_task')},
        ),
    ]
