# Generated by Django 6.0.3 on 2026-04-04 13:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationPlaybook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('candidate', 'Candidate'), ('interview', 'Interview'), ('offer', 'Offer'), ('agency', 'Agency'), ('recruiter', 'Recruiter'), ('sla', 'SLA'), ('executive', 'Executive'), ('cross_module', 'Cross Module')], max_length=30)),
                ('module_scope', models.CharField(blank=True, max_length=100)),
                ('playbook_type', models.CharField(choices=[('system_default', 'System Default'), ('tenant_custom', 'Tenant Custom'), ('recommended', 'Recommended'), ('imported', 'Imported')], default='system_default', max_length=30)),
                ('version', models.CharField(default='1.0.0', max_length=20)),
                ('config_schema', models.JSONField(blank=True, default=dict)),
                ('playbook_payload', models.JSONField(blank=True, default=dict)),
                ('is_system_playbook', models.BooleanField(db_index=True, default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'Automation Playbook',
                'ordering': ['category', 'name'],
                'indexes': [models.Index(fields=['is_system_playbook', 'is_active'], name='automation__is_syst_d9c32f_idx')],
            },
        ),
        migrations.CreateModel(
            name='AutomationPlaybookInstall',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('install_status', models.CharField(choices=[('draft', 'Draft'), ('installing', 'Installing'), ('installed', 'Installed'), ('partial', 'Partial'), ('failed', 'Failed'), ('rolled_back', 'Rolled Back')], default='draft', max_length=20)),
                ('installed_by', models.UUIDField(blank=True, null=True)),
                ('installed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('config_snapshot', models.JSONField(blank=True, default=dict)),
                ('created_workflow_count', models.PositiveIntegerField(default=0)),
                ('created_rule_count', models.PositiveIntegerField(default=0)),
                ('failure_reason', models.TextField(blank=True)),
                ('created_entities_json', models.JSONField(blank=True, default=dict)),
                ('playbook', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='installs', to='automation_playbooks.automationplaybook')),
            ],
            options={
                'verbose_name': 'Automation Playbook Install',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AutomationPlaybookItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_type', models.CharField(choices=[('workflow', 'Workflow'), ('notification_rule', 'Notification Rule'), ('task_rule', 'Task Rule'), ('sla_policy', 'SLA Policy'), ('governance_rule', 'Governance Rule'), ('permission_policy', 'Permission Policy'), ('analytics_view', 'Analytics View')], max_length=30)),
                ('item_key', models.CharField(db_index=True, max_length=100)),
                ('item_name', models.CharField(max_length=255)),
                ('config_payload', models.JSONField(blank=True, default=dict)),
                ('execution_order', models.PositiveIntegerField(default=0)),
                ('is_required', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('playbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='automation_playbooks.automationplaybook')),
            ],
            options={
                'verbose_name': 'Automation Playbook Item',
                'ordering': ['playbook', 'execution_order'],
            },
        ),
        migrations.CreateModel(
            name='AutomationPlaybookRecommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('recommendation_reason', models.TextField()),
                ('confidence_score', models.FloatField(default=0.0)),
                ('source_type', models.CharField(choices=[('ai_insight', 'AI Insight'), ('admin_default', 'Admin Default'), ('usage_pattern', 'Usage Pattern'), ('module_gap', 'Module Gap'), ('sla_breach_pattern', 'SLA Breach Pattern')], max_length=30)),
                ('status', models.CharField(choices=[('new', 'New'), ('viewed', 'Viewed'), ('accepted', 'Accepted'), ('dismissed', 'Dismissed')], default='new', max_length=20)),
                ('playbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='automation_playbooks.automationplaybook')),
            ],
            options={
                'verbose_name': 'Automation Playbook Recommendation',
                'ordering': ['-confidence_score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AutomationPlaybookAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('snapshot_date', models.DateField(db_index=True)),
                ('install_count', models.PositiveIntegerField(default=0)),
                ('active_count', models.PositiveIntegerField(default=0)),
                ('workflow_count', models.PositiveIntegerField(default=0)),
                ('execution_count', models.PositiveIntegerField(default=0)),
                ('success_rate', models.FloatField(default=0.0)),
                ('failure_rate', models.FloatField(default=0.0)),
                ('impact_summary', models.JSONField(blank=True, default=dict)),
                ('playbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='automation_playbooks.automationplaybook')),
            ],
            options={
                'verbose_name': 'Automation Playbook Analytics',
                'ordering': ['-snapshot_date'],
                'unique_together': {('tenant_id', 'playbook', 'snapshot_date')},
            },
        ),
    ]
