# Generated by Django 6.0.3 on 2026-04-07 17:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EndToEndScenarioResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('scenario_key', models.CharField(db_index=True, max_length=128)),
                ('scenario_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('passed', 'Passed'), ('warning', 'Warning'), ('failed', 'Failed')], max_length=32)),
                ('failed_step', models.CharField(blank=True, max_length=255, null=True)),
                ('summary', models.TextField(blank=True)),
                ('execution_trace', models.JSONField(blank=True, default=list)),
                ('tested_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'qa_e2e_scenario_results',
                'ordering': ['-tested_at'],
            },
        ),
        migrations.CreateModel(
            name='ModuleCheckResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('module_key', models.CharField(db_index=True, max_length=128)),
                ('check_type', models.CharField(choices=[('functional', 'Functional'), ('integration', 'Integration'), ('workflow', 'Workflow'), ('end_to_end', 'End to End'), ('security', 'Security'), ('isolation', 'Isolation')], max_length=32)),
                ('check_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('passed', 'Passed'), ('warning', 'Warning'), ('failed', 'Failed'), ('skipped', 'Skipped')], max_length=32)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=32)),
                ('summary', models.TextField(blank=True)),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('remediation_hint', models.TextField(blank=True, null=True)),
                ('tested_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'qa_module_check_results',
                'ordering': ['-tested_at'],
            },
        ),
        migrations.CreateModel(
            name='ModuleReadinessResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('module_key', models.CharField(db_index=True, max_length=128)),
                ('functional_score', models.IntegerField(default=0)),
                ('integration_score', models.IntegerField(default=0)),
                ('workflow_score', models.IntegerField(default=0)),
                ('overall_score', models.IntegerField(default=0)),
                ('final_status', models.CharField(choices=[('not_started', 'Not Started'), ('in_development', 'In Development'), ('functional_ready', 'Functional Ready'), ('integration_ready', 'Integration Ready'), ('workflow_ready', 'Workflow Ready'), ('production_ready', 'Production Ready')], default='not_started', max_length=64)),
                ('blockers_count', models.IntegerField(default=0)),
                ('warnings_count', models.IntegerField(default=0)),
                ('tested_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'qa_module_readiness_results',
                'ordering': ['-tested_at'],
            },
        ),
        migrations.CreateModel(
            name='ReadinessBlocker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('blocker_key', models.CharField(db_index=True, max_length=128)),
                ('module_key', models.CharField(db_index=True, max_length=128)),
                ('blocker_type', models.CharField(choices=[('missing_api', 'Missing API'), ('broken_integration', 'Broken Integration'), ('missing_event', 'Missing Event'), ('missing_permission', 'Missing Permission'), ('missing_workflow_support', 'Missing Workflow Support'), ('missing_scheduler_logic', 'Missing Scheduler Logic'), ('missing_document_generation', 'Missing Document Generation'), ('missing_handoff', 'Missing Handoff'), ('tenant_isolation_issue', 'Tenant Isolation Issue'), ('audit_gap', 'Audit Gap')], max_length=64)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('recommended_fix', models.TextField(blank=True, null=True)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'qa_readiness_blockers',
                'ordering': ['-detected_at'],
            },
        ),
    ]
