from django.urls import path

from apps.orchestration_center.api import views


urlpatterns = [
    path('overview/', views.OverviewView.as_view(), name='intelligence-overview'),
    path('providers/', views.ProviderListView.as_view(), name='intelligence-provider-list'),
    path('providers/<uuid:pk>/', views.ProviderDetailView.as_view(), name='intelligence-provider-detail'),
    path('models/', views.ModelListView.as_view(), name='intelligence-model-list'),
    path('models/<uuid:pk>/', views.ModelDetailView.as_view(), name='intelligence-model-detail'),
    path('prompts/', views.PromptListCreateView.as_view(), name='intelligence-prompt-list-create'),
    path('prompts/<uuid:pk>/', views.PromptDetailView.as_view(), name='intelligence-prompt-detail'),
    path('prompts/<uuid:pk>/versions/', views.PromptVersionCreateView.as_view(), name='intelligence-prompt-version-create'),
    path('prompts/<uuid:pk>/approve/', views.PromptApproveView.as_view(), name='intelligence-prompt-approve'),
    path('prompts/<uuid:pk>/archive/', views.PromptArchiveView.as_view(), name='intelligence-prompt-archive'),
    path('prompts/<uuid:pk>/test/', views.PromptTestView.as_view(), name='intelligence-prompt-test'),
    path('automations/', views.AutomationListCreateView.as_view(), name='intelligence-automation-list-create'),
    path('automations/<uuid:pk>/', views.AutomationDetailView.as_view(), name='intelligence-automation-detail'),
    path('automations/<uuid:pk>/toggle/', views.AutomationToggleView.as_view(), name='intelligence-automation-toggle'),
    path('automations/<uuid:pk>/simulate/', views.AutomationSimulateView.as_view(), name='intelligence-automation-simulate'),
    path('automations/<uuid:pk>/runs/', views.AutomationRunsView.as_view(), name='intelligence-automation-runs'),
    path('executions/ai/', views.AIExecutionListView.as_view(), name='intelligence-ai-executions'),
    path('suggestions/', views.SuggestionListCreateView.as_view(), name='intelligence-suggestion-list-create'),
    path('suggestions/<uuid:pk>/', views.SuggestionDetailView.as_view(), name='intelligence-suggestion-detail'),
    path('suggestions/<uuid:pk>/review/', views.SuggestionReviewView.as_view(), name='intelligence-suggestion-review'),
    path('suggestions/<uuid:pk>/approve/', views.SuggestionApproveView.as_view(), name='intelligence-suggestion-approve'),
    path('suggestions/<uuid:pk>/convert/', views.SuggestionConvertView.as_view(), name='intelligence-suggestion-convert'),
    path('executions/automation/', views.AutomationExecutionListView.as_view(), name='intelligence-automation-executions'),
    path('executions/<uuid:execution_id>/', views.UnifiedExecutionDetailView.as_view(), name='intelligence-execution-detail'),
    path('executions/<uuid:execution_id>/retry/', views.ExecutionRetryView.as_view(), name='intelligence-execution-retry'),
    path('executions/<uuid:execution_id>/cancel/', views.ExecutionCancelView.as_view(), name='intelligence-execution-cancel'),
    path('executions/<uuid:execution_id>/approve/', views.ExecutionApproveView.as_view(), name='intelligence-execution-approve'),
    path('executions/<uuid:execution_id>/reject/', views.ExecutionRejectView.as_view(), name='intelligence-execution-reject'),
    path('failures/', views.FailureListView.as_view(), name='intelligence-failure-list'),
    path('failures/<uuid:pk>/retry/', views.FailureRetryView.as_view(), name='intelligence-failure-retry'),
    path('failures/<uuid:pk>/resolve/', views.FailureResolveView.as_view(), name='intelligence-failure-resolve'),
    path('dead-letter/', views.DeadLetterListView.as_view(), name='intelligence-dead-letter-list'),
    path('dead-letter/<uuid:pk>/requeue/', views.DeadLetterRequeueView.as_view(), name='intelligence-dead-letter-requeue'),
    path('connectors/', views.ConnectorListView.as_view(), name='intelligence-connector-list'),
    path('settings/', views.SettingsView.as_view(), name='intelligence-settings'),
    path('approvals/', views.ApprovalListView.as_view(), name='intelligence-approval-list'),
    path('approvals/<uuid:pk>/', views.ApprovalDetailView.as_view(), name='intelligence-approval-detail'),
    path('approvals/<uuid:pk>/approve/', views.ApprovalApproveView.as_view(), name='intelligence-approval-approve'),
    path('approvals/<uuid:pk>/reject/', views.ApprovalRejectView.as_view(), name='intelligence-approval-reject'),
]
