# Generated by Django 6.0.3 on 2026-04-04 19:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationCompletionCheck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('check_category', models.CharField(choices=[('engine_integration', 'Engine Integration'), ('api', 'API'), ('ui', 'UI'), ('governance', 'Governance'), ('reliability', 'Reliability'), ('permissions', 'Permissions'), ('tenant_isolation', 'Tenant Isolation'), ('analytics', 'Analytics'), ('ai', 'AI'), ('documentation', 'Documentation'), ('qa', 'QA')], max_length=50)),
                ('check_name', models.CharField(max_length=255)),
                ('check_status', models.CharField(choices=[('passed', 'Passed'), ('warning', 'Warning'), ('failed', 'Failed'), ('not_run', 'Not Run')], default='not_run', max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('result_summary', models.TextField(blank=True)),
                ('remediation_action', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'automation_completion_checks',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AutomationCompletionReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('report_type', models.CharField(choices=[('readiness_summary', 'Readiness Summary'), ('gap_report', 'Gap Report'), ('integration_report', 'Integration Report'), ('qa_report', 'QA Report'), ('production_launch_report', 'Production Launch Report'), ('executive_completion_report', 'Executive Completion Report')], max_length=50)),
                ('report_name', models.CharField(max_length=255)),
                ('report_payload', models.JSONField(default=dict)),
                ('generated_by', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'automation_completion_reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AutomationGapItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('gap_type', models.CharField(choices=[('missing_integration', 'Missing Integration'), ('broken_flow', 'Broken Flow'), ('missing_permission', 'Missing Permission'), ('missing_audit', 'Missing Audit'), ('missing_observability', 'Missing Observability'), ('missing_recovery', 'Missing Recovery'), ('missing_ui', 'Missing UI'), ('missing_api', 'Missing API'), ('missing_test', 'Missing Test'), ('missing_documentation', 'Missing Documentation')], max_length=50)),
                ('module_scope', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('impact_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('recommended_fix', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('acknowledged', 'Acknowledged'), ('fixed', 'Fixed'), ('ignored', 'Ignored')], default='open', max_length=20)),
            ],
            options={
                'db_table': 'automation_gap_items',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AutomationProductionGate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('gate_name', models.CharField(max_length=255)),
                ('gate_type', models.CharField(choices=[('governance_gate', 'Governance Gate'), ('reliability_gate', 'Reliability Gate'), ('security_gate', 'Security Gate'), ('isolation_gate', 'Isolation Gate'), ('observability_gate', 'Observability Gate'), ('qa_gate', 'QA Gate'), ('documentation_gate', 'Documentation Gate'), ('executive_gate', 'Executive Gate')], max_length=50)),
                ('required', models.BooleanField(default=True)),
                ('current_status', models.CharField(choices=[('pending', 'Pending'), ('passed', 'Passed'), ('blocked', 'Blocked'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('blocking_reason', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'automation_production_gates',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AutomationSystemReadiness',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('readiness_score', models.IntegerField(default=0)),
                ('readiness_status', models.CharField(choices=[('not_ready', 'Not Ready'), ('partial', 'Partial'), ('ready_with_warnings', 'Ready with Warnings'), ('production_ready', 'Production Ready')], default='not_ready', max_length=50)),
                ('engine_integration_score', models.IntegerField(default=0)),
                ('governance_score', models.IntegerField(default=0)),
                ('reliability_score', models.IntegerField(default=0)),
                ('intelligence_score', models.IntegerField(default=0)),
                ('security_score', models.IntegerField(default=0)),
                ('tenant_isolation_score', models.IntegerField(default=0)),
                ('documentation_score', models.IntegerField(default=0)),
                ('qa_score', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'automation_system_readiness',
                'ordering': ['-updated_at'],
            },
        ),
    ]
