# Generated by Django 6.0.3 on 2026-03-28 17:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewDecision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('interview_id', models.UUIDField(db_index=True, unique=True)),
                ('decision', models.CharField(choices=[('hire', 'Hire'), ('reject', 'Reject'), ('hold', 'Hold'), ('next_round', 'Next Round')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('decided_by', models.UUIDField()),
                ('decided_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'interviews_decision',
            },
        ),
        migrations.CreateModel(
            name='InterviewType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(db_index=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'interviews_type',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='interview',
            name='meeting_link',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='interviewtemplate',
            name='scoring_type',
            field=models.CharField(choices=[('numeric', 'Numeric (0–100)'), ('pass_fail', 'Pass / Fail'), ('criteria', 'Criteria-Based')], default='numeric', max_length=20),
        ),
        migrations.AlterField(
            model_name='interview',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show'), ('rescheduled', 'Rescheduled')], db_index=True, default='scheduled', max_length=50),
        ),
        migrations.AlterField(
            model_name='interviewpanelist',
            name='role',
            field=models.CharField(choices=[('lead', 'Lead'), ('panelist', 'Panelist'), ('observer', 'Observer'), ('note_taker', 'Note Taker')], default='panelist', max_length=50),
        ),
        migrations.AlterField(
            model_name='interviewtemplate',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.CreateModel(
            name='InterviewFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('interview_id', models.UUIDField(db_index=True)),
                ('panelist_id', models.UUIDField(db_index=True)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('notes', models.TextField(blank=True)),
                ('recommendation', models.CharField(blank=True, choices=[('hire', 'Hire'), ('reject', 'Reject'), ('hold', 'Hold'), ('next_round', 'Next Round')], max_length=20)),
                ('criteria_scores', models.JSONField(blank=True, default=dict)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'interviews_feedback',
                'unique_together': {('interview_id', 'panelist_id')},
            },
        ),
        migrations.AddField(
            model_name='interviewtemplate',
            name='type',
            field=models.ForeignKey(blank=True, db_column='type_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates', to='interviews.interviewtype'),
        ),
    ]
