# Generated by Django 6.0.3 on 2026-03-28 20:20

import apps.interviews.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0005_scorecard_engine'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewAvailabilityBlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('interviewer_id', models.UUIDField(db_index=True)),
                ('starts_at', models.DateTimeField(db_index=True)),
                ('ends_at', models.DateTimeField(db_index=True)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('source', models.CharField(default='manual', max_length=30)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'interviews_availability_block',
                'ordering': ['starts_at'],
            },
        ),
        migrations.CreateModel(
            name='InterviewSchedulingLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('interview_id', models.UUIDField(db_index=True)),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('max_bookings', models.IntegerField(default=1)),
                ('booking_count', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('last_selected_slot', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'interviews_scheduling_link',
            },
        ),
        migrations.CreateModel(
            name='InterviewAvailabilityProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('interviewer_id', models.UUIDField(db_index=True)),
                ('mode', models.CharField(choices=[('system', 'System Availability'), ('calendar', 'Calendar Based Availability'), ('manual', 'Manual Scheduling'), ('candidate_self', 'Candidate Self Scheduling')], default='system', max_length=20)),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('working_hours', models.JSONField(blank=True, default=apps.interviews.models.default_working_hours)),
                ('default_duration_minutes', models.IntegerField(default=60)),
                ('default_buffer_minutes', models.IntegerField(default=15)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'interviews_availability_profile',
                'constraints': [models.UniqueConstraint(fields=('tenant_id', 'interviewer_id'), name='uniq_availability_profile_tenant_interviewer')],
            },
        ),
        migrations.CreateModel(
            name='InterviewCalendarConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('interviewer_id', models.UUIDField(db_index=True)),
                ('provider', models.CharField(choices=[('google', 'Google Calendar'), ('outlook', 'Outlook Calendar'), ('apple', 'Apple Calendar'), ('ics', 'ICS Feed')], max_length=20)),
                ('external_calendar_id', models.CharField(blank=True, max_length=255)),
                ('account_email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('sync_enabled', models.BooleanField(default=False)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'interviews_calendar_connection',
                'constraints': [models.UniqueConstraint(fields=('tenant_id', 'interviewer_id', 'provider', 'external_calendar_id'), name='uniq_calendar_connection_scope')],
            },
        ),
    ]
