# Generated by Django 6.0.3 on 2026-03-28 20:36

from django.db import migrations, models


REGISTRY_SEED = [
    ('recruiter_screening', 'Recruiter Screening', 'Initial recruiter-driven qualification round.', 'manual'),
    ('ai_screening', 'AI Screening', 'Automated AI-based screening flow.', 'native'),
    ('one_way_video', 'One Way Video', 'Candidate submits prerecorded responses.', 'native'),
    ('phone_interview', 'Phone Interview', 'Phone-based interview round.', 'manual'),
    ('async_text', 'Async Text', 'Asynchronous text-based Q&A interview.', 'async'),
    ('technical_interview', 'Technical Interview', 'General technical depth assessment.', 'manual'),
    ('coding_interview', 'Coding Interview', 'Hands-on coding evaluation.', 'native'),
    ('system_design', 'System Design', 'Architecture and design interview.', 'manual'),
    ('take_home_assignment', 'Take Home Assignment', 'Offline assignment based evaluation.', 'async'),
    ('debugging_interview', 'Debugging Interview', 'Candidate debugging capability test.', 'manual'),
    ('whiteboard', 'Whiteboard Interview', 'Whiteboard problem-solving round.', 'manual'),
    ('technical_panel', 'Technical Panel', 'Panel interview with technical stakeholders.', 'manual'),
    ('behavioral', 'Behavioral Interview', 'Behavior and competency assessment.', 'manual'),
    ('culture_fit', 'Culture Fit', 'Values and culture alignment check.', 'manual'),
    ('hr_interview', 'HR Interview', 'HR process and policy discussion round.', 'manual'),
    ('leadership', 'Leadership Interview', 'Leadership capability evaluation.', 'manual'),
    ('executive', 'Executive Interview', 'Executive leadership round.', 'manual'),
    ('hiring_manager', 'Hiring Manager Interview', 'Role and team fit with hiring manager.', 'manual'),
    ('panel', 'Panel Interview', 'Multi-interviewer panel evaluation.', 'manual'),
    ('sequential', 'Sequential Interview', 'Back-to-back interview sequence.', 'manual'),
    ('stakeholder', 'Stakeholder Interview', 'Cross-functional stakeholder round.', 'manual'),
    ('bar_raiser', 'Bar Raiser', 'Independent quality benchmark interview.', 'manual'),
    ('final_round', 'Final Round', 'Final decision-making interview round.', 'manual'),
    ('mcq_assessment', 'MCQ Assessment', 'Multiple-choice assessment.', 'native'),
    ('aptitude', 'Aptitude Assessment', 'Aptitude test round.', 'native'),
    ('psychometric', 'Psychometric Assessment', 'Psychometric fit evaluation.', 'third_party'),
    ('cognitive', 'Cognitive Assessment', 'Cognitive skills measurement.', 'third_party'),
    ('language', 'Language Assessment', 'Language proficiency evaluation.', 'native'),
    ('case_study', 'Case Study', 'Case-solving interview format.', 'manual'),
    ('role_play', 'Role Play', 'Scenario-based role play assessment.', 'manual'),
    ('work_sample', 'Work Sample', 'Real-work sample based assessment.', 'external'),
    ('presentation', 'Presentation Round', 'Presentation and communication round.', 'manual'),
    ('portfolio_review', 'Portfolio Review', 'Portfolio and project review round.', 'manual'),
    ('group_discussion', 'Group Discussion', 'Group dynamics and communication round.', 'manual'),
    ('assessment_center', 'Assessment Center', 'Composite multi-exercise assessment.', 'third_party'),
    ('mock', 'Mock Interview', 'Practice/mock interview session.', 'manual'),
    ('campus', 'Campus Interview', 'Campus hiring interview format.', 'manual'),
    ('walkin', 'Walk-in Interview', 'Walk-in hiring interview flow.', 'manual'),
    ('interview_cafe', 'Interview Cafe', 'Interview cafe style execution.', 'native'),
    ('live_video', 'Live Video Interview', 'Synchronous live video interview.', 'native'),
]


def seed_interview_type_registry(apps, schema_editor):
    InterviewType = apps.get_model('interviews', 'InterviewType')
    default_cfg = {
        'template': True,
        'scorecard': True,
        'scheduling': True,
        'automation': True,
        'prequalification': True,
    }
    for code, name, description, execution_mode in REGISTRY_SEED:
        InterviewType.objects.update_or_create(
            code=code,
            defaults={
                'name': name,
                'description': description,
                'execution_mode': execution_mode,
                'configurable': True,
                'type_configuration': default_cfg,
                'is_active': True,
                'is_deleted': False,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0006_interviewavailabilityblock_interviewschedulinglink_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewtype',
            name='configurable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='interviewtype',
            name='execution_mode',
            field=models.CharField(choices=[('native', 'Native'), ('third_party', 'Third Party'), ('external', 'External'), ('manual', 'Manual'), ('async', 'Async')], default='native', max_length=20),
        ),
        migrations.AddField(
            model_name='interviewtype',
            name='type_configuration',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='interview',
            name='interview_type',
            field=models.CharField(choices=[('technical', 'Technical'), ('recruiter_screening', 'Recruiter Screening'), ('ai_screening', 'AI Screening'), ('one_way_video', 'One Way Video'), ('phone_interview', 'Phone Interview'), ('async_text', 'Async Text'), ('technical_interview', 'Technical Interview'), ('coding_interview', 'Coding Interview'), ('system_design', 'System Design'), ('take_home_assignment', 'Take Home Assignment'), ('debugging_interview', 'Debugging Interview'), ('whiteboard', 'Whiteboard Interview'), ('technical_panel', 'Technical Panel'), ('behavioral', 'Behavioral Interview'), ('culture_fit', 'Culture Fit'), ('hr_interview', 'HR Interview'), ('leadership', 'Leadership Interview'), ('executive', 'Executive Interview'), ('hiring_manager', 'Hiring Manager Interview'), ('panel', 'Panel Interview'), ('sequential', 'Sequential Interview'), ('stakeholder', 'Stakeholder Interview'), ('bar_raiser', 'Bar Raiser'), ('final_round', 'Final Round'), ('mcq_assessment', 'MCQ Assessment'), ('aptitude', 'Aptitude Assessment'), ('psychometric', 'Psychometric Assessment'), ('cognitive', 'Cognitive Assessment'), ('language', 'Language Assessment'), ('case_study', 'Case Study'), ('role_play', 'Role Play'), ('work_sample', 'Work Sample'), ('presentation', 'Presentation Round'), ('portfolio_review', 'Portfolio Review'), ('group_discussion', 'Group Discussion'), ('assessment_center', 'Assessment Center'), ('mock', 'Mock Interview'), ('campus', 'Campus Interview'), ('walkin', 'Walk-in Interview'), ('interview_cafe', 'Interview Cafe'), ('live_video', 'Live Video Interview')], default='ai_screening', max_length=50),
        ),
        migrations.AlterField(
            model_name='interviewscorecardtemplate',
            name='interview_type',
            field=models.CharField(choices=[('technical', 'Technical'), ('recruiter_screening', 'Recruiter Screening'), ('ai_screening', 'AI Screening'), ('one_way_video', 'One Way Video'), ('phone_interview', 'Phone Interview'), ('async_text', 'Async Text'), ('technical_interview', 'Technical Interview'), ('coding_interview', 'Coding Interview'), ('system_design', 'System Design'), ('take_home_assignment', 'Take Home Assignment'), ('debugging_interview', 'Debugging Interview'), ('whiteboard', 'Whiteboard Interview'), ('technical_panel', 'Technical Panel'), ('behavioral', 'Behavioral Interview'), ('culture_fit', 'Culture Fit'), ('hr_interview', 'HR Interview'), ('leadership', 'Leadership Interview'), ('executive', 'Executive Interview'), ('hiring_manager', 'Hiring Manager Interview'), ('panel', 'Panel Interview'), ('sequential', 'Sequential Interview'), ('stakeholder', 'Stakeholder Interview'), ('bar_raiser', 'Bar Raiser'), ('final_round', 'Final Round'), ('mcq_assessment', 'MCQ Assessment'), ('aptitude', 'Aptitude Assessment'), ('psychometric', 'Psychometric Assessment'), ('cognitive', 'Cognitive Assessment'), ('language', 'Language Assessment'), ('case_study', 'Case Study'), ('role_play', 'Role Play'), ('work_sample', 'Work Sample'), ('presentation', 'Presentation Round'), ('portfolio_review', 'Portfolio Review'), ('group_discussion', 'Group Discussion'), ('assessment_center', 'Assessment Center'), ('mock', 'Mock Interview'), ('campus', 'Campus Interview'), ('walkin', 'Walk-in Interview'), ('interview_cafe', 'Interview Cafe'), ('live_video', 'Live Video Interview')], default='ai_screening', max_length=50),
        ),
        migrations.AlterField(
            model_name='interviewtemplate',
            name='interview_type',
            field=models.CharField(choices=[('technical', 'Technical'), ('recruiter_screening', 'Recruiter Screening'), ('ai_screening', 'AI Screening'), ('one_way_video', 'One Way Video'), ('phone_interview', 'Phone Interview'), ('async_text', 'Async Text'), ('technical_interview', 'Technical Interview'), ('coding_interview', 'Coding Interview'), ('system_design', 'System Design'), ('take_home_assignment', 'Take Home Assignment'), ('debugging_interview', 'Debugging Interview'), ('whiteboard', 'Whiteboard Interview'), ('technical_panel', 'Technical Panel'), ('behavioral', 'Behavioral Interview'), ('culture_fit', 'Culture Fit'), ('hr_interview', 'HR Interview'), ('leadership', 'Leadership Interview'), ('executive', 'Executive Interview'), ('hiring_manager', 'Hiring Manager Interview'), ('panel', 'Panel Interview'), ('sequential', 'Sequential Interview'), ('stakeholder', 'Stakeholder Interview'), ('bar_raiser', 'Bar Raiser'), ('final_round', 'Final Round'), ('mcq_assessment', 'MCQ Assessment'), ('aptitude', 'Aptitude Assessment'), ('psychometric', 'Psychometric Assessment'), ('cognitive', 'Cognitive Assessment'), ('language', 'Language Assessment'), ('case_study', 'Case Study'), ('role_play', 'Role Play'), ('work_sample', 'Work Sample'), ('presentation', 'Presentation Round'), ('portfolio_review', 'Portfolio Review'), ('group_discussion', 'Group Discussion'), ('assessment_center', 'Assessment Center'), ('mock', 'Mock Interview'), ('campus', 'Campus Interview'), ('walkin', 'Walk-in Interview'), ('interview_cafe', 'Interview Cafe'), ('live_video', 'Live Video Interview')], default='ai_screening', max_length=50),
        ),
        migrations.RunPython(seed_interview_type_registry, migrations.RunPython.noop),
    ]
