# Generated by Django 6.0.3 on 2026-04-05 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0012_interviewreviewtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewpackagebinding',
            name='auto_pass_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='interviewpackagebinding',
            name='auto_reject_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='interviewpackagebinding',
            name='manual_review_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='interviewpackagebinding',
            name='rounds_override',
            field=models.JSONField(blank=True, default=list, help_text='Override the rounds defined in the package.'),
        ),
    ]
