# Generated by Django 6.0.3 on 2026-04-03 17:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestration_center', '0007_aigovernanceapproval_aigovernancerule'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationLibraryTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('template_name', models.CharField(max_length=255)),
                ('template_type', models.CharField(choices=[('followup_sequence', 'Follow-up Sequence'), ('reminder_workflow', 'Reminder Workflow'), ('escalation_workflow', 'Escalation Workflow'), ('review_workflow', 'Review Workflow'), ('decision_workflow', 'Decision Workflow'), ('communication_workflow', 'Communication Workflow')], db_index=True, max_length=64)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('hiring', 'Hiring'), ('interview', 'Interview'), ('candidate_followup', 'Candidate Follow-up'), ('agency_management', 'Agency Management'), ('decision_support', 'Decision Support'), ('compliance', 'Compliance')], db_index=True, max_length=64)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='low', max_length=32)),
                ('config_payload', models.JSONField(blank=True, default=dict)),
                ('is_system_template', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'db_table': 'icc_automation_library_templates',
                'ordering': ['-is_system_template', 'template_name'],
            },
        ),
    ]
