# Generated by Django 6.0.3 on 2026-04-05 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orchestration_center', '0015_automationgovernanceaudit_automationusagelimit_and_more'),
        ('orchestration_center', '0015_workflowtemplate_workflow_stages'),
    ]

    operations = [
    ]
