# Generated by Django 6.0.3 on 2026-04-07 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestration_center', '0016_merge_20260405_1843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflowtemplate',
            name='workflow_stages',
        ),
        migrations.AlterField(
            model_name='workflownode',
            name='node_type',
            field=models.CharField(choices=[('start', 'Start'), ('condition', 'Condition'), ('action', 'Action'), ('delay', 'Delay'), ('approval', 'Approval'), ('human_task', 'Human Task'), ('scheduling', 'Scheduling'), ('document', 'Document'), ('integration', 'Integration'), ('end', 'End')], max_length=32),
        ),
    ]
