# Generated by Django 6.0.3 on 2026-04-07 17:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestration_center', '0017_remove_workflowtemplate_workflow_stages_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowEventDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_key', models.CharField(db_index=True, max_length=128, unique=True)),
                ('event_name', models.CharField(max_length=255)),
                ('module_scope', models.CharField(db_index=True, max_length=64)),
                ('description', models.TextField(blank=True)),
                ('payload_schema', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Workflow Event Definition',
                'db_table': 'icc_workflow_event_definitions',
                'ordering': ['module_scope', 'event_name'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowEventLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('event_key', models.CharField(db_index=True, max_length=128)),
                ('entity_type', models.CharField(db_index=True, max_length=64)),
                ('entity_id', models.CharField(db_index=True, max_length=64)),
                ('payload', models.JSONField(default=dict)),
                ('source_module', models.CharField(db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('emitted', 'Emitted'), ('consumed', 'Consumed'), ('failed', 'Failed'), ('ignored', 'Ignored')], default='emitted', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'icc_workflow_event_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowEventDebugTrace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('decision', models.CharField(choices=[('matched', 'Matched'), ('filtered_out', 'Filtered Out'), ('blocked', 'Blocked'), ('executed', 'Executed'), ('failed', 'Failed')], max_length=32)),
                ('reason', models.TextField(blank=True)),
                ('trace_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orchestration_center.workflow')),
                ('event_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debug_traces', to='orchestration_center.workfloweventlog')),
            ],
            options={
                'db_table': 'icc_workflow_event_debug_traces',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowEventSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('trigger_filters', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('event_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='orchestration_center.workfloweventdefinition')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_subscriptions', to='orchestration_center.workflow')),
            ],
            options={
                'db_table': 'icc_workflow_event_subscriptions',
                'unique_together': {('workflow', 'event_definition', 'tenant_id')},
            },
        ),
    ]
