# Generated by Django 6.0.3 on 2026-03-20 17:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('application_id', models.UUIDField(db_index=True)),
                ('candidate_id', models.UUIDField(db_index=True)),
                ('job_id', models.UUIDField(db_index=True)),
                ('template_id', models.UUIDField(blank=True, null=True)),
                ('interview_type', models.CharField(choices=[('ai_screening', 'AI Screening'), ('one_way_video', 'One-Way Video'), ('live_video', 'Live Video'), ('panel', 'Panel'), ('technical', 'Technical'), ('group_discussion', 'Group Discussion'), ('psychometric', 'Psychometric'), ('case_study', 'Case Study'), ('mock', 'Mock')], default='ai_screening', max_length=50)),
                ('interview_round', models.IntegerField(default=1)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show'), ('rescheduled', 'Rescheduled')], default='scheduled', max_length=50)),
                ('interview_link', models.TextField(blank=True)),
                ('recording_url', models.TextField(blank=True)),
                ('overall_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ai_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('human_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('recommendation', models.CharField(blank=True, choices=[('strongly_recommend', 'Strongly Recommend'), ('recommend', 'Recommend'), ('neutral', 'Neutral'), ('not_recommend', 'Not Recommend'), ('reject', 'Reject')], max_length=50)),
                ('feedback_summary', models.TextField(blank=True)),
                ('anti_cheat_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('anti_cheat_flags', models.JSONField(blank=True, default=list)),
                ('is_cafe_interview', models.BooleanField(default=False)),
                ('cafe_session_id', models.UUIDField(blank=True, null=True)),
                ('product', models.CharField(choices=[('ats', 'ATS'), ('cafe', 'Cafe'), ('marketplace', 'Marketplace')], default='ats', max_length=20)),
            ],
            options={
                'db_table': 'interviews_interview',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InterviewPanelist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('interview_id', models.UUIDField(db_index=True)),
                ('interviewer_id', models.UUIDField(db_index=True)),
                ('role', models.CharField(choices=[('lead', 'Lead'), ('interviewer', 'Interviewer'), ('observer', 'Observer')], default='interviewer', max_length=50)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('feedback', models.TextField(blank=True)),
                ('recommendation', models.CharField(blank=True, max_length=50)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('deadline_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'interviews_panelist',
            },
        ),
        migrations.CreateModel(
            name='InterviewQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('interview_id', models.UUIDField(db_index=True)),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('text', 'Text'), ('video', 'Video'), ('audio', 'Audio'), ('code', 'Code'), ('multiple_choice', 'Multiple Choice'), ('rating_scale', 'Rating Scale')], default='text', max_length=50)),
                ('expected_duration_seconds', models.IntegerField(blank=True, null=True)),
                ('candidate_answer', models.TextField(blank=True)),
                ('candidate_video_url', models.TextField(blank=True)),
                ('ai_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ai_feedback', models.TextField(blank=True)),
                ('human_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('human_feedback', models.TextField(blank=True)),
                ('order_index', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'interviews_question',
                'ordering': ['order_index'],
            },
        ),
        migrations.CreateModel(
            name='InterviewTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('interview_type', models.CharField(choices=[('ai_screening', 'AI Screening'), ('one_way_video', 'One-Way Video'), ('live_video', 'Live Video'), ('panel', 'Panel'), ('technical', 'Technical'), ('group_discussion', 'Group Discussion'), ('psychometric', 'Psychometric'), ('case_study', 'Case Study'), ('mock', 'Mock')], default='ai_screening', max_length=50)),
                ('duration_minutes', models.IntegerField(default=30)),
                ('instructions', models.TextField(blank=True)),
                ('passing_threshold', models.DecimalField(decimal_places=2, default=60, max_digits=5)),
                ('auto_shortlist_above', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('auto_reject_below', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('anti_cheat_enabled', models.BooleanField(default=True)),
                ('recording_enabled', models.BooleanField(default=True)),
                ('questions', models.JSONField(blank=True, default=list)),
                ('scoring_criteria', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'interviews_template',
            },
        ),
    ]
