# Generated by Django 6.0.3 on 2026-03-28 20:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0007_interviewtype_configurable_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewDecisionHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('interview_id', models.UUIDField(db_index=True)),
                ('decision_id', models.UUIDField(db_index=True)),
                ('previous_decision', models.CharField(blank=True, choices=[('hire', 'Hire'), ('reject', 'Reject'), ('hold', 'Hold'), ('next_round', 'Next Round'), ('manual_review', 'Manual Review'), ('assignment', 'Assignment'), ('panel_required', 'Panel Required'), ('escalate', 'Escalate')], max_length=20)),
                ('new_decision', models.CharField(choices=[('hire', 'Hire'), ('reject', 'Reject'), ('hold', 'Hold'), ('next_round', 'Next Round'), ('manual_review', 'Manual Review'), ('assignment', 'Assignment'), ('panel_required', 'Panel Required'), ('escalate', 'Escalate')], max_length=20)),
                ('changed_by', models.UUIDField()),
                ('change_source', models.CharField(choices=[('manual', 'Manual'), ('scorecard', 'Scorecard'), ('interviewer_feedback', 'Interviewer Feedback'), ('prequalification', 'Prequalification'), ('skill_matching', 'Skill Matching'), ('automation_rules', 'Automation Rules')], default='manual', max_length=30)),
                ('is_override', models.BooleanField(default=False)),
                ('override_reason', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'interviews_decision_history',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.AddField(
            model_name='interviewdecision',
            name='decision_mode',
            field=models.CharField(choices=[('manual', 'Manual'), ('auto', 'Auto'), ('conditional', 'Conditional')], default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='interviewdecision',
            name='decision_source',
            field=models.CharField(choices=[('manual', 'Manual'), ('scorecard', 'Scorecard'), ('interviewer_feedback', 'Interviewer Feedback'), ('prequalification', 'Prequalification'), ('skill_matching', 'Skill Matching'), ('automation_rules', 'Automation Rules')], default='manual', max_length=30),
        ),
        migrations.AddField(
            model_name='interviewdecision',
            name='is_override',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='interviewdecision',
            name='overridden_by',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewdecision',
            name='override_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='interviewdecision',
            name='previous_decision',
            field=models.CharField(blank=True, choices=[('hire', 'Hire'), ('reject', 'Reject'), ('hold', 'Hold'), ('next_round', 'Next Round'), ('manual_review', 'Manual Review'), ('assignment', 'Assignment'), ('panel_required', 'Panel Required'), ('escalate', 'Escalate')], max_length=20),
        ),
        migrations.AlterField(
            model_name='interviewdecision',
            name='decision',
            field=models.CharField(choices=[('hire', 'Hire'), ('reject', 'Reject'), ('hold', 'Hold'), ('next_round', 'Next Round'), ('manual_review', 'Manual Review'), ('assignment', 'Assignment'), ('panel_required', 'Panel Required'), ('escalate', 'Escalate')], max_length=20),
        ),
        migrations.AlterField(
            model_name='interviewfeedback',
            name='recommendation',
            field=models.CharField(blank=True, choices=[('hire', 'Hire'), ('reject', 'Reject'), ('hold', 'Hold'), ('next_round', 'Next Round'), ('manual_review', 'Manual Review'), ('assignment', 'Assignment'), ('panel_required', 'Panel Required'), ('escalate', 'Escalate')], max_length=20),
        ),
    ]
