# Generated by Django 6.0.3 on 2026-03-28 21:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0008_interviewdecisionhistory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewIntegrationProvider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(db_index=True, max_length=80, unique=True)),
                ('provider_type', models.CharField(choices=[('meeting', 'Meeting'), ('calendar', 'Calendar'), ('external', 'External')], max_length=30)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('tenant_configurable', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'interviews_integration_provider',
                'ordering': ['provider_type', 'name'],
            },
        ),
        migrations.AddField(
            model_name='interview',
            name='execution_mode',
            field=models.CharField(choices=[('native', 'Native'), ('third_party', 'Third Party'), ('external_manual', 'External Manual')], db_index=True, default='native', max_length=30),
        ),
        migrations.AddField(
            model_name='interview',
            name='execution_provider_code',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='interview',
            name='external_interview_link',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='meeting_provider_code',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.CreateModel(
            name='InterviewExecutionMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('interview_type', models.CharField(db_index=True, max_length=50)),
                ('stage_code', models.CharField(blank=True, db_index=True, max_length=80)),
                ('execution_mode', models.CharField(choices=[('native', 'Native'), ('third_party', 'Third Party'), ('external_manual', 'External Manual')], default='native', max_length=30)),
                ('provider_code', models.CharField(blank=True, db_index=True, max_length=80)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'interviews_execution_mapping',
                'constraints': [models.UniqueConstraint(fields=('tenant_id', 'interview_type', 'stage_code'), name='uniq_tenant_interview_execution_mapping')],
            },
        ),
        migrations.CreateModel(
            name='InterviewTenantProviderConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('auth_data', models.JSONField(blank=True, default=dict)),
                ('config_data', models.JSONField(blank=True, default=dict)),
                ('is_enabled', models.BooleanField(db_index=True, default=True)),
                ('connection_status', models.CharField(default='configured', max_length=30)),
                ('last_validated_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_connections', to='interviews.interviewintegrationprovider')),
            ],
            options={
                'db_table': 'interviews_tenant_provider_connection',
                'constraints': [models.UniqueConstraint(fields=('tenant_id', 'provider'), name='uniq_tenant_provider_connection')],
            },
        ),
    ]
