# Generated by Django 6.0.3 on 2026-03-28 21:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0009_interviewintegrationprovider_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewQuestionBank',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('scope', models.CharField(choices=[('global', 'Global'), ('tenant', 'Tenant'), ('template', 'Template')], db_index=True, default='tenant', max_length=20)),
                ('question_title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('question_type', models.CharField(choices=[('text', 'Text Question'), ('multiple_choice', 'Multiple Choice'), ('multi_select', 'Multi Select'), ('coding', 'Coding Question (Shell)'), ('file_upload', 'File Upload'), ('video', 'Video Question (Shell)'), ('rating', 'Rating Question'), ('yes_no', 'Yes / No')], default='text', max_length=30)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=20)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('options_json', models.JSONField(blank=True, default=list)),
                ('expected_answer', models.TextField(blank=True)),
                ('scoring_weight', models.DecimalField(decimal_places=2, default=1, max_digits=6)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'interviews_question_bank',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InterviewQuestionGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('scope', models.CharField(choices=[('global', 'Global'), ('tenant', 'Tenant'), ('template', 'Template')], db_index=True, default='tenant', max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('section_name', models.CharField(blank=True, max_length=120)),
                ('target_type', models.CharField(choices=[('template', 'Template'), ('interview_type', 'Interview Type'), ('assessment', 'Assessment')], default='template', max_length=20)),
                ('target_ref', models.CharField(blank=True, db_index=True, max_length=120)),
                ('order_index', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'interviews_question_group',
                'ordering': ['order_index', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='InterviewQuestionAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('attach_type', models.CharField(choices=[('template', 'Template'), ('interview_type', 'Interview Type'), ('assessment', 'Assessment')], db_index=True, max_length=20)),
                ('template_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('interview_type', models.CharField(blank=True, db_index=True, max_length=80)),
                ('assessment_ref', models.CharField(blank=True, db_index=True, max_length=120)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('order_index', models.IntegerField(default=0)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='interviews.interviewquestionbank')),
            ],
            options={
                'db_table': 'interviews_question_attachment',
                'ordering': ['order_index', 'created_at'],
                'constraints': [models.UniqueConstraint(fields=('tenant_id', 'question', 'attach_type', 'template_id', 'interview_type', 'assessment_ref'), name='uniq_question_attachment_scope')],
            },
        ),
        migrations.CreateModel(
            name='InterviewQuestionGroupItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_index', models.IntegerField(default=0)),
                ('required', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='interviews.interviewquestiongroup')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_items', to='interviews.interviewquestionbank')),
            ],
            options={
                'db_table': 'interviews_question_group_item',
                'ordering': ['order_index', 'created_at'],
                'constraints': [models.UniqueConstraint(fields=('group', 'question'), name='uniq_question_group_item')],
            },
        ),
    ]
