# Generated by Django 6.0.3 on 2026-04-01 09:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0010_interviewquestionbank_interviewquestiongroup_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewPackage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('rounds', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'interviews_package',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='interview',
            name='interview_type',
            field=models.CharField(choices=[('technical', 'Technical'), ('recruiter_screening', 'Recruiter Screening'), ('ai_screening', 'AI Screening'), ('ai_technical', 'AI Technical'), ('ai_behavioral', 'AI Behavioral'), ('one_way_video', 'One Way Video'), ('phone_interview', 'Phone Interview'), ('async_text', 'Async Text'), ('async_audio', 'Async Audio'), ('technical_interview', 'Technical Interview'), ('coding_interview', 'Coding Interview'), ('system_design', 'System Design'), ('take_home_assignment', 'Take Home Assignment'), ('debugging_interview', 'Debugging Interview'), ('whiteboard', 'Whiteboard Interview'), ('technical_panel', 'Technical Panel'), ('behavioral', 'Behavioral Interview'), ('culture_fit', 'Culture Fit'), ('hr_interview', 'HR Interview'), ('leadership', 'Leadership Interview'), ('executive', 'Executive Interview'), ('hiring_manager', 'Hiring Manager Interview'), ('panel', 'Panel Interview'), ('sequential', 'Sequential Interview'), ('stakeholder', 'Stakeholder Interview'), ('bar_raiser', 'Bar Raiser'), ('final_round', 'Final Round'), ('mcq_assessment', 'MCQ Assessment'), ('aptitude', 'Aptitude Assessment'), ('psychometric', 'Psychometric Assessment'), ('cognitive', 'Cognitive Assessment'), ('language', 'Language Assessment'), ('case_study', 'Case Study'), ('role_play', 'Role Play'), ('work_sample', 'Work Sample'), ('presentation', 'Presentation Round'), ('portfolio_review', 'Portfolio Review'), ('group_discussion', 'Group Discussion'), ('assessment_center', 'Assessment Center'), ('mock', 'Mock Interview'), ('campus', 'Campus Interview'), ('walkin', 'Walk-in Interview'), ('interview_cafe', 'Interview Cafe'), ('live_video', 'Live Video Interview')], default='ai_screening', max_length=50),
        ),
        migrations.AlterField(
            model_name='interviewscorecardtemplate',
            name='interview_type',
            field=models.CharField(choices=[('technical', 'Technical'), ('recruiter_screening', 'Recruiter Screening'), ('ai_screening', 'AI Screening'), ('ai_technical', 'AI Technical'), ('ai_behavioral', 'AI Behavioral'), ('one_way_video', 'One Way Video'), ('phone_interview', 'Phone Interview'), ('async_text', 'Async Text'), ('async_audio', 'Async Audio'), ('technical_interview', 'Technical Interview'), ('coding_interview', 'Coding Interview'), ('system_design', 'System Design'), ('take_home_assignment', 'Take Home Assignment'), ('debugging_interview', 'Debugging Interview'), ('whiteboard', 'Whiteboard Interview'), ('technical_panel', 'Technical Panel'), ('behavioral', 'Behavioral Interview'), ('culture_fit', 'Culture Fit'), ('hr_interview', 'HR Interview'), ('leadership', 'Leadership Interview'), ('executive', 'Executive Interview'), ('hiring_manager', 'Hiring Manager Interview'), ('panel', 'Panel Interview'), ('sequential', 'Sequential Interview'), ('stakeholder', 'Stakeholder Interview'), ('bar_raiser', 'Bar Raiser'), ('final_round', 'Final Round'), ('mcq_assessment', 'MCQ Assessment'), ('aptitude', 'Aptitude Assessment'), ('psychometric', 'Psychometric Assessment'), ('cognitive', 'Cognitive Assessment'), ('language', 'Language Assessment'), ('case_study', 'Case Study'), ('role_play', 'Role Play'), ('work_sample', 'Work Sample'), ('presentation', 'Presentation Round'), ('portfolio_review', 'Portfolio Review'), ('group_discussion', 'Group Discussion'), ('assessment_center', 'Assessment Center'), ('mock', 'Mock Interview'), ('campus', 'Campus Interview'), ('walkin', 'Walk-in Interview'), ('interview_cafe', 'Interview Cafe'), ('live_video', 'Live Video Interview')], default='ai_screening', max_length=50),
        ),
        migrations.AlterField(
            model_name='interviewtemplate',
            name='interview_type',
            field=models.CharField(choices=[('technical', 'Technical'), ('recruiter_screening', 'Recruiter Screening'), ('ai_screening', 'AI Screening'), ('ai_technical', 'AI Technical'), ('ai_behavioral', 'AI Behavioral'), ('one_way_video', 'One Way Video'), ('phone_interview', 'Phone Interview'), ('async_text', 'Async Text'), ('async_audio', 'Async Audio'), ('technical_interview', 'Technical Interview'), ('coding_interview', 'Coding Interview'), ('system_design', 'System Design'), ('take_home_assignment', 'Take Home Assignment'), ('debugging_interview', 'Debugging Interview'), ('whiteboard', 'Whiteboard Interview'), ('technical_panel', 'Technical Panel'), ('behavioral', 'Behavioral Interview'), ('culture_fit', 'Culture Fit'), ('hr_interview', 'HR Interview'), ('leadership', 'Leadership Interview'), ('executive', 'Executive Interview'), ('hiring_manager', 'Hiring Manager Interview'), ('panel', 'Panel Interview'), ('sequential', 'Sequential Interview'), ('stakeholder', 'Stakeholder Interview'), ('bar_raiser', 'Bar Raiser'), ('final_round', 'Final Round'), ('mcq_assessment', 'MCQ Assessment'), ('aptitude', 'Aptitude Assessment'), ('psychometric', 'Psychometric Assessment'), ('cognitive', 'Cognitive Assessment'), ('language', 'Language Assessment'), ('case_study', 'Case Study'), ('role_play', 'Role Play'), ('work_sample', 'Work Sample'), ('presentation', 'Presentation Round'), ('portfolio_review', 'Portfolio Review'), ('group_discussion', 'Group Discussion'), ('assessment_center', 'Assessment Center'), ('mock', 'Mock Interview'), ('campus', 'Campus Interview'), ('walkin', 'Walk-in Interview'), ('interview_cafe', 'Interview Cafe'), ('live_video', 'Live Video Interview')], default='ai_screening', max_length=50),
        ),
        migrations.CreateModel(
            name='InterviewPackageBinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('job_id', models.UUIDField(db_index=True, unique=True)),
                ('automation_enabled', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_bindings', to='interviews.interviewpackage')),
            ],
            options={
                'db_table': 'interviews_package_binding',
            },
        ),
    ]
