# Generated by Django 6.0.3 on 2026-04-01 16:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0011_interviewpackage_alter_interview_interview_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewReviewTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('interview_id', models.UUIDField(db_index=True)),
                ('review_type', models.CharField(db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('assigned_role', models.CharField(blank=True, max_length=64)),
                ('assigned_reviewer_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('requested_by', models.UUIDField(blank=True, db_index=True, null=True)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('external_reference', models.CharField(blank=True, db_index=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'interviews_review_task',
                'ordering': ['-created_at'],
            },
        ),
    ]
