# Generated by Django 6.0.3 on 2026-04-04 19:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationLearningEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('workflow_id', models.UUIDField(db_index=True)),
                ('event_type', models.CharField(choices=[('workflow_success', 'Workflow Success'), ('workflow_failure', 'Workflow Failure'), ('manual_override', 'Manual Override'), ('retry_success', 'Retry Success'), ('retry_failure', 'Retry Failure'), ('fallback_used', 'Fallback Used'), ('slow_execution', 'Slow Execution')], max_length=50)),
                ('event_data', models.JSONField(blank=True, default=dict)),
                ('outcome', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'db_table': 'automation_learning_events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AutomationLearningModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('model_type', models.CharField(choices=[('failure_prediction', 'Failure Prediction'), ('delay_prediction', 'Delay Prediction'), ('optimization_prediction', 'Optimization Prediction'), ('automation_recommendation', 'Automation Recommendation')], max_length=50)),
                ('training_data_range', models.JSONField(blank=True, default=dict)),
                ('accuracy_score', models.FloatField(default=0.0)),
                ('last_trained_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'automation_learning_models',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AutomationLearningPattern',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('pattern_type', models.CharField(choices=[('repeated_failure', 'Repeated Failure'), ('repeated_manual_action', 'Repeated Manual Action'), ('delay_pattern', 'Delay Pattern'), ('dependency_pattern', 'Dependency Pattern'), ('user_behavior_pattern', 'User Behavior Pattern')], max_length=50)),
                ('module_scope', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField()),
                ('frequency', models.IntegerField(default=1)),
                ('confidence_score', models.FloatField(default=0.0)),
            ],
            options={
                'db_table': 'automation_learning_patterns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AutomationOptimizationSuggestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('suggestion_type', models.CharField(choices=[('optimize_workflow', 'Optimize Workflow'), ('add_fallback', 'Add Fallback'), ('adjust_priority', 'Adjust Priority'), ('add_retry', 'Add Retry'), ('create_new_workflow', 'Create New Workflow'), ('modify_sla', 'Modify SLA')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('expected_impact', models.TextField(blank=True)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('applied', 'Applied'), ('dismissed', 'Dismissed')], default='pending', max_length=20)),
            ],
            options={
                'db_table': 'automation_optimization_suggestions',
                'ordering': ['-created_at'],
            },
        ),
    ]
