# Generated by Django 6.0.3

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0009_messageattachment_usernotificationpreference_and_more'),
    ]

    operations = [
        # Migration 0009 already added the critical fields and models.
        # This migration is a placeholder to keep Django state in sync without 
        # performing risky index/column renames that failed previously.
    ]
