# Generated by Django 6.0.3 on 2026-04-08 15:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow_execution', '0009_sla_index_and_start_alignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowNotificationRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('workflow_id', models.UUIDField(db_index=True)),
                ('stage_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('trigger_type', models.CharField(choices=[('stage_started', 'Stage Started'), ('stage_completed', 'Stage Completed'), ('wait_started', 'Wait Started'), ('wait_resumed', 'Wait Resumed'), ('sla_warning', 'SLA Warning'), ('sla_breach', 'SLA Breach'), ('escalation', 'Escalation'), ('workflow_failed', 'Workflow Failed'), ('workflow_completed', 'Workflow Completed')], db_index=True, max_length=32)),
                ('recipient_type', models.CharField(choices=[('workflow_owner', 'Workflow Owner'), ('assigned_actor', 'Assigned Actor'), ('recruiter', 'Recruiter'), ('hiring_manager', 'Hiring Manager'), ('hr', 'HR'), ('candidate', 'Candidate'), ('agency_recruiter', 'Agency Recruiter'), ('admin', 'Admin')], db_index=True, max_length=32)),
                ('channel', models.CharField(choices=[('in_app', 'In App'), ('email', 'Email'), ('whatsapp', 'WhatsApp'), ('sms', 'SMS')], db_index=True, max_length=16)),
                ('template_key', models.CharField(db_index=True, max_length=128)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'db_table': 'wf_exec_wfnotif_rules',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['workflow_id', 'trigger_type', 'is_active'], name='wf_exec_not_workflo_d2a4c8_idx'), models.Index(fields=['workflow_id', 'stage_id', 'trigger_type', 'is_active'], name='wf_exec_not_workflo_cbf91c_idx')],
            },
        ),
        migrations.CreateModel(
            name='WorkflowNotificationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('recipient_type', models.CharField(choices=[('workflow_owner', 'Workflow Owner'), ('assigned_actor', 'Assigned Actor'), ('recruiter', 'Recruiter'), ('hiring_manager', 'Hiring Manager'), ('hr', 'HR'), ('candidate', 'Candidate'), ('agency_recruiter', 'Agency Recruiter'), ('admin', 'Admin')], db_index=True, max_length=32)),
                ('recipient_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('channel', models.CharField(choices=[('in_app', 'In App'), ('email', 'Email'), ('whatsapp', 'WhatsApp'), ('sms', 'SMS')], db_index=True, max_length=16)),
                ('template_key', models.CharField(db_index=True, max_length=128)),
                ('message_preview', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped')], db_index=True, default='queued', max_length=16)),
                ('sent_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('stage_execution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_logs', to='workflow_execution.workflowstageexecution')),
                ('workflow_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to='workflow_execution.workflowinstance')),
            ],
            options={
                'db_table': 'wf_exec_wfnotif_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['workflow_instance', 'status'], name='wf_exec_not_workflo_300e52_idx'), models.Index(fields=['channel', 'status'], name='wf_exec_not_channel_58fd01_idx')],
            },
        ),
        migrations.CreateModel(
            name='WorkflowNotificationQueue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('recipient_type', models.CharField(choices=[('workflow_owner', 'Workflow Owner'), ('assigned_actor', 'Assigned Actor'), ('recruiter', 'Recruiter'), ('hiring_manager', 'Hiring Manager'), ('hr', 'HR'), ('candidate', 'Candidate'), ('agency_recruiter', 'Agency Recruiter'), ('admin', 'Admin')], db_index=True, max_length=32)),
                ('recipient_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('channel', models.CharField(choices=[('in_app', 'In App'), ('email', 'Email'), ('whatsapp', 'WhatsApp'), ('sms', 'SMS')], db_index=True, max_length=16)),
                ('template_key', models.CharField(db_index=True, max_length=128)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('sent', 'Sent'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=16)),
                ('scheduled_at', models.DateTimeField(db_index=True)),
                ('processed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('stage_execution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_queue_items', to='workflow_execution.workflowstageexecution')),
                ('workflow_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_queue_items', to='workflow_execution.workflowinstance')),
            ],
            options={
                'db_table': 'wf_exec_wfnotif_queue',
                'ordering': ['scheduled_at', 'created_at'],
                'indexes': [models.Index(fields=['status', 'scheduled_at'], name='wf_exec_not_status_6f4faf_idx'), models.Index(fields=['workflow_instance', 'status'], name='wf_exec_not_workflo_ca59dd_idx')],
            },
        ),
    ]
