# Generated by Django 6.0.3 on 2026-04-08 15:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow_execution', '0011_rename_wf_exec_not_workflo_300e52_idx_wf_exec_wfn_workflo_6429c1_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowScheduledTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('task_type', models.CharField(choices=[('stage_transition', 'Stage Transition'), ('wait_resume', 'Wait Resume'), ('retry_stage', 'Retry Stage'), ('sla_check', 'SLA Check'), ('escalation_check', 'Escalation Check'), ('notification_dispatch', 'Notification Dispatch'), ('workflow_resume', 'Workflow Resume')], db_index=True, max_length=32)),
                ('scheduled_at', models.DateTimeField(db_index=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='scheduled', max_length=16)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('executed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('stage_execution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_tasks', to='workflow_execution.workflowstageexecution')),
                ('workflow_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_tasks', to='workflow_execution.workflowinstance')),
            ],
            options={
                'db_table': 'wf_exec_sched_tasks',
                'ordering': ['scheduled_at', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowSchedulerLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('task_type', models.CharField(choices=[('stage_transition', 'Stage Transition'), ('wait_resume', 'Wait Resume'), ('retry_stage', 'Retry Stage'), ('sla_check', 'SLA Check'), ('escalation_check', 'Escalation Check'), ('notification_dispatch', 'Notification Dispatch'), ('workflow_resume', 'Workflow Resume')], db_index=True, max_length=32)),
                ('status', models.CharField(choices=[('started', 'Started'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, max_length=16)),
                ('message', models.TextField(blank=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduler_logs', to='workflow_execution.workflowscheduledtask')),
                ('workflow_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduler_logs', to='workflow_execution.workflowinstance')),
            ],
            options={
                'db_table': 'wf_exec_sched_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='workflowscheduledtask',
            index=models.Index(fields=['status', 'scheduled_at'], name='wf_exec_sch_status_55527d_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowscheduledtask',
            index=models.Index(fields=['workflow_instance', 'status'], name='wf_exec_sch_workflo_ff42d2_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowschedulerlog',
            index=models.Index(fields=['workflow_instance', 'status'], name='wf_exec_sch_workflo_cf8a83_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowschedulerlog',
            index=models.Index(fields=['task_type', 'status'], name='wf_exec_sch_task_ty_0c7dc3_idx'),
        ),
    ]
