# Generated by Django 6.0.3 on 2026-04-08 15:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow_execution', '0012_workflowscheduledtask_workflowschedulerlog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowConditionGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('workflow_id', models.UUIDField(db_index=True)),
                ('stage_id', models.UUIDField(db_index=True)),
                ('group_name', models.CharField(db_index=True, default='default', max_length=128)),
                ('success_transition_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('failure_transition_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('default_transition_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'db_table': 'wf_exec_condition_groups',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['workflow_id', 'stage_id', 'is_active'], name='wf_exec_con_workflo_987be9_idx'), models.Index(fields=['workflow_id', 'stage_id', 'group_name', 'is_active'], name='wf_exec_con_workflo_10e8bb_idx')],
            },
        ),
        migrations.CreateModel(
            name='WorkflowConditionRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('workflow_id', models.UUIDField(db_index=True)),
                ('stage_id', models.UUIDField(db_index=True)),
                ('rule_name', models.CharField(max_length=255)),
                ('rule_group', models.CharField(db_index=True, default='default', max_length=128)),
                ('condition_type', models.CharField(choices=[('workflow_context', 'Workflow Context'), ('entity_field', 'Entity Field'), ('actor_field', 'Actor Field'), ('score_field', 'Score Field'), ('status_field', 'Status Field'), ('time_field', 'Time Field'), ('custom', 'Custom')], db_index=True, max_length=32)),
                ('field_name', models.CharField(db_index=True, max_length=255)),
                ('operator', models.CharField(choices=[('equals', 'Equals'), ('not_equals', 'Not Equals'), ('greater_than', 'Greater Than'), ('less_than', 'Less Than'), ('greater_or_equal', 'Greater Or Equal'), ('less_or_equal', 'Less Or Equal'), ('contains', 'Contains'), ('not_contains', 'Not Contains'), ('in_list', 'In List'), ('not_in_list', 'Not In List'), ('is_true', 'Is True'), ('is_false', 'Is False'), ('exists', 'Exists'), ('not_exists', 'Not Exists')], db_index=True, max_length=32)),
                ('expected_value', models.JSONField(blank=True, default=dict)),
                ('logical_join', models.CharField(choices=[('AND', 'AND'), ('OR', 'OR')], default='AND', max_length=3)),
                ('priority', models.IntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'db_table': 'wf_exec_condition_rules',
                'ordering': ['priority', 'created_at'],
                'indexes': [models.Index(fields=['workflow_id', 'stage_id', 'rule_group', 'is_active'], name='wf_exec_con_workflo_2bdb86_idx'), models.Index(fields=['workflow_id', 'stage_id', 'priority'], name='wf_exec_con_workflo_b0d8a6_idx')],
            },
        ),
        migrations.CreateModel(
            name='WorkflowConditionEvaluationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('evaluated_value', models.JSONField(blank=True, default=dict)),
                ('expected_value', models.JSONField(blank=True, default=dict)),
                ('result', models.CharField(choices=[('passed', 'Passed'), ('failed', 'Failed'), ('skipped', 'Skipped')], db_index=True, max_length=16)),
                ('reason', models.TextField(blank=True)),
                ('stage_execution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='condition_evaluation_logs', to='workflow_execution.workflowstageexecution')),
                ('workflow_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condition_evaluation_logs', to='workflow_execution.workflowinstance')),
                ('condition_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluation_logs', to='workflow_execution.workflowconditiongroup')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluation_logs', to='workflow_execution.workflowconditionrule')),
            ],
            options={
                'db_table': 'wf_exec_condition_eval_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['workflow_instance', 'result'], name='wf_exec_con_workflo_8bb948_idx'), models.Index(fields=['condition_group', 'result'], name='wf_exec_con_conditi_88f9ea_idx')],
            },
        ),
    ]
