# Generated by Django 6.0.3 on 2026-04-08 15:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow_execution', '0013_workflowconditiongroup_workflowconditionrule_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowActionDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('workflow_id', models.UUIDField(db_index=True)),
                ('stage_id', models.UUIDField(db_index=True)),
                ('action_name', models.CharField(max_length=255)),
                ('action_type', models.CharField(choices=[('assign_actor', 'Assign Actor'), ('create_task', 'Create Task'), ('send_notification', 'Send Notification'), ('update_entity_status', 'Update Entity Status'), ('move_stage', 'Move Stage'), ('create_interview', 'Create Interview'), ('update_interview', 'Update Interview'), ('create_offer', 'Create Offer'), ('update_offer', 'Update Offer'), ('generate_document', 'Generate Document'), ('create_sla', 'Create SLA'), ('create_handoff', 'Create Handoff'), ('schedule_action', 'Schedule Action'), ('create_note', 'Create Note'), ('add_tag', 'Add Tag'), ('request_approval', 'Request Approval')], db_index=True, max_length=32)),
                ('action_config', models.JSONField(blank=True, default=dict)),
                ('execution_order', models.IntegerField(db_index=True, default=0)),
                ('run_mode', models.CharField(choices=[('immediate', 'Immediate'), ('deferred', 'Deferred'), ('async', 'Async')], db_index=True, default='immediate', max_length=16)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'db_table': 'wf_exec_action_defs',
                'ordering': ['execution_order', 'created_at'],
                'indexes': [models.Index(fields=['workflow_id', 'stage_id', 'is_active', 'execution_order'], name='wf_exec_act_workflo_cb0b3a_idx')],
            },
        ),
        migrations.CreateModel(
            name='WorkflowActionDependency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('dependency_type', models.CharField(choices=[('must_complete_first', 'Must Complete First'), ('run_if_success', 'Run If Success'), ('run_if_failed', 'Run If Failed')], db_index=True, default='must_complete_first', max_length=32)),
                ('action_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='workflow_execution.workflowactiondefinition')),
                ('depends_on_action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependents', to='workflow_execution.workflowactiondefinition')),
            ],
            options={
                'db_table': 'wf_exec_action_dependencies',
                'ordering': ['created_at'],
                'constraints': [models.UniqueConstraint(fields=('action_definition', 'depends_on_action', 'dependency_type'), name='wf_exec_action_dependency_unique')],
            },
        ),
        migrations.CreateModel(
            name='WorkflowActionExecutionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('action_type', models.CharField(choices=[('assign_actor', 'Assign Actor'), ('create_task', 'Create Task'), ('send_notification', 'Send Notification'), ('update_entity_status', 'Update Entity Status'), ('move_stage', 'Move Stage'), ('create_interview', 'Create Interview'), ('update_interview', 'Update Interview'), ('create_offer', 'Create Offer'), ('update_offer', 'Update Offer'), ('generate_document', 'Generate Document'), ('create_sla', 'Create SLA'), ('create_handoff', 'Create Handoff'), ('schedule_action', 'Schedule Action'), ('create_note', 'Create Note'), ('add_tag', 'Add Tag'), ('request_approval', 'Request Approval')], db_index=True, max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped'), ('deferred', 'Deferred')], db_index=True, default='pending', max_length=16)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('execution_result', models.JSONField(blank=True, default=dict)),
                ('action_definition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='execution_logs', to='workflow_execution.workflowactiondefinition')),
                ('stage_execution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_execution_logs', to='workflow_execution.workflowstageexecution')),
                ('workflow_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_execution_logs', to='workflow_execution.workflowinstance')),
            ],
            options={
                'db_table': 'wf_exec_action_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['workflow_instance', 'status'], name='wf_exec_act_workflo_111513_idx'), models.Index(fields=['action_type', 'status'], name='wf_exec_act_action__87d4bc_idx')],
            },
        ),
    ]
