# Generated by Django 6.0.3 on 2026-04-08 16:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow_execution', '0014_workflowactiondefinition_workflowactiondependency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowApprovalRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('workflow_id', models.UUIDField(db_index=True)),
                ('stage_id', models.UUIDField(db_index=True)),
                ('approval_type', models.CharField(choices=[('single', 'Single'), ('multiple', 'Multiple'), ('sequential', 'Sequential'), ('parallel', 'Parallel')], db_index=True, default='single', max_length=16)),
                ('required_approvals', models.PositiveIntegerField(default=1)),
                ('approval_role', models.CharField(blank=True, max_length=64)),
                ('escalation_role', models.CharField(blank=True, max_length=64)),
                ('timeout_hours', models.PositiveIntegerField(default=24)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'db_table': 'wf_exec_approval_rules',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['workflow_id', 'stage_id', 'is_active'], name='wf_exec_app_workflo_7882c7_idx')],
            },
        ),
        migrations.CreateModel(
            name='WorkflowHumanTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('task_type', models.CharField(choices=[('review', 'Review'), ('approval', 'Approval'), ('decision', 'Decision'), ('feedback', 'Feedback'), ('confirmation', 'Confirmation'), ('document_review', 'Document Review'), ('scheduling', 'Scheduling'), ('custom', 'Custom')], db_index=True, max_length=32)),
                ('assigned_to_type', models.CharField(blank=True, choices=[('recruiter', 'Recruiter'), ('hiring_manager', 'Hiring Manager'), ('hr', 'HR'), ('agency_recruiter', 'Agency Recruiter'), ('candidate', 'Candidate'), ('interviewer', 'Interviewer'), ('system', 'System')], db_index=True, max_length=32)),
                ('assigned_to_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='medium', max_length=16)),
                ('due_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=16)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('stage_execution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='human_tasks', to='workflow_execution.workflowstageexecution')),
                ('workflow_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='human_tasks', to='workflow_execution.workflowinstance')),
            ],
            options={
                'db_table': 'wf_exec_human_tasks',
                'ordering': ['due_at', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowApprovalLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('approver_type', models.CharField(choices=[('recruiter', 'Recruiter'), ('hiring_manager', 'Hiring Manager'), ('hr', 'HR'), ('agency_recruiter', 'Agency Recruiter'), ('candidate', 'Candidate'), ('interviewer', 'Interviewer'), ('system', 'System')], db_index=True, max_length=32)),
                ('approver_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('decision', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('requested_changes', 'Requested Changes')], db_index=True, max_length=32)),
                ('comments', models.TextField(blank=True)),
                ('workflow_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_logs', to='workflow_execution.workflowinstance')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_logs', to='workflow_execution.workflowhumantask')),
            ],
            options={
                'db_table': 'wf_exec_approval_logs',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='workflowhumantask',
            index=models.Index(fields=['workflow_instance', 'status'], name='wf_exec_hum_workflo_db5228_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowhumantask',
            index=models.Index(fields=['assigned_to_id', 'status'], name='wf_exec_hum_assigne_3844be_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowapprovallog',
            index=models.Index(fields=['workflow_instance', 'decision'], name='wf_exec_app_workflo_a54ca7_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowapprovallog',
            index=models.Index(fields=['task', 'decision'], name='wf_exec_app_task_id_9ea490_idx'),
        ),
    ]
