# Generated by Django 6.0.3 on 2026-04-08 16:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow_execution', '0015_workflowapprovalrule_workflowhumantask_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowinstance',
            name='version_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.CreateModel(
            name='WorkflowVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('workflow_id', models.UUIDField(db_index=True)),
                ('version_number', models.PositiveIntegerField(db_index=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived'), ('rolled_back', 'Rolled Back')], db_index=True, default='draft', max_length=16)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'wf_exec_versions',
                'ordering': ['-version_number', '-created_at'],
                'indexes': [models.Index(fields=['workflow_id', 'status'], name='wf_exec_ver_workflo_db0635_idx')],
                'constraints': [models.UniqueConstraint(fields=('workflow_id', 'version_number'), name='wf_exec_version_unique')],
            },
        ),
        migrations.CreateModel(
            name='WorkflowDraft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('workflow_id', models.UUIDField(db_index=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('config_snapshot', models.JSONField(blank=True, default=dict)),
                ('builder_mode', models.CharField(choices=[('guided', 'Guided'), ('advanced', 'Advanced')], db_index=True, default='guided', max_length=16)),
                ('status', models.CharField(choices=[('editing', 'Editing'), ('ready_for_publish', 'Ready For Publish'), ('published', 'Published'), ('discarded', 'Discarded')], db_index=True, default='editing', max_length=32)),
                ('version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drafts', to='workflow_execution.workflowversion')),
            ],
            options={
                'db_table': 'wf_exec_drafts',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['workflow_id', 'status'], name='wf_exec_dra_workflo_37fbd6_idx')],
            },
        ),
        migrations.CreateModel(
            name='WorkflowVersionChangeLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('workflow_id', models.UUIDField(db_index=True)),
                ('change_type', models.CharField(choices=[('created', 'Created'), ('edited', 'Edited'), ('published', 'Published'), ('rolled_back', 'Rolled Back'), ('discarded', 'Discarded'), ('cloned', 'Cloned')], db_index=True, max_length=16)),
                ('changed_by', models.UUIDField(blank=True, db_index=True, null=True)),
                ('change_summary', models.TextField(blank=True)),
                ('version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_logs', to='workflow_execution.workflowversion')),
            ],
            options={
                'db_table': 'wf_exec_version_change_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['workflow_id', 'change_type'], name='wf_exec_ver_workflo_b24c98_idx')],
            },
        ),
        migrations.CreateModel(
            name='WorkflowVersionComparison',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('workflow_id', models.UUIDField(db_index=True)),
                ('comparison_result', models.JSONField(blank=True, default=dict)),
                ('from_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons_from', to='workflow_execution.workflowversion')),
                ('to_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons_to', to='workflow_execution.workflowversion')),
            ],
            options={
                'db_table': 'wf_exec_version_comparisons',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['workflow_id'], name='wf_exec_ver_workflo_bca392_idx')],
            },
        ),
    ]
