# Generated by Django 6.0.3 on 2026-04-08 16:20

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow_execution', '0016_workflowinstance_version_id_workflowversion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('standard_hiring', 'Standard Hiring'), ('high_volume_hiring', 'High Volume Hiring'), ('executive_hiring', 'Executive Hiring'), ('agency_hiring', 'Agency Hiring'), ('campus_hiring', 'Campus Hiring'), ('contract_hiring', 'Contract Hiring'), ('custom', 'Custom')], db_index=True, default='custom', max_length=64)),
                ('template_type', models.CharField(choices=[('system', 'System'), ('company', 'Company'), ('agency', 'Agency'), ('custom', 'Custom')], db_index=True, default='custom', max_length=16)),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('organization', 'Organization'), ('public', 'Public')], db_index=True, default='private', max_length=16)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'db_table': 'wf_exec_templates',
                'ordering': ['category', 'name', '-updated_at'],
                'indexes': [models.Index(fields=['template_type', 'visibility', 'is_active'], name='wf_exec_tem_templat_41a8f8_idx'), models.Index(fields=['category', 'is_active'], name='wf_exec_tem_categor_db3632_idx')],
            },
        ),
        migrations.CreateModel(
            name='WorkflowTemplateRating',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('rating', models.PositiveSmallIntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('review', models.TextField(blank=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='workflow_execution.workflowtemplate')),
            ],
            options={
                'db_table': 'wf_exec_template_ratings',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['template', 'rating'], name='wf_exec_tem_templat_b203bd_idx')],
            },
        ),
        migrations.CreateModel(
            name='WorkflowTemplateUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('workflow_id', models.UUIDField(db_index=True)),
                ('used_by', models.UUIDField(blank=True, db_index=True, null=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='workflow_execution.workflowtemplate')),
            ],
            options={
                'db_table': 'wf_exec_template_usage',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['template', 'tenant_id'], name='wf_exec_tem_templat_e59ddd_idx'), models.Index(fields=['workflow_id', 'tenant_id'], name='wf_exec_tem_workflo_310911_idx')],
            },
        ),
        migrations.CreateModel(
            name='WorkflowTemplateVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('version_number', models.PositiveIntegerField(db_index=True)),
                ('config_snapshot', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='workflow_execution.workflowtemplate')),
            ],
            options={
                'db_table': 'wf_exec_template_versions',
                'ordering': ['-version_number', '-created_at'],
                'constraints': [models.UniqueConstraint(fields=('template', 'version_number'), name='wf_exec_template_version_unique')],
            },
        ),
    ]
