# Generated by Django 6.0.3 on 2026-04-08 17:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow_execution', '0017_workflowtemplate_workflowtemplaterating_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowBuilderConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('workflow_id', models.UUIDField(db_index=True)),
                ('source_node_id', models.UUIDField(db_index=True)),
                ('target_node_id', models.UUIDField(db_index=True)),
                ('condition_label', models.CharField(blank=True, max_length=255)),
                ('connection_type', models.CharField(choices=[('default', 'Default'), ('success', 'Success'), ('failure', 'Failure'), ('conditional', 'Conditional'), ('approval', 'Approval'), ('rejection', 'Rejection')], db_index=True, default='default', max_length=32)),
            ],
            options={
                'db_table': 'wf_exec_builder_connections',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['workflow_id', 'source_node_id'], name='wf_exec_bui_workflo_8db8c8_idx'), models.Index(fields=['workflow_id', 'target_node_id'], name='wf_exec_bui_workflo_df8015_idx'), models.Index(fields=['workflow_id', 'connection_type'], name='wf_exec_bui_workflo_619d9c_idx')],
            },
        ),
        migrations.CreateModel(
            name='WorkflowBuilderLayout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('workflow_id', models.UUIDField(db_index=True)),
                ('canvas_config', models.JSONField(blank=True, default=dict)),
                ('zoom_level', models.FloatField(default=1.0)),
                ('viewport', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'wf_exec_builder_layouts',
                'ordering': ['-updated_at'],
                'constraints': [models.UniqueConstraint(fields=('workflow_id',), name='wf_exec_builder_layout_unique')],
            },
        ),
        migrations.CreateModel(
            name='WorkflowBuilderNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('workflow_id', models.UUIDField(db_index=True)),
                ('node_type', models.CharField(choices=[('start', 'Start'), ('stage', 'Stage'), ('decision', 'Decision'), ('action', 'Action'), ('human_task', 'Human Task'), ('approval', 'Approval'), ('delay', 'Delay'), ('end', 'End')], db_index=True, max_length=32)),
                ('node_name', models.CharField(max_length=255)),
                ('position_x', models.IntegerField(default=0)),
                ('position_y', models.IntegerField(default=0)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'db_table': 'wf_exec_builder_nodes',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['workflow_id', 'is_active'], name='wf_exec_bui_workflo_71a78e_idx'), models.Index(fields=['workflow_id', 'node_type', 'is_active'], name='wf_exec_bui_workflo_b65241_idx')],
            },
        ),
    ]
