# Generated by Django 6.0.3 on 2026-04-08 17:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow_execution', '0018_workflowbuilderconnection_workflowbuilderlayout_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowObservabilitySnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('current_stage_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('current_status', models.CharField(db_index=True, max_length=32)),
                ('wait_reason', models.CharField(blank=True, max_length=255)),
                ('active_actor_type', models.CharField(blank=True, max_length=64)),
                ('active_actor_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('pending_task_count', models.IntegerField(default=0)),
                ('pending_notification_count', models.IntegerField(default=0)),
                ('has_failure', models.BooleanField(db_index=True, default=False)),
                ('has_sla_risk', models.BooleanField(db_index=True, default=False)),
                ('workflow_instance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='observability_snapshot', to='workflow_execution.workflowinstance')),
            ],
            options={
                'db_table': 'wf_exec_obs_snapshots',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowExecutionMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('metric_name', models.CharField(db_index=True, max_length=128)),
                ('metric_value', models.FloatField(default=0.0)),
                ('metric_type', models.CharField(choices=[('duration', 'Duration'), ('wait_time', 'Wait Time'), ('retry_count', 'Retry Count'), ('action_count', 'Action Count'), ('failure_count', 'Failure Count'), ('stage_count', 'Stage Count'), ('handoff_count', 'Handoff Count')], db_index=True, max_length=32)),
                ('recorded_at', models.DateTimeField(db_index=True)),
                ('workflow_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_metrics', to='workflow_execution.workflowinstance')),
            ],
            options={
                'db_table': 'wf_exec_obs_metrics',
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['workflow_instance', 'metric_name', 'recorded_at'], name='wf_exec_obs_workflo_922a6f_idx'), models.Index(fields=['workflow_instance', 'metric_type', 'recorded_at'], name='wf_exec_obs_workflo_3c9d75_idx')],
            },
        ),
        migrations.CreateModel(
            name='WorkflowExecutionTimelineEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('entry_type', models.CharField(choices=[('workflow_started', 'Workflow Started'), ('stage_started', 'Stage Started'), ('stage_completed', 'Stage Completed'), ('transition_taken', 'Transition Taken'), ('decision_evaluated', 'Decision Evaluated'), ('action_executed', 'Action Executed'), ('wait_started', 'Wait Started'), ('wait_resumed', 'Wait Resumed'), ('human_task_created', 'Human Task Created'), ('human_task_completed', 'Human Task Completed'), ('approval_requested', 'Approval Requested'), ('approval_completed', 'Approval Completed'), ('sla_started', 'SLA Started'), ('sla_warning', 'SLA Warning'), ('sla_breached', 'SLA Breached'), ('routing_started', 'Routing Started'), ('routing_completed', 'Routing Completed'), ('notification_sent', 'Notification Sent'), ('failure_logged', 'Failure Logged'), ('retry_started', 'Retry Started'), ('workflow_completed', 'Workflow Completed'), ('workflow_failed', 'Workflow Failed')], db_index=True, max_length=32)),
                ('entry_label', models.CharField(max_length=255)),
                ('entry_description', models.TextField(blank=True)),
                ('actor_type', models.CharField(blank=True, max_length=64)),
                ('actor_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('stage_execution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observability_timeline_entries', to='workflow_execution.workflowstageexecution')),
                ('workflow_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observability_timeline_entries', to='workflow_execution.workflowinstance')),
            ],
            options={
                'db_table': 'wf_exec_obs_timeline_entries',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['workflow_instance', 'entry_type', 'created_at'], name='wf_exec_obs_workflo_8d9df9_idx'), models.Index(fields=['workflow_instance', 'created_at'], name='wf_exec_obs_workflo_a34968_idx')],
            },
        ),
        migrations.CreateModel(
            name='WorkflowExecutionTrace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('trace_key', models.CharField(db_index=True, max_length=128)),
                ('trace_type', models.CharField(choices=[('transition', 'Transition'), ('action', 'Action'), ('condition', 'Condition'), ('routing', 'Routing'), ('sla', 'SLA'), ('notification', 'Notification'), ('scheduler', 'Scheduler'), ('approval', 'Approval'), ('human_task', 'Human Task'), ('failure', 'Failure')], db_index=True, max_length=32)),
                ('source_module', models.CharField(db_index=True, max_length=128)),
                ('source_id', models.CharField(blank=True, max_length=128)),
                ('trace_message', models.TextField()),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], db_index=True, default='info', max_length=16)),
                ('workflow_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_traces', to='workflow_execution.workflowinstance')),
            ],
            options={
                'db_table': 'wf_exec_obs_traces',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['workflow_instance', 'trace_type', 'created_at'], name='wf_exec_obs_workflo_18ea1a_idx'), models.Index(fields=['workflow_instance', 'severity', 'created_at'], name='wf_exec_obs_workflo_b1f621_idx')],
            },
        ),
    ]
