# Generated by Django 6.0.3 on 2026-04-08 17:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow_execution', '0019_workflowobservabilitysnapshot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowscheduledtask',
            name='task_type',
            field=models.CharField(choices=[('stage_transition', 'Stage Transition'), ('wait_resume', 'Wait Resume'), ('retry_stage', 'Retry Stage'), ('recovery_retry', 'Recovery Retry'), ('sla_check', 'SLA Check'), ('escalation_check', 'Escalation Check'), ('notification_dispatch', 'Notification Dispatch'), ('workflow_resume', 'Workflow Resume')], db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='workflowschedulerlog',
            name='task_type',
            field=models.CharField(choices=[('stage_transition', 'Stage Transition'), ('wait_resume', 'Wait Resume'), ('retry_stage', 'Retry Stage'), ('recovery_retry', 'Recovery Retry'), ('sla_check', 'SLA Check'), ('escalation_check', 'Escalation Check'), ('notification_dispatch', 'Notification Dispatch'), ('workflow_resume', 'Workflow Resume')], db_index=True, max_length=32),
        ),
        migrations.CreateModel(
            name='WorkflowRecoveryCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('recovery_type', models.CharField(choices=[('stage_failure', 'Stage Failure'), ('action_failure', 'Action Failure'), ('transition_failure', 'Transition Failure'), ('routing_failure', 'Routing Failure'), ('notification_failure', 'Notification Failure'), ('sla_failure', 'SLA Failure'), ('scheduler_failure', 'Scheduler Failure'), ('human_task_failure', 'Human Task Failure')], db_index=True, max_length=32)),
                ('failure_type', models.CharField(choices=[('transient', 'Transient'), ('external_dependency', 'External Dependency'), ('validation', 'Validation'), ('permission', 'Permission'), ('data_integrity', 'Data Integrity'), ('timeout', 'Timeout'), ('logic_error', 'Logic Error'), ('unknown', 'Unknown')], db_index=True, default='unknown', max_length=32)),
                ('error_message', models.TextField(blank=True)),
                ('error_code', models.CharField(blank=True, db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('open', 'Open'), ('retry_scheduled', 'Retry Scheduled'), ('retrying', 'Retrying'), ('recovered', 'Recovered'), ('escalated', 'Escalated'), ('manual_intervention_required', 'Manual Intervention Required'), ('failed_permanently', 'Failed Permanently'), ('closed', 'Closed')], db_index=True, default='open', max_length=40)),
                ('retry_strategy', models.CharField(choices=[('immediate', 'Immediate'), ('delayed', 'Delayed'), ('exponential_backoff', 'Exponential Backoff'), ('manual_only', 'Manual Only'), ('no_retry', 'No Retry')], db_index=True, default='manual_only', max_length=32)),
                ('retry_limit', models.PositiveIntegerField(default=0)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('next_retry_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('action_execution_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recovery_cases', to='workflow_execution.workflowactionexecutionlog')),
                ('stage_execution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recovery_cases', to='workflow_execution.workflowstageexecution')),
                ('workflow_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recovery_cases', to='workflow_execution.workflowinstance')),
            ],
            options={
                'db_table': 'wf_exec_recovery_cases',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowRecoveryActionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('action_type', models.CharField(choices=[('retry_started', 'Retry Started'), ('retry_succeeded', 'Retry Succeeded'), ('retry_failed', 'Retry Failed'), ('escalated', 'Escalated'), ('manual_resume', 'Manual Resume'), ('manual_skip', 'Manual Skip'), ('manual_fail', 'Manual Fail'), ('workflow_recovered', 'Workflow Recovered'), ('permanent_failure', 'Permanent Failure')], db_index=True, max_length=32)),
                ('action_taken_by', models.CharField(blank=True, max_length=128)),
                ('action_summary', models.TextField(blank=True)),
                ('workflow_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recovery_action_logs', to='workflow_execution.workflowinstance')),
                ('recovery_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_logs', to='workflow_execution.workflowrecoverycase')),
            ],
            options={
                'db_table': 'wf_exec_recovery_action_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowRecoveryPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('workflow_id', models.UUIDField(db_index=True)),
                ('stage_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('action_type', models.CharField(blank=True, db_index=True, max_length=64)),
                ('failure_type', models.CharField(choices=[('transient', 'Transient'), ('external_dependency', 'External Dependency'), ('validation', 'Validation'), ('permission', 'Permission'), ('data_integrity', 'Data Integrity'), ('timeout', 'Timeout'), ('logic_error', 'Logic Error'), ('unknown', 'Unknown')], db_index=True, default='unknown', max_length=32)),
                ('retry_strategy', models.CharField(choices=[('immediate', 'Immediate'), ('delayed', 'Delayed'), ('exponential_backoff', 'Exponential Backoff'), ('manual_only', 'Manual Only'), ('no_retry', 'No Retry')], db_index=True, default='manual_only', max_length=32)),
                ('retry_limit', models.PositiveIntegerField(default=0)),
                ('retry_delay_seconds', models.PositiveIntegerField(default=0)),
                ('escalate_after_failures', models.PositiveIntegerField(default=0)),
                ('requires_manual_review', models.BooleanField(db_index=True, default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'db_table': 'wf_exec_recovery_policies',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['workflow_id', 'stage_id', 'failure_type', 'is_active'], name='wf_exec_rec_workflo_95c4b1_idx')],
            },
        ),
        migrations.CreateModel(
            name='WorkflowRetryAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('attempt_number', models.PositiveIntegerField()),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='running', max_length=16)),
                ('error_message', models.TextField(blank=True)),
                ('result_summary', models.JSONField(blank=True, default=dict)),
                ('recovery_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retry_attempts', to='workflow_execution.workflowrecoverycase')),
            ],
            options={
                'db_table': 'wf_exec_recovery_attempts',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddIndex(
            model_name='workflowrecoverycase',
            index=models.Index(fields=['workflow_instance', 'status'], name='wf_exec_rec_workflo_1b8ced_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowrecoverycase',
            index=models.Index(fields=['recovery_type', 'status'], name='wf_exec_rec_recover_9d4755_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowrecoverycase',
            index=models.Index(fields=['next_retry_at', 'status'], name='wf_exec_rec_next_re_d42177_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowrecoveryactionlog',
            index=models.Index(fields=['workflow_instance', 'action_type'], name='wf_exec_rec_workflo_d7d844_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowretryattempt',
            index=models.Index(fields=['recovery_case', 'attempt_number'], name='wf_exec_rec_recover_160bbe_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowretryattempt',
            index=models.Index(fields=['status', 'started_at'], name='wf_exec_rec_status_904368_idx'),
        ),
    ]
