# Generated by Django 6.0.3 on 2026-03-21 11:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateFormSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invite_link_id', models.UUIDField(db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('cv_url', models.TextField(blank=True)),
                ('cv_filename', models.CharField(blank=True, max_length=255)),
                ('form_data', models.JSONField(blank=True, default=dict)),
                ('candidate_id', models.UUIDField(blank=True, null=True)),
                ('user_id', models.UUIDField(blank=True, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=45)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('processed', 'Processed'), ('converted', 'Converted')], default='submitted', max_length=20)),
                ('wants_account', models.BooleanField(default=False)),
                ('account_created', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'candidates_form_submission',
            },
        ),
        migrations.CreateModel(
            name='CandidateInteraction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('candidate_id', models.UUIDField(db_index=True)),
                ('interaction_type', models.CharField(choices=[('call', 'Call'), ('email', 'Email'), ('whatsapp', 'WhatsApp'), ('note', 'Note'), ('meeting', 'Meeting'), ('linkedin', 'LinkedIn')], default='note', max_length=20)),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], default='outbound', max_length=10)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('content', models.TextField(blank=True)),
                ('outcome', models.CharField(blank=True, choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative'), ('no_response', 'No Response')], max_length=20)),
                ('next_followup_date', models.DateField(blank=True, null=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'crm_interaction',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CandidateInviteLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('token', models.CharField(max_length=100, unique=True)),
                ('form_config', models.JSONField(blank=True, default=dict)),
                ('job_id', models.UUIDField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('max_uses', models.IntegerField(blank=True, null=True)),
                ('use_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('disabled', 'Disabled')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'candidates_invite_link',
            },
        ),
        migrations.CreateModel(
            name='CandidatePipelineStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('candidate_id', models.UUIDField(db_index=True)),
                ('status', models.CharField(choices=[('new_lead', 'New Lead'), ('nurturing', 'Nurturing'), ('in_process', 'In Process'), ('offer_stage', 'Offer Stage'), ('placed', 'Placed'), ('lost', 'Lost')], default='new_lead', max_length=20)),
                ('assigned_to', models.UUIDField(blank=True, null=True)),
                ('next_action', models.CharField(blank=True, max_length=255)),
                ('next_action_date', models.DateField(blank=True, null=True)),
                ('last_contacted_at', models.DateTimeField(blank=True, null=True)),
                ('contact_count', models.IntegerField(default=0)),
                ('sentiment', models.CharField(choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative')], default='neutral', max_length=20)),
                ('source_job_id', models.UUIDField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'crm_pipeline_status',
                'unique_together': {('tenant_id', 'candidate_id')},
            },
        ),
    ]
