# Generated by Django 6.0.3 on 2026-03-21 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_candidateformsubmission_candidateinteraction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatepipelinestatus',
            name='status',
            field=models.CharField(choices=[('new_lead', 'New Lead'), ('nurturing', 'Nurturing'), ('in_process', 'In Process'), ('ready_to_submit', 'Ready to Submit'), ('submitted', 'Submitted'), ('offer_stage', 'Offer Stage'), ('placed', 'Placed'), ('lost', 'Lost')], default='new_lead', max_length=20),
        ),
    ]
