# Generated by Django 6.0.3 on 2026-03-22 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0003_alter_candidatepipelinestatus_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='account_status',
            field=models.CharField(choices=[('none', 'No Account'), ('invited', 'Invite Sent'), ('claimed', 'Account Claimed'), ('active', 'Active User')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='candidate',
            name='availability_status',
            field=models.CharField(blank=True, choices=[('available_now', 'Available Now'), ('notice_period', 'Serving Notice Period'), ('not_looking', 'Not Looking'), ('open_to_offers', 'Open to Offers')], max_length=50),
        ),
        migrations.AddField(
            model_name='candidate',
            name='claim_token',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name='candidate',
            name='claim_token_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='claimed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='counter_offer',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='current_ctc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='current_ctc_currency',
            field=models.CharField(blank=True, default='INR', max_length=10),
        ),
        migrations.AddField(
            model_name='candidate',
            name='designation',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='candidate',
            name='fitment_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='initial_entry_type',
            field=models.CharField(blank=True, choices=[('self', 'Self Registered'), ('invite', 'Invite Link'), ('manual', 'Manual Add'), ('passport_import', 'Passport Import'), ('agency_submission', 'Agency Submission')], max_length=20),
        ),
        migrations.AddField(
            model_name='candidate',
            name='invite_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='last_working_day',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='offer_in_hand',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='candidate',
            name='offer_in_hand_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='profile_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('partial', 'Partial'), ('complete', 'Complete'), ('claimed', 'Claimed')], default='partial', max_length=20),
        ),
        migrations.AddField(
            model_name='candidate',
            name='relevant_experience_years',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='work_mode_preference',
            field=models.CharField(blank=True, choices=[('any', 'Any'), ('remote', 'Remote Only'), ('hybrid', 'Hybrid'), ('onsite', 'On-site Only')], default='any', max_length=20),
        ),
    ]
