# Generated by Django 6.0.3 on 2026-03-25 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0011_candidate_active_job_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='engagement_stage',
            field=models.CharField(choices=[('new_lead', 'New Lead'), ('contacted', 'Contacted'), ('follow_up', 'Follow Up'), ('qualified', 'Qualified'), ('nurture', 'Nurture'), ('dormant', 'Dormant')], db_index=True, default='new_lead', max_length=30),
        ),
        migrations.AlterField(
            model_name='candidateengagement',
            name='stage',
            field=models.CharField(choices=[('new_lead', 'New Lead'), ('contacted', 'Contacted'), ('follow_up', 'Follow Up'), ('qualified', 'Qualified'), ('nurture', 'Nurture'), ('dormant', 'Dormant'), ('submitted', 'Submitted'), ('review', 'Review'), ('interviewing', 'Interviewing'), ('offered', 'Offered'), ('joined', 'Joined'), ('rejected', 'Rejected'), ('new', 'New (Legacy)'), ('not_interested', 'Not Interested (Legacy)'), ('shortlisted', 'Shortlisted Internally (Legacy)'), ('client_review', 'Client Review (Legacy)'), ('placed', 'Placed'), ('closed', 'Closed'), ('lost', 'Lost'), ('revived', 'Revived')], default='new_lead', max_length=50),
        ),
    ]
