# Generated by Django 6.0.3 on 2026-03-26 18:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0015_add_candidate_pool_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateTenantRight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('candidate_id', models.UUIDField(db_index=True)),
                ('source_tenant_id', models.UUIDField(db_index=True)),
                ('target_tenant_id', models.UUIDField(db_index=True)),
                ('relationship_type', models.CharField(choices=[('protected', 'Protected'), ('shared', 'Shared')], db_index=True, default='protected', max_length=30)),
                ('protected_until', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('context_job_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('allowed_job_ids', models.JSONField(blank=True, default=list)),
                ('retention_scope', models.CharField(default='job_only', max_length=40)),
                ('retention_start_type', models.CharField(default='submission_date', max_length=40)),
                ('retention_post_expiry', models.CharField(default='shared', max_length=40)),
                ('placed_via_source', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('active_shared', 'Active Shared'), ('expired', 'Expired'), ('pending_candidate_consent', 'Pending Candidate Consent'), ('released', 'Released')], db_index=True, default='active', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'candidates_tenant_rights',
                'indexes': [models.Index(fields=['candidate_id', 'target_tenant_id', 'status'], name='candidates__candida_98c97c_idx'), models.Index(fields=['source_tenant_id', 'target_tenant_id', 'status'], name='candidates__source__fca3ec_idx'), models.Index(fields=['protected_until', 'status'], name='candidates__protect_b41667_idx')],
            },
        ),
        migrations.CreateModel(
            name='CandidateRightsAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('candidate_id', models.UUIDField(db_index=True)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('action', models.CharField(db_index=True, max_length=80)),
                ('actor_user_id', models.UUIDField(blank=True, null=True)),
                ('actor_tenant_id', models.UUIDField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('tenant_right', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='candidates.candidatetenantright')),
            ],
            options={
                'db_table': 'candidates_rights_audit_log',
                'indexes': [models.Index(fields=['candidate_id', 'created_at'], name='candidates__candida_2303e0_idx'), models.Index(fields=['action', 'created_at'], name='candidates__action_0617fd_idx')],
            },
        ),
    ]
