# Generated by Django 6.0.3 on 2026-04-04 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0019_candidate_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateengagement',
            name='intent',
            field=models.CharField(choices=[('specific_job', 'For Specific Job'), ('future_jobs', 'For Future Jobs'), ('looking_for_job', 'Candidate Looking for Job'), ('just_lead', 'Just Lead / Not Sure')], db_index=True, default='just_lead', max_length=50),
        ),
        migrations.AddField(
            model_name='candidateengagement',
            name='is_nurture_track',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='candidateengagement',
            name='next_action_due_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='candidateengagement',
            name='next_action_owner_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidateengagement',
            name='next_action_priority',
            field=models.CharField(choices=[('hot', 'Hot'), ('warm', 'Warm'), ('cold', 'Cold')], default='warm', max_length=20),
        ),
        migrations.AddField(
            model_name='candidateengagement',
            name='next_action_reminder_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidateengagement',
            name='next_action_type',
            field=models.CharField(blank=True, choices=[('call', 'Call'), ('email', 'Email'), ('whatsapp', 'WhatsApp'), ('note', 'Note'), ('follow_up', 'Follow-up'), ('meeting', 'Meeting'), ('cv_requested', 'CV Requested'), ('no_response', 'No Response')], max_length=50, null=True),
        ),
    ]
