# Generated by Django 6.0.3 on 2026-04-04 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0021_candidatepipelinestatus_intent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatepipelinestatus',
            name='status',
            field=models.CharField(choices=[('new_lead', 'New Lead'), ('contacted', 'Contacted'), ('interested', 'Interested'), ('follow_up', 'Follow-up'), ('qualified', 'Qualified'), ('ready_for_job', 'Ready for Job'), ('submitted', 'Submitted'), ('future_talent', 'Future Talent'), ('not_interested', 'Not Interested'), ('archive', 'Archive')], default='new_lead', max_length=30),
        ),
    ]
