# Generated by Django 6.0.3 on 2026-04-04 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0022_alter_candidatepipelinestatus_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatepipelinestatus',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='candidatepipelinestatus',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
