# Generated by Django 6.0.3 on 2026-04-05 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automation_maturity', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='automationbusinesstransformationmetric',
            new_name='wf_maturity_tenant__812836_idx',
            old_name='am_biz_tenant_date_idx',
        ),
        migrations.RenameIndex(
            model_name='automationbusinesstransformationmetric',
            new_name='wf_maturity_tenant__8cdf7b_idx',
            old_name='am_biz_tenant_process_idx',
        ),
        migrations.RenameIndex(
            model_name='automationmaturityassessment',
            new_name='wf_maturity_tenant__b14e8e_idx',
            old_name='am_assess_tenant_date_idx',
        ),
        migrations.RenameIndex(
            model_name='automationmaturityassessment',
            new_name='wf_maturity_tenant__682a98_idx',
            old_name='am_assess_tenant_level_idx',
        ),
        migrations.RenameIndex(
            model_name='automationmaturityrecommendation',
            new_name='wf_maturity_tenant__50ca06_idx',
            old_name='am_rec_tenant_status_idx',
        ),
        migrations.RenameIndex(
            model_name='automationmaturityrecommendation',
            new_name='wf_maturity_tenant__71620b_idx',
            old_name='am_rec_tenant_priority_idx',
        ),
        migrations.RenameIndex(
            model_name='automationmaturityrecommendation',
            new_name='wf_maturity_tenant__d7ef0d_idx',
            old_name='am_rec_tenant_type_idx',
        ),
        migrations.RenameIndex(
            model_name='automationmaturityroadmap',
            new_name='wf_maturity_tenant__3930e4_idx',
            old_name='am_roadmap_tenant_active_idx',
        ),
        migrations.RenameIndex(
            model_name='automationmodulematurity',
            new_name='wf_maturity_tenant__48ff1a_idx',
            old_name='am_mod_tenant_scope_idx',
        ),
        migrations.RenameIndex(
            model_name='automationmodulematurity',
            new_name='wf_maturity_tenant__6d5544_idx',
            old_name='am_mod_tenant_assess_idx',
        ),
        migrations.RenameIndex(
            model_name='automationteamadoption',
            new_name='wf_maturity_tenant__1f2af2_idx',
            old_name='am_team_tenant_assess_idx',
        ),
    ]
