# Generated by Django 6.0.3 on 2026-03-25 18:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidates', '0012_alter_candidate_engagement_stage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TalentPool',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('tenant_type', models.CharField(choices=[('company', 'Company'), ('agency', 'Agency')], default='company', max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('pool_type', models.CharField(choices=[('manual', 'Manual'), ('smart', 'Smart')], default='manual', max_length=20)),
                ('color', models.CharField(blank=True, help_text='Hex code or color name for UI indicator', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filters_json', models.JSONField(blank=True, default=dict, help_text='Search filters for smart pools')),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Talent Pool',
                'verbose_name_plural': 'Talent Pools',
                'unique_together': {('tenant_id', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='CandidateTalentPoolMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('added_by', models.UUIDField(blank=True, null=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('rule', 'Rule'), ('import', 'Import')], default='manual', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pool_memberships', to='candidates.candidate')),
                ('talent_pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='talent_pools.talentpool')),
            ],
            options={
                'verbose_name': 'Candidate Talent Pool Membership',
                'verbose_name_plural': 'Candidate Talent Pool Memberships',
                'unique_together': {('candidate', 'talent_pool', 'tenant_id')},
            },
        ),
    ]
