# Generated by Django 6.0.3 on 2026-03-26 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('talent_pools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TalentPoolActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('event_type', models.CharField(db_index=True, max_length=100)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('system', 'System'), ('rule', 'Rule'), ('import', 'Import')], default='manual', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='talent_pool_activity_events', to=settings.AUTH_USER_MODEL)),
                ('talent_pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_events', to='talent_pools.talentpool')),
            ],
            options={
                'db_table': 'talent_pool_activity_events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='talentpoolactivity',
            index=models.Index(fields=['tenant_id', 'talent_pool', '-created_at'], name='talent_pool_tenant__fc7a95_idx'),
        ),
        migrations.AddIndex(
            model_name='talentpoolactivity',
            index=models.Index(fields=['event_type'], name='talent_pool_event_t_0bb5b8_idx'),
        ),
    ]
