# Generated by Django 6.0.3 on 2026-03-25 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talent_pools', '0002_talentpoolactivity'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='talentpoolactivity',
            new_name='talent_pool_tenant__05d87c_idx',
            old_name='talent_pool_tenant__fc7a95_idx',
        ),
        migrations.RenameIndex(
            model_name='talentpoolactivity',
            new_name='talent_pool_event_t_8bcc22_idx',
            old_name='talent_pool_event_t_0bb5b8_idx',
        ),
    ]
