# Generated by Django 6.0.3 on 2026-04-04 13:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowAnomaly',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('workflow_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('anomaly_type', models.CharField(choices=[('unusual_failure_rate', 'Unusual Failure Rate'), ('unusual_latency', 'Unusual Latency'), ('repeated_retries', 'Repeated Retries'), ('execution_loop', 'Execution Loop'), ('execution_stuck', 'Execution Stuck')], max_length=50)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], default='warning', max_length=20)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('investigating', 'Investigating'), ('resolved', 'Resolved')], default='open', max_length=20)),
            ],
            options={
                'db_table': 'icc_workflow_anomalies',
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowExecutionTrace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('workflow_id', models.UUIDField(db_index=True)),
                ('execution_id', models.UUIDField(db_index=True)),
                ('trace_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('node_id', models.UUIDField(blank=True, null=True)),
                ('event_type', models.CharField(max_length=100)),
                ('execution_time_ms', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('started', 'Started'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='started', max_length=20)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'icc_workflow_execution_traces',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowObservabilityEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('workflow_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('event_type', models.CharField(max_length=100)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], default='info', max_length=20)),
                ('message', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'icc_workflow_observability_events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowDependencyHealth',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('dependency_type', models.CharField(choices=[('notification', 'Notification Engine'), ('task_engine', 'Task Engine'), ('sla_engine', 'SLA Engine'), ('cross_module', 'Cross Module'), ('ai_engine', 'AI Engine'), ('permission_engine', 'Permission Engine')], max_length=50)),
                ('dependency_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('healthy', 'Healthy'), ('degraded', 'Degraded'), ('failed', 'Failed')], default='healthy', max_length=20)),
                ('last_checked_at', models.DateTimeField(auto_now=True)),
                ('failure_reason', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'icc_workflow_dependency_health',
                'unique_together': {('tenant_id', 'dependency_type')},
            },
        ),
    ]
