# Generated by Django 6.0.3 on 2026-04-04 19:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationAIContext',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('entity_type', models.CharField(choices=[('candidate_state', 'Candidate State'), ('job_state', 'Job State'), ('pipeline_stage', 'Pipeline Stage'), ('sla_risk', 'SLA Risk'), ('workload', 'Workload'), ('team_availability', 'Team Availability')], max_length=50)),
                ('entity_id', models.UUIDField()),
                ('context_data', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'automation_ai_contexts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AutomationAIDecision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('decision_type', models.CharField(choices=[('execute_workflow', 'Execute Workflow'), ('delay_execution', 'Delay Execution'), ('escalate', 'Escalate'), ('retry', 'Retry'), ('fallback', 'Fallback'), ('create_automation', 'Create Automation'), ('pause_automation', 'Pause Automation')], max_length=50)),
                ('decision_reason', models.TextField()),
                ('decision_confidence', models.FloatField(default=0.0)),
                ('decision_output', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'automation_ai_decisions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AutomationAIReasoning',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('reasoning_type', models.CharField(choices=[('predictive', 'Predictive'), ('contextual', 'Contextual'), ('behavioral', 'Behavioral'), ('optimization', 'Optimization')], max_length=50)),
                ('reasoning_data', models.JSONField(blank=True, default=dict)),
                ('confidence_score', models.FloatField(default=0.0)),
            ],
            options={
                'db_table': 'automation_ai_reasoning',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AutomationAIRecommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('recommendation_type', models.CharField(choices=[('create_workflow', 'Create Workflow'), ('optimize_workflow', 'Optimize Workflow'), ('remove_workflow', 'Remove Workflow'), ('change_priority', 'Change Priority'), ('adjust_sla', 'Adjust SLA')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('expected_impact', models.TextField(blank=True)),
                ('confidence_score', models.FloatField(default=0.0)),
            ],
            options={
                'db_table': 'automation_ai_recommendations',
                'ordering': ['-created_at'],
            },
        ),
    ]
