# Generated by Django 6.0.3 on 2026-04-04 11:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowSLAPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('module_scope', models.CharField(choices=[('candidates', 'Candidates'), ('jobs', 'Jobs'), ('pipeline', 'Pipeline'), ('interviews', 'Interviews'), ('offers', 'Offers'), ('agencies', 'Agencies'), ('tasks', 'Tasks'), ('cross_module', 'Cross Module')], max_length=30)),
                ('trigger_event', models.CharField(db_index=True, max_length=128)),
                ('entity_type', models.CharField(max_length=64)),
                ('deadline_minutes', models.PositiveIntegerField()),
                ('warning_before_minutes', models.PositiveIntegerField(default=60)),
                ('escalation_after_minutes', models.PositiveIntegerField(default=120)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Workflow SLA Policy',
                'ordering': ['-priority', '-created_at'],
                'indexes': [models.Index(fields=['tenant_id', 'is_active'], name='automation__tenant__547b1e_idx'), models.Index(fields=['tenant_id', 'trigger_event'], name='automation__tenant__34dd3c_idx')],
            },
        ),
        migrations.CreateModel(
            name='WorkflowSLAExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('workflow_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('entity_type', models.CharField(db_index=True, max_length=64)),
                ('entity_id', models.CharField(db_index=True, max_length=64)),
                ('owner_user_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('current_status', models.CharField(choices=[('active', 'Active'), ('warning_due', 'Warning Due'), ('breached', 'Breached'), ('escalated', 'Escalated'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='active', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('due_at', models.DateTimeField(db_index=True)),
                ('warning_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('breached_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('escalation_level', models.PositiveSmallIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sla_policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='automation_sla.workflowslapolicy')),
            ],
            options={
                'verbose_name': 'Workflow SLA Execution',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowSLAEscalationRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('escalation_level', models.PositiveSmallIntegerField(default=1)),
                ('escalate_after_minutes', models.PositiveIntegerField()),
                ('target_role', models.CharField(blank=True, max_length=50)),
                ('target_user_id', models.UUIDField(blank=True, null=True)),
                ('notification_template_id', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sla_policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalation_rules', to='automation_sla.workflowslapolicy')),
            ],
            options={
                'verbose_name': 'Workflow SLA Escalation Rule',
                'ordering': ['sla_policy', 'escalation_level'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowSLABreachInsight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('workflow_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('insight_type', models.CharField(choices=[('repeated_breach', 'Repeated Breach'), ('high_delay_team', 'High Delay Team'), ('slow_stage_transition', 'Slow Stage Transition'), ('agency_response_delay', 'Agency Response Delay'), ('interview_feedback_delay', 'Interview Feedback Delay'), ('offer_response_delay', 'Offer Response Delay')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('breach_count', models.PositiveIntegerField(default=0)),
                ('impacted_module', models.CharField(choices=[('candidates', 'Candidates'), ('jobs', 'Jobs'), ('pipeline', 'Pipeline'), ('interviews', 'Interviews'), ('offers', 'Offers'), ('agencies', 'Agencies'), ('tasks', 'Tasks'), ('cross_module', 'Cross Module')], max_length=30)),
                ('suggested_fix', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved'), ('ignored', 'Ignored')], db_index=True, default='new', max_length=20)),
                ('sla_policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='breach_insights', to='automation_sla.workflowslapolicy')),
            ],
            options={
                'verbose_name': 'Workflow SLA Breach Insight',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowSLAReminder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('reminder_type', models.CharField(choices=[('warning', 'Warning'), ('breach', 'Breach'), ('escalation', 'Escalation'), ('final_notice', 'Final Notice')], max_length=20)),
                ('recipient_type', models.CharField(max_length=50)),
                ('channel', models.CharField(default='in_app', max_length=20)),
                ('scheduled_at', models.DateTimeField(db_index=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped'), ('cancelled', 'Cancelled')], db_index=True, default='scheduled', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sla_execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='automation_sla.workflowslaexecution')),
            ],
            options={
                'verbose_name': 'Workflow SLA Reminder',
                'ordering': ['scheduled_at'],
            },
        ),
        migrations.AddIndex(
            model_name='workflowslaexecution',
            index=models.Index(fields=['tenant_id', 'current_status'], name='automation__tenant__c4cefe_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowslaexecution',
            index=models.Index(fields=['tenant_id', 'due_at'], name='automation__tenant__e2defb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='workflowslaescalationrule',
            unique_together={('sla_policy', 'escalation_level')},
        ),
    ]
