from django.urls import path

from apps.module_registry import views


urlpatterns = [
    path('modules/', views.ModuleRegistryListCreateView.as_view(), name='module-registry-list-create'),
    path('modules/<uuid:module_id>/', views.ModuleRegistryDetailView.as_view(), name='module-registry-detail'),
    path('modules/<uuid:module_id>/status/', views.ModuleStatusUpdateView.as_view(), name='module-registry-status'),
    path('modules/<uuid:module_id>/dependencies/', views.ModuleDependencyCreateView.as_view(), name='module-registry-dependency-create'),
    path('modules/<uuid:module_id>/blockers/', views.ModuleBlockerCreateView.as_view(), name='module-registry-blocker-create'),
    path('modules/<uuid:module_id>/owners/', views.ModuleOwnerCreateView.as_view(), name='module-registry-owner-create'),
    path('planning/scan/', views.RemainingModuleMapScanView.as_view(), name='remaining-module-scan'),
    path('planning/map/', views.RemainingModuleMapListView.as_view(), name='remaining-module-map'),
    path('planning/gaps/', views.ModuleGapListView.as_view(), name='remaining-module-gaps'),
    path('planning/partial/', views.PartiallyBuiltModuleListView.as_view(), name='remaining-module-partial'),
    path('planning/blocked/', views.BlockedModuleListView.as_view(), name='remaining-module-blocked'),
    path('planning/architecture-only/', views.ArchitectureOnlyModuleListView.as_view(), name='remaining-module-architecture-only'),
    path('planning/priority/', views.ModulePrioritySummaryView.as_view(), name='remaining-module-priority'),
    path('planning/recommended-next/', views.NextRecommendedModulesView.as_view(), name='remaining-module-next'),
    path('planning/mvp/', views.MVPModulesView.as_view(), name='remaining-module-mvp'),
    path('planning/enterprise-later/', views.EnterpriseLaterModulesView.as_view(), name='remaining-module-enterprise-later'),
    path('planning/sequence/', views.ModuleSequencePlanListCreateView.as_view(), name='remaining-module-sequence'),
    path('planning/dependency-chain/', views.ModuleDependencyChainListView.as_view(), name='remaining-module-dependency-chain'),
    path('planning/parallel-safe/', views.ParallelSafeModulesView.as_view(), name='remaining-module-parallel-safe'),
    path('planning/modules/<uuid:module_id>/continuation/', views.ModuleContinuationPlanUpdateView.as_view(), name='remaining-module-continuation'),
    path('selection/candidates/', views.CandidateModulePoolView.as_view(), name='next-module-candidate-pool'),
    path('selection/score/', views.ScoreModuleCandidatesView.as_view(), name='next-module-score'),
    path('selection/scoring-summary/', views.CandidateScoringSummaryView.as_view(), name='next-module-scoring-summary'),
    path('selection/rejected/', views.RejectedCandidatesView.as_view(), name='next-module-rejected'),
    path('selection/dependency-pressure/', views.DependencyPressureSummaryView.as_view(), name='next-module-dependency-pressure'),
    path('selection/readiness/', views.NextModuleReadinessSummaryView.as_view(), name='next-module-readiness'),
    path('selection/select/', views.SelectNextCriticalModuleView.as_view(), name='next-module-select'),
    path('selection/selected/', views.SelectedNextModuleView.as_view(), name='next-module-selected'),
    path('selection/why-selected/', views.WhySelectedView.as_view(), name='next-module-why-selected'),
    path('selection/why-not-others/', views.WhyNotOthersView.as_view(), name='next-module-why-not-others'),
    path('selection/lock/', views.LockNextModuleDecisionView.as_view(), name='next-module-lock'),
    path('selection/update/', views.UpdateNextModuleDecisionView.as_view(), name='next-module-update'),
    path('selection/immediate-order/', views.ImmediateImplementationOrderView.as_view(), name='next-module-immediate-order'),
    path('selection/backend-first/', views.BackendFirstRecommendationView.as_view(), name='next-module-backend-first'),
    path('selection/frontend-first/', views.FrontendFirstRecommendationView.as_view(), name='next-module-frontend-first'),
    path('selection/blocker-prerequisites/', views.BlockerPrerequisitesView.as_view(), name='next-module-blocker-prerequisites'),
    path('selection/follow-up-sequence/', views.FollowUpModuleSequenceView.as_view(), name='next-module-follow-up-sequence'),
    path('prompts/generate/', views.GenerateImplementationPromptView.as_view(), name='generated-prompt-generate'),
    path('prompts/current/', views.GeneratedPromptDetailView.as_view(), name='generated-prompt-current'),
    path('prompts/regenerate/', views.RegeneratePromptView.as_view(), name='generated-prompt-regenerate'),
    path('prompts/history/', views.PromptHistoryView.as_view(), name='generated-prompt-history'),
    path('prompts/approve/', views.ApprovePromptView.as_view(), name='generated-prompt-approve'),
    path('prompts/lock/', views.LockPromptView.as_view(), name='generated-prompt-lock'),
    path('prompts/context/selected-module/', views.PromptSelectedModuleContextView.as_view(), name='generated-prompt-selected-module'),
    path('prompts/context/dependencies/', views.PromptModuleDependenciesView.as_view(), name='generated-prompt-dependencies'),
    path('prompts/context/module/', views.PromptModuleContextView.as_view(), name='generated-prompt-module-context'),
    path('prompts/context/integration-mapping/', views.PromptIntegrationMappingView.as_view(), name='generated-prompt-integration-mapping'),
]
