# Generated by Django 6.0.3 on 2026-04-01 20:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestration_center', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AISuggestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('suggestion_key', models.CharField(db_index=True, max_length=64)),
                ('category', models.CharField(choices=[('followup_recommendation', 'Follow-up Recommendation'), ('escalation_recommendation', 'Escalation Recommendation'), ('review_recommendation', 'Review Recommendation'), ('assignment_recommendation', 'Assignment Recommendation'), ('communication_draft', 'Communication Draft'), ('risk_flag_recommendation', 'Risk Flag Recommendation'), ('deadline_recommendation', 'Deadline Recommendation'), ('insight_summary', 'Insight Summary')], db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending Review'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('converted', 'Converted'), ('expired', 'Expired'), ('superseded', 'Superseded'), ('failed', 'Failed')], db_index=True, default='draft', max_length=32)),
                ('source_event', models.CharField(blank=True, db_index=True, max_length=128)),
                ('source_module', models.CharField(db_index=True, max_length=64)),
                ('source_entity_type', models.CharField(db_index=True, max_length=64)),
                ('source_entity_id', models.CharField(db_index=True, max_length=64)),
                ('owner_module', models.CharField(blank=True, db_index=True, max_length=64)),
                ('proposed_action_family', models.CharField(blank=True, db_index=True, max_length=64)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True)),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('confidence_band', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], db_index=True, default='medium', max_length=16)),
                ('payload_json', models.JSONField(blank=True, default=dict)),
                ('rationale_json', models.JSONField(blank=True, default=dict)),
                ('audit_metadata_json', models.JSONField(blank=True, default=dict)),
                ('requires_approval', models.BooleanField(default=False)),
                ('manual_override_allowed', models.BooleanField(default=True)),
                ('review_comment', models.TextField(blank=True)),
                ('approval_comment', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, max_length=255)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('converted_artifact_type', models.CharField(blank=True, max_length=64)),
                ('converted_artifact_id', models.UUIDField(blank=True, null=True)),
                ('reviewed_by_id', models.UUIDField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by_id', models.UUIDField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_by_id', models.UUIDField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('converted_by_id', models.UUIDField(blank=True, null=True)),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
                ('ai_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='suggestions', to='orchestration_center.aiexecutionrequest')),
                ('approval_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggestions', to='orchestration_center.approvalqueueitem')),
                ('superseded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_suggestions', to='orchestration_center.aisuggestion')),
            ],
            options={
                'db_table': 'icc_ai_suggestions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AISuggestionConversion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('conversion_type', models.CharField(db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('converted', 'Converted'), ('failed', 'Failed')], db_index=True, default='pending', max_length=32)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, max_length=255)),
                ('requested_by_id', models.UUIDField(blank=True, null=True)),
                ('requested_action_payload_json', models.JSONField(blank=True, default=dict)),
                ('result_payload_json', models.JSONField(blank=True, default=dict)),
                ('error_category', models.CharField(blank=True, db_index=True, max_length=64)),
                ('error_message', models.TextField(blank=True)),
                ('retry_safe', models.BooleanField(db_index=True, default=True)),
                ('approval_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggestion_conversions', to='orchestration_center.approvalqueueitem')),
                ('suggestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversions', to='orchestration_center.aisuggestion')),
            ],
            options={
                'db_table': 'icc_ai_suggestion_conversions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='aisuggestion',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('idempotency_key',), name='uniq_icc_ai_suggestion_idempotency_key'),
        ),
        migrations.AddConstraint(
            model_name='aisuggestionconversion',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('idempotency_key',), name='uniq_icc_ai_suggestion_conversion_idempotency_key'),
        ),
    ]
