# Generated by Django 6.0.3 on 2026-04-02 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestration_center', '0002_aisuggestion_aisuggestionconversion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aisuggestion',
            name='applied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aisuggestion',
            name='applied_by_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aisuggestion',
            name='apply_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='aisuggestion',
            name='dismissal_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='aisuggestion',
            name='dismissed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aisuggestion',
            name='dismissed_by_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aisuggestion',
            name='last_apply_error_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='aisuggestion',
            name='last_apply_result_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='aisuggestion',
            name='last_apply_status',
            field=models.CharField(blank=True, db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='aisuggestion',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('pending_review', 'Pending Review'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('dismissed', 'Dismissed'), ('applied', 'Applied'), ('converted', 'Converted'), ('expired', 'Expired'), ('superseded', 'Superseded'), ('failed', 'Failed')], db_index=True, default='pending', max_length=32),
        ),
    ]
