# Generated by Django 6.0.3 on 2026-04-02

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestration_center', '0003_aisuggestion_applied_at_aisuggestion_applied_by_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationIntelligencePolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('suggestion_type', models.CharField(choices=[('followup_recommendation', 'Follow-up Recommendation'), ('escalation_recommendation', 'Escalation Recommendation'), ('review_recommendation', 'Review Recommendation'), ('assignment_recommendation', 'Assignment Recommendation'), ('communication_draft', 'Communication Draft'), ('risk_flag_recommendation', 'Risk Flag Recommendation'), ('deadline_recommendation', 'Deadline Recommendation'), ('insight_summary', 'Insight Summary')], db_index=True, max_length=64)),
                ('module_scope', models.CharField(blank=True, db_index=True, max_length=64)),
                ('confidence_threshold', models.DecimalField(decimal_places=2, default=0.85, max_digits=5)),
                ('auto_approve', models.BooleanField(default=False)),
                ('auto_apply', models.BooleanField(default=False)),
                ('approval_required', models.BooleanField(default=True)),
                ('is_enabled', models.BooleanField(db_index=True, default=True)),
                ('priority_order', models.PositiveIntegerField(default=100)),
                ('notes', models.TextField(blank=True)),
                ('last_triggered_at', models.DateTimeField(blank=True, null=True)),
                ('last_triggered_suggestion_id', models.UUIDField(blank=True, null=True)),
                ('last_outcome', models.CharField(blank=True, db_index=True, max_length=64)),
            ],
            options={
                'db_table': 'icc_automation_intelligence_policies',
                'ordering': ['priority_order', '-confidence_threshold', 'suggestion_type', 'module_scope'],
                'constraints': [models.UniqueConstraint(fields=('tenant_id', 'suggestion_type', 'module_scope'), name='uniq_icc_automation_intelligence_policy_scope')],
            },
        ),
        migrations.AlterField(
            model_name='aisuggestion',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('pending_review', 'Pending Review'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('dismissed', 'Dismissed'), ('applied', 'Applied'), ('apply_failed', 'Apply Failed'), ('converted', 'Converted'), ('expired', 'Expired'), ('superseded', 'Superseded'), ('failed', 'Failed')], db_index=True, default='pending', max_length=32),
        ),
    ]
