# Generated by Django 6.0.3 on 2026-04-03 16:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestration_center', '0005_automationtemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationLearningSignal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('automation_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('suggestion_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('policy_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('outcome_type', models.CharField(choices=[('success', 'Success'), ('failure', 'Failure'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('dismissed', 'Dismissed'), ('applied', 'Applied'), ('overridden', 'Overridden')], db_index=True, max_length=32)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('execution_time_ms', models.IntegerField(blank=True, null=True)),
                ('user_action', models.CharField(blank=True, max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'icc_automation_learning_signals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='aisuggestion',
            name='category',
            field=models.CharField(choices=[('followup_recommendation', 'Follow-up Recommendation'), ('escalation_recommendation', 'Escalation Recommendation'), ('review_recommendation', 'Review Recommendation'), ('assignment_recommendation', 'Assignment Recommendation'), ('communication_draft', 'Communication Draft'), ('risk_flag_recommendation', 'Risk Flag Recommendation'), ('deadline_recommendation', 'Deadline Recommendation'), ('insight_summary', 'Insight Summary'), ('policy_improvement', 'Policy Improvement'), ('automation_recommendation', 'Automation Recommendation')], db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='automationintelligencepolicy',
            name='suggestion_type',
            field=models.CharField(choices=[('followup_recommendation', 'Follow-up Recommendation'), ('escalation_recommendation', 'Escalation Recommendation'), ('review_recommendation', 'Review Recommendation'), ('assignment_recommendation', 'Assignment Recommendation'), ('communication_draft', 'Communication Draft'), ('risk_flag_recommendation', 'Risk Flag Recommendation'), ('deadline_recommendation', 'Deadline Recommendation'), ('insight_summary', 'Insight Summary'), ('policy_improvement', 'Policy Improvement'), ('automation_recommendation', 'Automation Recommendation')], db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='automationtemplate',
            name='suggestion_type',
            field=models.CharField(choices=[('followup_recommendation', 'Follow-up Recommendation'), ('escalation_recommendation', 'Escalation Recommendation'), ('review_recommendation', 'Review Recommendation'), ('assignment_recommendation', 'Assignment Recommendation'), ('communication_draft', 'Communication Draft'), ('risk_flag_recommendation', 'Risk Flag Recommendation'), ('deadline_recommendation', 'Deadline Recommendation'), ('insight_summary', 'Insight Summary'), ('policy_improvement', 'Policy Improvement'), ('automation_recommendation', 'Automation Recommendation')], db_index=True, max_length=64),
        ),
    ]
