# Generated by Django 6.0.3 on 2026-04-03 16:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestration_center', '0006_automationlearningsignal_alter_aisuggestion_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIGovernanceApproval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('request_type', models.CharField(db_index=True, max_length=64)),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('requested_by', models.UUIDField(db_index=True)),
                ('approval_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=32)),
                ('approved_by', models.UUIDField(blank=True, null=True)),
                ('rejected_by', models.UUIDField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'icc_ai_governance_approvals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIGovernanceRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('rule_name', models.CharField(max_length=255)),
                ('rule_type', models.CharField(choices=[('suggestion_apply', 'Suggestion Apply'), ('automation_execute', 'Automation Execute'), ('policy_change', 'Policy Change'), ('prompt_change', 'Prompt Change'), ('execution_retry', 'Execution Retry')], db_index=True, max_length=64)),
                ('requires_approval', models.BooleanField(default=True)),
                ('auto_apply_allowed', models.BooleanField(default=False)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='medium', max_length=32)),
            ],
            options={
                'db_table': 'icc_ai_governance_rules',
            },
        ),
    ]
