# Generated by Django 6.0.3 on 2026-04-03 19:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestration_center', '0011_workflow_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workflow',
            options={'ordering': ['-priority', '-created_at']},
        ),
        migrations.AddField(
            model_name='workflow',
            name='current_version',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='workflow',
            name='dry_run_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workflow',
            name='is_critical',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workflow',
            name='priority',
            field=models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], db_index=True, default='medium', max_length=16),
        ),
        migrations.AddField(
            model_name='workflow',
            name='require_approval',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workflowexecution',
            name='execution_trace',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='workflowexecution',
            name='is_dry_run',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workflowexecutionlog',
            name='state_after',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workflowexecutionlog',
            name='state_before',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workflowexecution',
            name='status',
            field=models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('paused', 'Paused'), ('rolled_back', 'Rolled Back')], db_index=True, default='running', max_length=32),
        ),
        migrations.CreateModel(
            name='WorkflowAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('action', models.CharField(choices=[('created', 'Created'), ('edited', 'Edited'), ('version_created', 'Version Created'), ('activated', 'Activated'), ('paused', 'Paused'), ('archived', 'Archived'), ('executed', 'Executed'), ('failed', 'Failed'), ('rollback', 'Rollback'), ('limit_exceeded', 'Limit Exceeded'), ('approval_requested', 'Approval Requested'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, max_length=64)),
                ('performed_by', models.UUIDField(blank=True, null=True)),
                ('version_number', models.IntegerField(blank=True, null=True)),
                ('execution_id', models.UUIDField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='orchestration_center.workflow')),
            ],
            options={
                'db_table': 'icc_workflow_audit_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowRollbackLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('rollback_time', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.UUIDField()),
                ('status', models.CharField(default='completed', max_length=32)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('execution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rollback_log', to='orchestration_center.workflowexecution')),
            ],
            options={
                'db_table': 'icc_workflow_rollback_logs',
            },
        ),
        migrations.CreateModel(
            name='WorkflowSafetyRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('max_executions_per_hour', models.IntegerField(default=100)),
                ('max_executions_per_day', models.IntegerField(default=1000)),
                ('require_confirmation', models.BooleanField(default=False)),
                ('alert_threshold_percentage', models.IntegerField(default=80)),
                ('is_paused_by_system', models.BooleanField(default=False)),
                ('last_violation_at', models.DateTimeField(blank=True, null=True)),
                ('workflow', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='safety_rule', to='orchestration_center.workflow')),
            ],
            options={
                'db_table': 'icc_workflow_safety_rules',
            },
        ),
        migrations.CreateModel(
            name='WorkflowVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('version_number', models.IntegerField()),
                ('config_snapshot', models.JSONField()),
                ('change_summary', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=False)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='orchestration_center.workflow')),
            ],
            options={
                'db_table': 'icc_workflow_versions',
                'ordering': ['-version_number'],
                'unique_together': {('workflow', 'version_number')},
            },
        ),
        migrations.CreateModel(
            name='WorkflowApproval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('requested_by', models.UUIDField(db_index=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=32)),
                ('approved_by', models.UUIDField(blank=True, null=True)),
                ('comment', models.TextField(blank=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='orchestration_center.workflow')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests', to='orchestration_center.workflowversion')),
            ],
            options={
                'db_table': 'icc_workflow_approvals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='workflowexecution',
            name='version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orchestration_center.workflowversion'),
        ),
    ]
