# Generated by Django 6.0.3 on 2026-04-03 19:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestration_center', '0012_alter_workflow_options_workflow_current_version_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationInsight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('insight_type', models.CharField(db_index=True, max_length=64)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('suggested_action', models.JSONField(blank=True, default=dict)),
                ('confidence_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('status', models.CharField(choices=[('new', 'New'), ('accepted', 'Accepted'), ('dismissed', 'Dismissed')], db_index=True, default='new', max_length=32)),
            ],
            options={
                'db_table': 'icc_automation_insights',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AutomationRecommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('recommendation_type', models.CharField(db_index=True, max_length=64)),
                ('reason', models.TextField(blank=True)),
                ('confidence_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('workflow_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendations', to='orchestration_center.workflowtemplate')),
            ],
            options={
                'db_table': 'icc_automation_recommendations',
                'ordering': ['-created_at'],
            },
        ),
    ]
