# Generated by Django 6.0.3 on 2026-04-03 20:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestration_center', '0013_automationinsight_automationrecommendation'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowFailureInsight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('failure_type', models.CharField(db_index=True, max_length=128)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('suggested_fix', models.TextField(blank=True)),
                ('occurrence_count', models.IntegerField(default=0)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved'), ('ignored', 'Ignored')], db_index=True, default='new', max_length=32)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='failure_insights', to='orchestration_center.workflow')),
            ],
            options={
                'db_table': 'icc_workflow_failure_insights',
                'ordering': ['-last_seen_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowActionMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('action_type', models.CharField(db_index=True, max_length=64)),
                ('action_count', models.IntegerField(default=0)),
                ('success_count', models.IntegerField(default=0)),
                ('failure_count', models.IntegerField(default=0)),
                ('avg_action_time_ms', models.FloatField(default=0.0)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_metrics', to='orchestration_center.workflow')),
            ],
            options={
                'db_table': 'icc_workflow_action_metrics',
                'unique_together': {('tenant_id', 'workflow', 'action_type')},
            },
        ),
        migrations.CreateModel(
            name='WorkflowAnalyticsSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('snapshot_date', models.DateField(db_index=True)),
                ('execution_count', models.IntegerField(default=0)),
                ('success_count', models.IntegerField(default=0)),
                ('failure_count', models.IntegerField(default=0)),
                ('paused_count', models.IntegerField(default=0)),
                ('avg_execution_time_ms', models.FloatField(default=0.0)),
                ('avg_steps_per_execution', models.FloatField(default=0.0)),
                ('completion_rate', models.FloatField(default=0.0)),
                ('failure_rate', models.FloatField(default=0.0)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_snapshots', to='orchestration_center.workflow')),
            ],
            options={
                'db_table': 'icc_workflow_analytics_snapshots',
                'ordering': ['-snapshot_date'],
                'unique_together': {('tenant_id', 'workflow', 'snapshot_date')},
            },
        ),
        migrations.CreateModel(
            name='WorkflowImpactMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('impact_type', models.CharField(choices=[('hours_saved', 'Hours Saved'), ('reminders_sent', 'Reminders Sent'), ('escalations_prevented', 'Escalations Prevented'), ('stage_movements_automated', 'Stage Movements Automated'), ('interviews_auto_scheduled', 'Interviews Auto-Scheduled'), ('offers_auto_triggered', 'Offers Auto-Triggered')], db_index=True, max_length=64)),
                ('metric_value', models.FloatField(default=0.0)),
                ('metric_unit', models.CharField(blank=True, max_length=32)),
                ('calculation_context', models.JSONField(blank=True, default=dict)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impact_metrics', to='orchestration_center.workflow')),
            ],
            options={
                'db_table': 'icc_workflow_impact_metrics',
                'unique_together': {('tenant_id', 'workflow', 'impact_type')},
            },
        ),
        migrations.CreateModel(
            name='WorkflowTriggerMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('trigger_event', models.CharField(db_index=True, max_length=128)),
                ('trigger_count', models.IntegerField(default=0)),
                ('execution_started_count', models.IntegerField(default=0)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trigger_metrics', to='orchestration_center.workflow')),
            ],
            options={
                'db_table': 'icc_workflow_trigger_metrics',
                'unique_together': {('tenant_id', 'workflow', 'trigger_event')},
            },
        ),
    ]
