# Generated by Django 6.0.3 on 2026-04-04 10:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestration_center', '0014_workflowfailureinsight_workflowactionmetric_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationGovernanceAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('action', models.CharField(choices=[('policy_change', 'Policy Change'), ('auto_apply', 'Auto Apply'), ('manual_override', 'Manual Override'), ('execution_failure', 'Execution Failure'), ('kill_switch_toggled', 'Kill Switch Toggled'), ('limit_exceeded', 'Limit Exceeded')], db_index=True, max_length=64)),
                ('performed_by', models.UUIDField(blank=True, null=True)),
                ('target_id', models.UUIDField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'icc_automation_governance_audits',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AutomationUsageLimit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('tenant_id', models.UUIDField(db_index=True, unique=True)),
                ('daily_limit', models.IntegerField(default=1000)),
                ('hourly_limit', models.IntegerField(default=100)),
                ('max_auto_apply', models.IntegerField(default=500)),
                ('max_failures', models.IntegerField(default=50)),
            ],
            options={
                'db_table': 'icc_automation_usage_limits',
            },
        ),
        migrations.AlterModelOptions(
            name='automationtemplate',
            options={'ordering': ['-is_system_template', 'name']},
        ),
        migrations.RenameField(
            model_name='automationtemplate',
            old_name='is_builtin',
            new_name='is_system_template',
        ),
        migrations.RenameField(
            model_name='automationtemplate',
            old_name='confidence_threshold',
            new_name='recommended_confidence_threshold',
        ),
        migrations.RemoveField(
            model_name='automationtemplate',
            name='automation_level',
        ),
        migrations.RemoveField(
            model_name='automationtemplate',
            name='module_scope',
        ),
        migrations.RemoveField(
            model_name='automationtemplate',
            name='suggestion_type',
        ),
        migrations.RemoveField(
            model_name='automationtemplate',
            name='tags',
        ),
        migrations.AddField(
            model_name='automationintelligencepolicy',
            name='auto_apply_allowed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='automationintelligencepolicy',
            name='origin_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_policies', to='orchestration_center.automationtemplate'),
        ),
        migrations.AddField(
            model_name='automationintelligencepolicy',
            name='risk_level',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='low', max_length=32),
        ),
        migrations.AddField(
            model_name='automationlearningsignal',
            name='failure_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='automationlearningsignal',
            name='override_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='automationlearningsignal',
            name='recommendation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='automationlearningsignal',
            name='success_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='automationlearningsignal',
            name='suggestion_type',
            field=models.CharField(blank=True, db_index=True, default='general', max_length=64),
        ),
        migrations.AddField(
            model_name='automationtemplate',
            name='action_set',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='automationtemplate',
            name='category',
            field=models.CharField(choices=[('candidate_followup', 'Candidate Follow-up'), ('deadline_management', 'Deadline Management'), ('escalation', 'Escalation'), ('review_workflow', 'Review Workflow'), ('communication', 'Communication'), ('interview_followup', 'Interview Follow-up'), ('decision_support', 'Decision Support')], db_index=True, default='communication', max_length=64),
        ),
        migrations.AddField(
            model_name='automationtemplate',
            name='condition_set',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='automationtemplate',
            name='default_risk_level',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='low', max_length=32),
        ),
        migrations.AddField(
            model_name='automationtemplate',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='automationtemplate',
            name='template_key',
            field=models.CharField(db_index=True, default='manual_setup', max_length=64),
        ),
        migrations.AddField(
            model_name='automationtemplate',
            name='trigger_type',
            field=models.CharField(db_index=True, default='manual', max_length=64),
        ),
        migrations.AddField(
            model_name='tenantintelligencesettings',
            name='auto_apply_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='automationlibrarytemplate',
            name='category',
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='automationlibrarytemplate',
            name='risk_level',
            field=models.CharField(db_index=True, default='low', max_length=32),
        ),
        migrations.AlterField(
            model_name='automationlibrarytemplate',
            name='template_type',
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.CreateModel(
            name='AutomationOptimizationRecommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('recommendation_type', models.CharField(choices=[('increase_confidence_threshold', 'Increase Confidence Threshold'), ('decrease_confidence_threshold', 'Decrease Confidence Threshold'), ('enable_auto_approve', 'Enable Auto-Approve'), ('disable_auto_approve', 'Disable Auto-Approve'), ('enable_auto_apply', 'Enable Auto-Apply'), ('disable_auto_apply', 'Disable Auto-Apply'), ('change_risk_level', 'Change Risk Level')], max_length=64)),
                ('current_value', models.JSONField(blank=True, null=True)),
                ('recommended_value', models.JSONField(blank=True, null=True)),
                ('reason', models.TextField()),
                ('confidence', models.FloatField(default=0.0)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='optimization_recommendations', to='orchestration_center.automationintelligencepolicy')),
            ],
            options={
                'db_table': 'icc_automation_optimization_recommendations',
                'ordering': ['-created_at'],
            },
        ),
    ]
