# Generated by Django 6.0.3 on 2026-04-07 17:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestration_center', '0018_workfloweventdefinition_workfloweventlog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowProcessInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('workflow_id', models.UUIDField(db_index=True)),
                ('entity_type', models.CharField(db_index=True, max_length=64)),
                ('entity_id', models.UUIDField(db_index=True)),
                ('process_status', models.CharField(choices=[('running', 'Running'), ('waiting_human', 'Waiting Human'), ('waiting_approval', 'Waiting Approval'), ('waiting_schedule', 'Waiting Schedule'), ('waiting_candidate', 'Waiting Candidate'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='running', max_length=32)),
                ('current_stage', models.CharField(blank=True, max_length=128, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'workflow_process_instances',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowNegotiationCheckpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('offer_id', models.UUIDField(db_index=True)),
                ('negotiation_round', models.IntegerField(default=1)),
                ('proposed_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('allowed_band_min', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('allowed_band_max', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('within_band', 'Within Band'), ('approval_required', 'Approval Required'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('exhausted', 'Exhausted')], default='pending', max_length=32)),
                ('approved_by', models.UUIDField(blank=True, null=True)),
                ('process_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='negotiations', to='orchestration_center.workflowprocessinstance')),
            ],
            options={
                'db_table': 'workflow_negotiation_checkpoints',
            },
        ),
        migrations.CreateModel(
            name='WorkflowHandoffRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('handoff_type', models.CharField(choices=[('onboarding', 'Onboarding'), ('hrms', 'HRMS'), ('closure', 'Closure'), ('external_webhook', 'External Webhook')], max_length=32)),
                ('payload', models.JSONField(default=dict)),
                ('destination_system', models.CharField(blank=True, max_length=128)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('acknowledged', 'Acknowledged'), ('failed', 'Failed')], default='pending', max_length=32)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('process_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handoffs', to='orchestration_center.workflowprocessinstance')),
            ],
            options={
                'db_table': 'workflow_handoff_records',
            },
        ),
        migrations.CreateModel(
            name='WorkflowStageExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('stage_key', models.CharField(max_length=128)),
                ('stage_type', models.CharField(choices=[('process_stage', 'Process Stage'), ('interview_round', 'Interview Round'), ('approval_gate', 'Approval Gate'), ('wait_state', 'Wait State'), ('scheduler', 'Scheduler'), ('negotiation', 'Negotiation'), ('handoff', 'Handoff')], max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('waiting', 'Waiting'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=32)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('process_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='orchestration_center.workflowprocessinstance')),
            ],
            options={
                'db_table': 'workflow_stage_executions',
                'ordering': ['started_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowSchedulerCheckpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('scheduling_type', models.CharField(choices=[('interviewer', 'Interviewer'), ('panel', 'Panel'), ('personal_interview', 'Personal Interview'), ('manager_meeting', 'Manager Meeting')], max_length=32)),
                ('target_user_ids', models.JSONField(default=list)),
                ('target_mode', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('hybrid', 'Hybrid')], default='online', max_length=32)),
                ('availability_payload', models.JSONField(blank=True, default=dict)),
                ('selected_slot', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('availability_checked', 'Availability Checked'), ('slot_found', 'Slot Found'), ('booked', 'Booked'), ('failed', 'Failed'), ('reschedule_required', 'Reschedule Required')], default='pending', max_length=32)),
                ('process_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduling_checkpoints', to='orchestration_center.workflowprocessinstance')),
                ('stage_execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduling_checkpoints', to='orchestration_center.workflowstageexecution')),
            ],
            options={
                'db_table': 'workflow_scheduler_checkpoints',
            },
        ),
        migrations.CreateModel(
            name='WorkflowApprovalCheckpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('approval_type', models.CharField(max_length=128)),
                ('requested_from_user_id', models.UUIDField(db_index=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=32)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('process_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='orchestration_center.workflowprocessinstance')),
                ('stage_execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='orchestration_center.workflowstageexecution')),
            ],
            options={
                'db_table': 'workflow_approval_checkpoints',
            },
        ),
    ]
