# Generated by Django 6.0.3 on 2026-05-07 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0004_remove_department_head_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='primary_currency',
            field=models.CharField(default='INR', max_length=5),
        ),
        migrations.AddField(
            model_name='organisation',
            name='primary_language',
            field=models.CharField(default='en', max_length=10),
        ),
    ]
