# Generated by Django 6.0.3 on 2026-03-28 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automationrule',
            name='trigger_event',
            field=models.CharField(choices=[('application.submitted', 'Application Submitted'), ('application.stage_changed', 'Application Stage Changed'), ('application.shortlisted', 'Application Shortlisted'), ('interview.completed', 'Interview Completed'), ('offer.sent', 'Offer Sent'), ('deadline.overdue', 'Deadline Overdue'), ('agency.submitted', 'Agency Submitted'), ('job.approved', 'Job Approved'), ('candidate.applied', 'Candidate Applied'), ('prequalification.completed', 'Prequalification Completed'), ('interview.scheduled', 'Interview Scheduled'), ('feedback.submitted', 'Feedback Submitted'), ('decision.made', 'Decision Made'), ('candidate.no_show', 'Candidate No Show'), ('interview.cancelled', 'Interview Cancelled')], max_length=100),
        ),
    ]
