# Generated by Django 6.0.3 on 2026-04-04 13:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowSandboxScenario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('module_scope', models.CharField(db_index=True, max_length=64)),
                ('trigger_event', models.CharField(db_index=True, max_length=128)),
                ('scenario_payload', models.JSONField(default=dict)),
                ('expected_path', models.JSONField(blank=True, default=list)),
                ('expected_actions', models.JSONField(blank=True, default=list)),
                ('is_system_scenario', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'verbose_name': 'Workflow Sandbox Scenario',
                'ordering': ['-is_system_scenario', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowSandboxRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('workflow_id', models.UUIDField(db_index=True)),
                ('version_id', models.UUIDField(blank=True, null=True)),
                ('run_name', models.CharField(max_length=255)),
                ('trigger_event', models.CharField(max_length=128)),
                ('input_context', models.JSONField(blank=True, default=dict)),
                ('expected_outcome', models.JSONField(blank=True, default=dict)),
                ('actual_outcome', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='queued', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Workflow Sandbox Run',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant_id', 'status'], name='automation__tenant__a81a23_idx'), models.Index(fields=['tenant_id', 'workflow_id'], name='automation__tenant__f5961f_idx')],
            },
        ),
        migrations.CreateModel(
            name='WorkflowSandboxArtifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('artifact_type', models.CharField(choices=[('simulated_notification', 'Simulated Notification'), ('simulated_task', 'Simulated Task'), ('simulated_sla', 'Simulated SLA'), ('simulated_stage_change', 'Simulated Stage Change'), ('simulated_escalation', 'Simulated Escalation'), ('simulated_offer', 'Simulated Offer'), ('simulated_dependency_trace', 'Simulated Dependency Trace')], max_length=50)),
                ('artifact_name', models.CharField(max_length=255)),
                ('artifact_payload', models.JSONField(default=dict)),
                ('sandbox_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='automation_sandbox.workflowsandboxrun')),
            ],
            options={
                'verbose_name': 'Workflow Sandbox Artifact',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowSandboxApproval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('workflow_id', models.UUIDField(db_index=True)),
                ('approval_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('reviewed_by', models.UUIDField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('sandbox_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='automation_sandbox.workflowsandboxrun')),
            ],
            options={
                'verbose_name': 'Workflow Sandbox Approval',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowSandboxStepLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('node_id', models.UUIDField(db_index=True)),
                ('step_order', models.PositiveIntegerField()),
                ('action_type', models.CharField(max_length=64)),
                ('simulated_input', models.JSONField(blank=True, default=dict)),
                ('simulated_output', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('skipped', 'Skipped'), ('simulated', 'Simulated'), ('warning', 'Warning')], max_length=20)),
                ('duration_ms', models.IntegerField(default=0)),
                ('warning_message', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('sandbox_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='automation_sandbox.workflowsandboxrun')),
            ],
            options={
                'verbose_name': 'Workflow Sandbox Step Log',
                'ordering': ['sandbox_run', 'step_order'],
            },
        ),
    ]
