# Generated by Django 6.0.3 on 2026-03-25 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrequisition',
            name='auto_followup_after_source',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='auto_match_candidates',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='auto_nurture_unqualified_candidates',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='auto_push_to_recruiter_queue',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='override_workflow_mode',
            field=models.CharField(blank=True, choices=[('manual', 'Manual'), ('semi_automated', 'Semi Automated'), ('fully_automated', 'Fully Automated')], max_length=30),
        ),
    ]
