# Generated by Django 6.0.3 on 2026-04-01 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_jobrequisition_job_ref_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrequisition',
            name='hiring_manager_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='job_category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='recruiter_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
