# Generated by Django 6.0.3 on 2026-04-01 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_jobrequisition_backup_recruiter_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrequisition',
            name='agency_submission_governance',
            field=models.CharField(choices=[('direct', 'Direct Submission'), ('approval_required', 'Approval Required'), ('draft_only', 'Draft Submission')], default='direct', max_length=30),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='is_published_to_agencies',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='sourcing_mode',
            field=models.CharField(choices=[('internal_only', 'Internal Only'), ('external_only', 'External Only'), ('hybrid', 'Hybrid')], default='internal_only', max_length=30),
        ),
    ]
