# Generated by Django 6.0.3 on 2026-04-01 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_jobstage_is_critical_path_jobstage_is_mandatory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrequisition',
            name='agency_distribution_policy',
            field=models.CharField(choices=[('all', 'All Preferred Agencies'), ('performance_ranked', 'Performance Ranked'), ('manual', 'Manual')], default='manual', max_length=50),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='auto_assign_recruiter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='auto_distribute_to_agencies',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='auto_schedule_interviews',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='recruiter_assignment_policy',
            field=models.CharField(choices=[('round_robin', 'Round Robin'), ('workload_balanced', 'Workload Balanced'), ('performance_based', 'Performance Based'), ('manual', 'Manual')], default='manual', max_length=50),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='sla_automation_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
