# Generated by Django 6.0.3 on 2026-04-05 12:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0014_jobrequisition_prequal_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='jobdescriptiontemplate',
            new_name='jobs_jd_tem_tenant__db8d0f_idx',
            old_name='jobs_jdt_tenant_active_idx',
        ),
        migrations.RenameIndex(
            model_name='jobdescriptiontemplate',
            new_name='jobs_jd_tem_tenant__93a125_idx',
            old_name='jobs_jdt_tenant_category_idx',
        ),
        migrations.RenameIndex(
            model_name='joblocation',
            new_name='jobs_locati_tenant__79bbe4_idx',
            old_name='jobs_loc_tenant_req_idx',
        ),
        migrations.AlterField(
            model_name='jobdescriptiontemplate',
            name='category',
            field=models.CharField(choices=[('engineering', 'Engineering'), ('product', 'Product'), ('design', 'Design'), ('sales', 'Sales'), ('marketing', 'Marketing'), ('operations', 'Operations'), ('finance', 'Finance'), ('hr', 'HR'), ('legal', 'Legal'), ('other', 'Other')], db_index=True, default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='jobdescriptiontemplate',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='jobdescriptiontemplate',
            name='job_type',
            field=models.CharField(blank=True, choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract'), ('internship', 'Internship'), ('freelance', 'Freelance')], max_length=50),
        ),
        migrations.AlterField(
            model_name='joblocation',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='jobrequisition',
            name='prequal_threshold_override',
            field=models.IntegerField(blank=True, help_text="Override the form's default pass threshold (0-100). Null = use form default.", null=True),
        ),
    ]
