# Generated by Django 6.0.3 on 2026-04-07 18:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency_workflows', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyWorkflowEventDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('event_key', models.CharField(db_index=True, max_length=128, unique=True)),
                ('event_name', models.CharField(max_length=255)),
                ('module_scope', models.CharField(db_index=True, max_length=64)),
                ('description', models.TextField(blank=True)),
                ('payload_schema', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'agency_workflow_event_definitions',
                'ordering': ['event_name'],
            },
        ),
        migrations.CreateModel(
            name='AgencyWorkflowEventLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('event_key', models.CharField(db_index=True, max_length=128)),
                ('entity_type', models.CharField(db_index=True, max_length=64)),
                ('entity_id', models.UUIDField(db_index=True)),
                ('related_candidate_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('related_client_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('related_job_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('payload', models.JSONField(default=dict)),
                ('source_module', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('emitted', 'Emitted'), ('consumed', 'Consumed'), ('failed', 'Failed'), ('ignored', 'Ignored')], default='emitted', max_length=16)),
            ],
            options={
                'db_table': 'agency_workflow_event_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgencyWorkflowEventDebugTrace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('decision', models.CharField(choices=[('matched', 'Matched'), ('filtered_out', 'Filtered Out'), ('blocked', 'Blocked'), ('executed', 'Executed'), ('failed', 'Failed')], max_length=16)),
                ('reason', models.TextField(blank=True)),
                ('trace_payload', models.JSONField(blank=True, default=dict)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_traces', to='agency_workflows.agencyworkflowdefinition')),
                ('event_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traces', to='agency_workflows.agencyworkfloweventlog')),
            ],
            options={
                'db_table': 'agency_workflow_event_debug_traces',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgencyWorkflowEventSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('trigger_filters', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('event_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='agency_workflows.agencyworkfloweventdefinition')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_subscriptions', to='agency_workflows.agencyworkflowdefinition')),
            ],
            options={
                'db_table': 'agency_workflow_event_subscriptions',
            },
        ),
    ]
