# Generated by Django 6.0.3 on 2026-04-07 18:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency_workflows', '0003_alter_agencyworkfloweventdebugtrace_event_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyWorkflowProcessInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('entity_type', models.CharField(db_index=True, max_length=64)),
                ('entity_id', models.UUIDField(db_index=True)),
                ('candidate_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('client_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('job_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('assigned_recruiter_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('process_status', models.CharField(choices=[('running', 'Running'), ('waiting_internal', 'Waiting Internal'), ('waiting_client', 'Waiting Client'), ('waiting_candidate', 'Waiting Candidate'), ('waiting_interview', 'Waiting Interview'), ('waiting_offer', 'Waiting Offer'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='running', max_length=32)),
                ('current_stage', models.CharField(blank=True, max_length=128, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_instances', to='agency_workflows.agencyworkflowdefinition')),
            ],
            options={
                'db_table': 'agency_workflow_process_instances',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='AgencyPlacementGuaranteeRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('candidate_id', models.UUIDField(db_index=True)),
                ('client_id', models.UUIDField(db_index=True)),
                ('job_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('placement_status', models.CharField(choices=[('joining_pending', 'Joining Pending'), ('joined', 'Joined'), ('dropped', 'Dropped'), ('closed', 'Closed')], default='joining_pending', max_length=32)),
                ('joined_at', models.DateTimeField(blank=True, null=True)),
                ('guarantee_start_date', models.DateField(blank=True, null=True)),
                ('guarantee_end_date', models.DateField(blank=True, null=True)),
                ('guarantee_status', models.CharField(choices=[('not_started', 'Not Started'), ('active', 'Active'), ('breached', 'Breached'), ('completed', 'Completed')], default='not_started', max_length=32)),
                ('process_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placement_guarantees', to='agency_workflows.agencyworkflowprocessinstance')),
            ],
            options={
                'db_table': 'agency_placement_guarantee_records',
            },
        ),
        migrations.CreateModel(
            name='AgencyOfferProgressCheckpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('candidate_id', models.UUIDField(db_index=True)),
                ('client_id', models.UUIDField(db_index=True)),
                ('job_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('offer_status', models.CharField(choices=[('pending', 'Pending'), ('received', 'Received'), ('discussing', 'Discussing'), ('countered', 'Countered'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=32)),
                ('proposed_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('accepted_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('negotiation_round', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('active', 'Active'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('exhausted', 'Exhausted'), ('closed', 'Closed')], default='active', max_length=32)),
                ('process_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_checkpoints', to='agency_workflows.agencyworkflowprocessinstance')),
            ],
            options={
                'db_table': 'agency_offer_progress_checkpoints',
            },
        ),
        migrations.CreateModel(
            name='AgencyWorkflowStageExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('stage_key', models.CharField(max_length=128)),
                ('stage_type', models.CharField(choices=[('talent_pool_stage', 'Talent Pool Stage'), ('recruiter_review', 'Recruiter Review'), ('internal_approval', 'Internal Approval'), ('submission_stage', 'Submission Stage'), ('client_wait', 'Client Wait'), ('interview_coordination', 'Interview Coordination'), ('offer_stage', 'Offer Stage'), ('placement_stage', 'Placement Stage'), ('guarantee_stage', 'Guarantee Stage'), ('closure_stage', 'Closure Stage')], max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('waiting', 'Waiting'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=32)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('process_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='agency_workflows.agencyworkflowprocessinstance')),
            ],
            options={
                'db_table': 'agency_workflow_stage_executions',
                'ordering': ['started_at'],
            },
        ),
        migrations.CreateModel(
            name='AgencyInternalApprovalCheckpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('approval_type', models.CharField(choices=[('recruiter_manager_review', 'Recruiter Manager Review'), ('submission_approval', 'Submission Approval'), ('salary_exception_approval', 'Salary Exception Approval'), ('client_escalation_approval', 'Client Escalation Approval')], max_length=64)),
                ('requested_from_user_id', models.UUIDField(db_index=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=32)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('process_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_approvals', to='agency_workflows.agencyworkflowprocessinstance')),
                ('stage_execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_approvals', to='agency_workflows.agencyworkflowstageexecution')),
            ],
            options={
                'db_table': 'agency_internal_approval_checkpoints',
            },
        ),
        migrations.CreateModel(
            name='AgencyClientResponseCheckpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('response_type', models.CharField(choices=[('submission_feedback', 'Submission Feedback'), ('shortlist_confirmation', 'Shortlist Confirmation'), ('interview_confirmation', 'Interview Confirmation'), ('offer_update', 'Offer Update'), ('joining_confirmation', 'Joining Confirmation')], max_length=64)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('last_followup_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reminded', 'Reminded'), ('overdue', 'Overdue'), ('escalated', 'Escalated'), ('responded', 'Responded'), ('expired', 'Expired')], default='pending', max_length=32)),
                ('process_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_responses', to='agency_workflows.agencyworkflowprocessinstance')),
                ('stage_execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_responses', to='agency_workflows.agencyworkflowstageexecution')),
            ],
            options={
                'db_table': 'agency_client_response_checkpoints',
            },
        ),
    ]
