# Generated by Django 6.0.3 on 2026-03-20 17:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyPerformanceScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('agency_tenant_id', models.UUIDField(db_index=True)),
                ('company_tenant_id', models.UUIDField(db_index=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('total_submissions', models.IntegerField(default=0)),
                ('shortlisted_count', models.IntegerField(default=0)),
                ('interviewed_count', models.IntegerField(default=0)),
                ('offered_count', models.IntegerField(default=0)),
                ('joined_count', models.IntegerField(default=0)),
                ('shortlist_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('offer_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('join_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('avg_submission_time_hours', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('overall_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
            options={
                'db_table': 'agencies_performance_score',
            },
        ),
        migrations.CreateModel(
            name='AgencyClientRelationship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('agency_tenant_id', models.UUIDField(db_index=True)),
                ('company_tenant_id', models.UUIDField(db_index=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('suspended', 'Suspended'), ('terminated', 'Terminated')], default='pending', max_length=50)),
                ('tier', models.CharField(choices=[('preferred', 'Preferred'), ('standard', 'Standard'), ('probation', 'Probation'), ('blacklisted', 'Blacklisted')], default='standard', max_length=50)),
                ('contract_start_date', models.DateField(blank=True, null=True)),
                ('contract_end_date', models.DateField(blank=True, null=True)),
                ('sla_submission_hours', models.IntegerField(default=48)),
                ('sla_feedback_hours', models.IntegerField(default=72)),
                ('commission_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('commission_type', models.CharField(blank=True, choices=[('percentage', 'Percentage'), ('fixed', 'Fixed'), ('milestone', 'Milestone')], max_length=50)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'agencies_client_relationship',
                'unique_together': {('agency_tenant_id', 'company_tenant_id')},
            },
        ),
        migrations.CreateModel(
            name='AgencyJobAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('requisition_id', models.UUIDField(db_index=True)),
                ('agency_tenant_id', models.UUIDField(db_index=True)),
                ('assigned_by', models.UUIDField(blank=True, null=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('max_submissions', models.IntegerField(blank=True, null=True)),
                ('submission_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('closed', 'Closed')], default='active', max_length=50)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'agencies_job_assignment',
                'unique_together': {('tenant_id', 'requisition_id', 'agency_tenant_id')},
            },
        ),
    ]
