# Generated by Django 6.0.3 on 2026-03-20 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agencyperformancescore',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='agencyperformancescore',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='agencyperformancescore',
            name='is_deleted',
        ),
        migrations.AlterField(
            model_name='agencyclientrelationship',
            name='agency_tenant_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='agencyclientrelationship',
            name='company_tenant_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='agencyjobassignment',
            name='agency_tenant_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='agencyperformancescore',
            name='agency_tenant_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='agencyperformancescore',
            name='company_tenant_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
