# Generated by Django 6.0.3 on 2026-03-24 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0004_emailtrackingconfig_guestportal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencyclientrelationship',
            name='payment_schedule',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
