# Generated by Django 6.0.3 on 2026-03-24 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0005_agencyclientrelationship_payment_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencyclientrelationship',
            name='contact_country_code',
            field=models.CharField(blank=True, default='IN', max_length=10),
        ),
        migrations.AddField(
            model_name='agencyclientrelationship',
            name='contact_phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='guestportal',
            name='contact_country_code',
            field=models.CharField(blank=True, default='IN', max_length=10),
        ),
        migrations.AddField(
            model_name='guestportal',
            name='contact_phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
