# Generated by Django 6.0.3 on 2026-03-26 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0007_agencyclientrelationship_retention_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencyclientrelationship',
            name='guarantee_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='agencyclientrelationship',
            name='guarantee_period_days',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='agencyclientrelationship',
            name='guarantee_resolution_type',
            field=models.CharField(choices=[('replacement_only', 'Replacement Only'), ('refund_only', 'Refund Only'), ('replacement_or_refund', 'Replacement or Refund'), ('no_guarantee', 'No Guarantee')], default='replacement_only', max_length=40),
        ),
        migrations.AddField(
            model_name='agencyclientrelationship',
            name='guarantee_start_type',
            field=models.CharField(choices=[('joining_date', 'Joining Date'), ('offer_acceptance_date', 'Offer Acceptance Date'), ('first_working_day', 'First Working Day')], default='joining_date', max_length=40),
        ),
        migrations.AddField(
            model_name='agencyclientrelationship',
            name='refund_mode',
            field=models.CharField(blank=True, choices=[('full_refund', 'Full Refund'), ('partial_refund', 'Partial Refund'), ('pro_rated_refund', 'Pro-rated Refund')], max_length=40),
        ),
        migrations.AddField(
            model_name='agencyclientrelationship',
            name='refund_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='agencyclientrelationship',
            name='replacement_attempt_limit',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('unlimited', 'Unlimited')], default='1', max_length=20),
        ),
        migrations.AddField(
            model_name='agencyclientrelationship',
            name='replacement_guarantee_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
