# Generated by Django 6.0.3 on 2026-04-01 12:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleRegistry',
            fields=[
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('module_key', models.CharField(db_index=True, max_length=120, unique=True)),
                ('module_name', models.CharField(db_index=True, max_length=200)),
                ('module_domain', models.CharField(db_index=True, max_length=120)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('blocked', 'Blocked'), ('partial', 'Partial'), ('complete', 'Complete')], db_index=True, default='not_started', max_length=20)),
                ('architecture_status', models.CharField(choices=[('not_ready', 'Not Ready'), ('partial', 'Partial'), ('ready', 'Ready'), ('verified', 'Verified')], db_index=True, default='not_ready', max_length=20)),
                ('backend_status', models.CharField(choices=[('not_ready', 'Not Ready'), ('partial', 'Partial'), ('ready', 'Ready'), ('verified', 'Verified')], db_index=True, default='not_ready', max_length=20)),
                ('frontend_status', models.CharField(choices=[('not_ready', 'Not Ready'), ('partial', 'Partial'), ('ready', 'Ready'), ('verified', 'Verified')], db_index=True, default='not_ready', max_length=20)),
                ('integration_status', models.CharField(choices=[('not_ready', 'Not Ready'), ('partial', 'Partial'), ('ready', 'Ready'), ('verified', 'Verified')], db_index=True, default='not_ready', max_length=20)),
                ('qa_status', models.CharField(choices=[('not_ready', 'Not Ready'), ('partial', 'Partial'), ('ready', 'Ready'), ('verified', 'Verified')], db_index=True, default='not_ready', max_length=20)),
                ('dependency_status', models.CharField(choices=[('not_ready', 'Not Ready'), ('partial', 'Partial'), ('ready', 'Ready'), ('verified', 'Verified')], db_index=True, default='not_ready', max_length=20)),
                ('blocker_status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('blocked', 'Blocked'), ('partial', 'Partial'), ('complete', 'Complete')], db_index=True, default='not_started', max_length=20)),
                ('priority_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='medium', max_length=20)),
                ('implementation_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'tos_module_registry',
                'ordering': ['implementation_order', 'priority_level', 'module_name'],
            },
        ),
        migrations.CreateModel(
            name='ModuleOwner',
            fields=[
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner_tool', models.CharField(db_index=True, max_length=120)),
                ('owner_name', models.CharField(blank=True, max_length=200)),
                ('responsibility', models.CharField(blank=True, max_length=120)),
                ('is_primary', models.BooleanField(db_index=True, default=False)),
                ('notes', models.TextField(blank=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owners', to='module_registry.moduleregistry')),
            ],
            options={
                'db_table': 'tos_module_owner',
            },
        ),
        migrations.CreateModel(
            name='ModuleBlocker',
            fields=[
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('blocker_status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('blocked', 'Blocked'), ('partial', 'Partial'), ('complete', 'Complete')], db_index=True, default='blocked', max_length=20)),
                ('priority_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='high', max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='medium', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blockers', to='module_registry.moduleregistry')),
            ],
            options={
                'db_table': 'tos_module_blocker',
            },
        ),
        migrations.CreateModel(
            name='ModuleAuditLog',
            fields=[
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(db_index=True, max_length=120)),
                ('actor_name', models.CharField(blank=True, max_length=200)),
                ('event_payload', models.JSONField(blank=True, default=dict)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='module_registry.moduleregistry')),
            ],
            options={
                'db_table': 'tos_module_audit_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModuleStatus',
            fields=[
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('blocked', 'Blocked'), ('partial', 'Partial'), ('complete', 'Complete')], db_index=True, default='not_started', max_length=20)),
                ('architecture_status', models.CharField(choices=[('not_ready', 'Not Ready'), ('partial', 'Partial'), ('ready', 'Ready'), ('verified', 'Verified')], db_index=True, default='not_ready', max_length=20)),
                ('backend_status', models.CharField(choices=[('not_ready', 'Not Ready'), ('partial', 'Partial'), ('ready', 'Ready'), ('verified', 'Verified')], db_index=True, default='not_ready', max_length=20)),
                ('frontend_status', models.CharField(choices=[('not_ready', 'Not Ready'), ('partial', 'Partial'), ('ready', 'Ready'), ('verified', 'Verified')], db_index=True, default='not_ready', max_length=20)),
                ('integration_status', models.CharField(choices=[('not_ready', 'Not Ready'), ('partial', 'Partial'), ('ready', 'Ready'), ('verified', 'Verified')], db_index=True, default='not_ready', max_length=20)),
                ('qa_status', models.CharField(choices=[('not_ready', 'Not Ready'), ('partial', 'Partial'), ('ready', 'Ready'), ('verified', 'Verified')], db_index=True, default='not_ready', max_length=20)),
                ('dependency_status', models.CharField(choices=[('not_ready', 'Not Ready'), ('partial', 'Partial'), ('ready', 'Ready'), ('verified', 'Verified')], db_index=True, default='not_ready', max_length=20)),
                ('blocker_status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('blocked', 'Blocked'), ('partial', 'Partial'), ('complete', 'Complete')], db_index=True, default='not_started', max_length=20)),
                ('architecture_approved', models.BooleanField(default=False)),
                ('implementation_ready', models.BooleanField(default=False)),
                ('frontend_ready', models.BooleanField(default=False)),
                ('backend_ready', models.BooleanField(default=False)),
                ('verification_required', models.BooleanField(default=True)),
                ('module', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='status_record', to='module_registry.moduleregistry')),
            ],
            options={
                'db_table': 'tos_module_status',
            },
        ),
        migrations.CreateModel(
            name='ModuleDependency',
            fields=[
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dependency_status', models.CharField(choices=[('not_ready', 'Not Ready'), ('partial', 'Partial'), ('ready', 'Ready'), ('verified', 'Verified')], db_index=True, default='not_ready', max_length=20)),
                ('is_hard_blocker', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('depends_on', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependents', to='module_registry.moduleregistry')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='module_registry.moduleregistry')),
            ],
            options={
                'db_table': 'tos_module_dependency',
                'unique_together': {('module', 'depends_on')},
            },
        ),
    ]
