# Generated by Django 6.0.3 on 2026-03-25 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='label',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='permission',
            name='module_label',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
