# Generated by Django 6.0.3 on 2026-04-05 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automation_notifications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='workflownotificationpreference',
            name='unique_user_notif_pref',
        ),
        migrations.RenameIndex(
            model_name='workflowescalationnotification',
            new_name='automation__tenant__fffeea_idx',
            old_name='wf_escal_tenant_status_idx',
        ),
        migrations.RenameIndex(
            model_name='workflowescalationnotification',
            new_name='automation__tenant__4e1280_idx',
            old_name='wf_escal_tenant_wf_idx',
        ),
        migrations.RenameIndex(
            model_name='workflownotificationdelivery',
            new_name='automation__tenant__14d8f3_idx',
            old_name='wf_notif_del_tenant_status_idx',
        ),
        migrations.RenameIndex(
            model_name='workflownotificationdelivery',
            new_name='automation__tenant__eb9f2a_idx',
            old_name='wf_notif_del_ch_status_idx',
        ),
        migrations.RenameIndex(
            model_name='workflownotificationdelivery',
            new_name='automation__tenant__37ce69_idx',
            old_name='wf_notif_del_dedupe_idx',
        ),
        migrations.RenameIndex(
            model_name='workflownotificationdelivery',
            new_name='automation__executi_289d3b_idx',
            old_name='wf_notif_del_exec_status_idx',
        ),
        migrations.RenameIndex(
            model_name='workflownotificationinsight',
            new_name='automation__tenant__05078b_idx',
            old_name='wf_notif_insight_type_idx',
        ),
        migrations.RenameIndex(
            model_name='workflownotificationpreference',
            new_name='automation__tenant__547c55_idx',
            old_name='wf_notif_pref_tenant_user_idx',
        ),
        migrations.RenameIndex(
            model_name='workflownotificationrule',
            new_name='automation__tenant__29fd3e_idx',
            old_name='wf_notif_rule_tenant_wf_idx',
        ),
        migrations.RenameIndex(
            model_name='workflownotificationrule',
            new_name='automation__tenant__2fb820_idx',
            old_name='wf_notif_rule_event_idx',
        ),
        migrations.AlterUniqueTogether(
            name='workflownotificationpreference',
            unique_together={('tenant_id', 'user_id', 'notification_type')},
        ),
    ]
