# Generated by Django 6.0.3 on 2026-04-04 13:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowChangeSet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('workflow_id', models.UUIDField(db_index=True)),
                ('from_version', models.IntegerField(blank=True, null=True)),
                ('to_version', models.IntegerField(blank=True, null=True)),
                ('change_summary', models.JSONField(blank=True, default=dict)),
                ('risk_score', models.IntegerField(default=0)),
                ('impact_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=20)),
            ],
            options={
                'db_table': 'icc_workflow_change_sets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowDependencyMap',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('workflow_id', models.UUIDField(db_index=True)),
                ('dependent_workflow_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('dependency_type', models.CharField(choices=[('trigger_dependency', 'Trigger Dependency'), ('action_dependency', 'Action Dependency'), ('sla_dependency', 'SLA Dependency'), ('task_dependency', 'Task Dependency'), ('notification_dependency', 'Notification Dependency'), ('cross_module_dependency', 'Cross Module Dependency')], max_length=50)),
            ],
            options={
                'db_table': 'icc_workflow_dependency_maps',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowDeploymentPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('deployment_strategy', models.CharField(choices=[('immediate', 'Immediate'), ('staged', 'Staged'), ('canary', 'Canary'), ('manual_approval', 'Manual Approval')], default='immediate', max_length=30)),
                ('rollout_percentage', models.IntegerField(default=100)),
                ('rollout_steps', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(default='pending', max_length=30)),
                ('change_set', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deployment_plan', to='automation_change_impact.workflowchangeset')),
            ],
            options={
                'db_table': 'icc_workflow_deployment_plans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowImpactAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('affected_module', models.JSONField(blank=True, default=list)),
                ('affected_workflows', models.JSONField(blank=True, default=list)),
                ('affected_slas', models.JSONField(blank=True, default=list)),
                ('affected_notifications', models.JSONField(blank=True, default=list)),
                ('affected_tasks', models.JSONField(blank=True, default=list)),
                ('affected_users_count', models.IntegerField(default=0)),
                ('risk_reason', models.TextField(blank=True)),
                ('change_set', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='impact_analysis', to='automation_change_impact.workflowchangeset')),
            ],
            options={
                'db_table': 'icc_workflow_impact_analyses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowRollbackPreview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('rollback_possible', models.BooleanField(default=True)),
                ('rollback_impact', models.TextField(blank=True)),
                ('change_set', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rollback_preview', to='automation_change_impact.workflowchangeset')),
            ],
            options={
                'db_table': 'icc_workflow_rollback_previews',
                'ordering': ['-created_at'],
            },
        ),
    ]
