from django.urls import path

from apps.workflow_execution.api.views import (
    WorkflowInstanceViewSet,
    WorkflowWaitStateViewSet,
    WorkflowSLAListView,
    WorkflowSLAResolveView,
    WorkflowStageSLAByStageView,
    WorkflowNotificationListView,
    WorkflowNotificationDetailView,
    WorkflowNotificationTestSendView,
    WorkflowNotificationRetryView,
    WorkflowSchedulerTaskListView,
    WorkflowSchedulerTaskDetailView,
    WorkflowSchedulerTaskRetryView,
    WorkflowSchedulerTaskCancelView,
    WorkflowConditionRuleListView,
    WorkflowConditionRuleDetailView,
    WorkflowConditionGroupListView,
    WorkflowConditionGroupDetailView,
    WorkflowConditionGroupTestEvaluateView,
    WorkflowActionListView,
    WorkflowActionDetailView,
    WorkflowActionTestRunView,
    WorkflowHumanTaskListView,
    WorkflowHumanTaskDetailView,
    WorkflowHumanTaskCompleteView,
    WorkflowHumanTaskRejectView,
    WorkflowHumanTaskEscalateView,
    WorkflowVersionListView,
    WorkflowVersionDetailView,
    WorkflowDraftGetView,
    WorkflowVersionsByWorkflowView,
    WorkflowVersionCompareView,
    WorkflowDraftCreateView,
    WorkflowDraftSaveView,
    WorkflowDraftPublishView,
    WorkflowVersionRollbackView,
    WorkflowVersionCloneView,
    WorkflowDraftDiscardView,
    WorkflowTemplateListView,
    WorkflowTemplateDetailView,
    WorkflowTemplateVersionsView,
    WorkflowTemplateCloneView,
    WorkflowTemplateApplyView,
    WorkflowTemplatePublishView,
    WorkflowTemplateArchiveView,
    WorkflowTemplateImportView,
    WorkflowTemplateExportView,
    WorkflowTemplateRateView,
    WorkflowBuilderGraphView,
    WorkflowBuilderNodeCreateView,
    WorkflowBuilderNodeUpdateDeleteView,
    WorkflowBuilderConnectionCreateView,
    WorkflowBuilderConnectionDeleteView,
    WorkflowBuilderValidateView,
    WorkflowBuilderSaveView,
    WorkflowObservabilityInstanceTimelineView,
    WorkflowObservabilityInstanceTraceView,
    WorkflowObservabilityInstanceSnapshotView,
    WorkflowObservabilityInstanceMetricsView,
    WorkflowObservabilityInstanceHealthView,
    WorkflowObservabilityWorkflowSummaryView,
    WorkflowObservabilityWorkflowFailuresView,
    WorkflowObservabilityWorkflowSLARisksView,
    WorkflowRecoveryCaseListView,
    WorkflowRecoveryCaseDetailView,
    WorkflowRecoveryPolicyListCreateView,
    WorkflowRecoveryCaseRetryView,
    WorkflowRecoveryCaseEscalateView,
    WorkflowRecoveryCaseManualResumeView,
    WorkflowRecoveryCaseManualSkipView,
    WorkflowRecoveryCaseManualFailView,
    WorkflowAnalyticsWorkflowListView,
    WorkflowAnalyticsSummaryView,
    WorkflowAnalyticsTimelineView,
    WorkflowAnalyticsBottlenecksView,
    WorkflowAnalyticsFailuresView,
    WorkflowAnalyticsStagesView,
    WorkflowAnalyticsActionsView,
    WorkflowAnalyticsImpactView,
    WorkflowAnalyticsTrendsView,
    CompanyAgencySubmissionCallbackView,
    CompanyAgencyCoordinationCallbackView,
    CompanyCandidateResponseCallbackView,
    CompanyCandidateInterviewConfirmCallbackView,
    CompanyCandidateOfferResponseCallbackView,
    CompanyCandidateDocumentUploadedCallbackView,
    CompanyCandidateDocumentSignedCallbackView,
    CompanyHRMSHandoffCallbackView,
    CompanyHRMSHandoffAckCallbackView,
)


workflow_instance_list = WorkflowInstanceViewSet.as_view({'get': 'list'})
workflow_instance_detail = WorkflowInstanceViewSet.as_view({'get': 'retrieve'})
workflow_instance_timeline = WorkflowInstanceViewSet.as_view({'get': 'timeline'})
workflow_instance_stages = WorkflowInstanceViewSet.as_view({'get': 'stages'})
workflow_instance_wait_states = WorkflowInstanceViewSet.as_view({'get': 'wait_states'})
workflow_instance_sla = WorkflowInstanceViewSet.as_view({'get': 'sla'})
workflow_instance_failures = WorkflowInstanceViewSet.as_view({'get': 'failures'})
workflow_instance_actor_ownership = WorkflowInstanceViewSet.as_view({'get': 'actor_ownership'})
workflow_instance_notifications = WorkflowInstanceViewSet.as_view({'get': 'notifications'})
workflow_instance_scheduled_tasks = WorkflowInstanceViewSet.as_view({'get': 'scheduled_tasks'})
workflow_instance_condition_logs = WorkflowInstanceViewSet.as_view({'get': 'condition_logs'})
workflow_instance_action_logs = WorkflowInstanceViewSet.as_view({'get': 'action_logs'})
workflow_instance_human_tasks = WorkflowInstanceViewSet.as_view({'get': 'human_tasks'})
workflow_instance_recovery = WorkflowInstanceViewSet.as_view({'get': 'recovery'})
workflow_instance_retry = WorkflowInstanceViewSet.as_view({'post': 'retry'})
workflow_wait_resume = WorkflowWaitStateViewSet.as_view({'post': 'resume'})

urlpatterns = [
    path('workflow-sla/', WorkflowSLAListView.as_view(), name='workflow-sla-list'),
    path('workflow-sla/<uuid:pk>/resolve/', WorkflowSLAResolveView.as_view(), name='workflow-sla-resolve'),
    path('workflow-instances/', workflow_instance_list, name='workflow-instance-list'),
    path('workflow-instances/<uuid:pk>/', workflow_instance_detail, name='workflow-instance-detail'),
    path('workflow-instances/<uuid:pk>/timeline/', workflow_instance_timeline, name='workflow-instance-timeline'),
    path('workflow-instances/<uuid:pk>/stages/', workflow_instance_stages, name='workflow-instance-stages'),
    path('workflow-instances/<uuid:pk>/wait-states/', workflow_instance_wait_states, name='workflow-instance-wait-states'),
    path('workflow-instances/<uuid:pk>/sla/', workflow_instance_sla, name='workflow-instance-sla'),
    path('workflow-instances/<uuid:pk>/failures/', workflow_instance_failures, name='workflow-instance-failures'),
    path('workflow-instances/<uuid:pk>/actor-ownership/', workflow_instance_actor_ownership, name='workflow-instance-actor-ownership'),
    path('workflow-instances/<uuid:pk>/notifications/', workflow_instance_notifications, name='workflow-instance-notifications'),
    path('workflow-instances/<uuid:pk>/scheduled-tasks/', workflow_instance_scheduled_tasks, name='workflow-instance-scheduled-tasks'),
    path('workflow-instances/<uuid:pk>/condition-logs/', workflow_instance_condition_logs, name='workflow-instance-condition-logs'),
    path('workflow-instances/<uuid:pk>/action-logs/', workflow_instance_action_logs, name='workflow-instance-action-logs'),
    path('workflow-instances/<uuid:pk>/human-tasks/', workflow_instance_human_tasks, name='workflow-instance-human-tasks'),
    path('workflow-instances/<uuid:pk>/recovery/', workflow_instance_recovery, name='workflow-instance-recovery'),
    path('workflow-instances/<uuid:pk>/retry/', workflow_instance_retry, name='workflow-instance-retry'),
    path('workflow-wait/<uuid:pk>/resume/', workflow_wait_resume, name='workflow-wait-resume'),
    path('workflow-stages/<uuid:pk>/sla/', WorkflowStageSLAByStageView.as_view(), name='workflow-stage-sla'),
    path('workflow-notifications/', WorkflowNotificationListView.as_view(), name='workflow-notification-list'),
    path('workflow-notifications/<uuid:pk>/', WorkflowNotificationDetailView.as_view(), name='workflow-notification-detail'),
    path('workflow-notifications/test-send/', WorkflowNotificationTestSendView.as_view(), name='workflow-notification-test-send'),
    path('workflow-notifications/<uuid:pk>/retry/', WorkflowNotificationRetryView.as_view(), name='workflow-notification-retry'),
    path('workflow-scheduler/tasks/', WorkflowSchedulerTaskListView.as_view(), name='workflow-scheduler-task-list'),
    path('workflow-scheduler/tasks/<uuid:pk>/', WorkflowSchedulerTaskDetailView.as_view(), name='workflow-scheduler-task-detail'),
    path('workflow-scheduler/tasks/<uuid:pk>/retry/', WorkflowSchedulerTaskRetryView.as_view(), name='workflow-scheduler-task-retry'),
    path('workflow-scheduler/tasks/<uuid:pk>/cancel/', WorkflowSchedulerTaskCancelView.as_view(), name='workflow-scheduler-task-cancel'),
    path('workflow-conditions/', WorkflowConditionRuleListView.as_view(), name='workflow-condition-rule-list'),
    path('workflow-conditions/<uuid:pk>/', WorkflowConditionRuleDetailView.as_view(), name='workflow-condition-rule-detail'),
    path('workflow-condition-groups/', WorkflowConditionGroupListView.as_view(), name='workflow-condition-group-list'),
    path('workflow-condition-groups/<uuid:pk>/', WorkflowConditionGroupDetailView.as_view(), name='workflow-condition-group-detail'),
    path(
        'workflow-condition-groups/<uuid:pk>/test-evaluate/',
        WorkflowConditionGroupTestEvaluateView.as_view(),
        name='workflow-condition-group-test-evaluate',
    ),
    path('workflow-actions/', WorkflowActionListView.as_view(), name='workflow-action-list'),
    path('workflow-actions/<uuid:pk>/', WorkflowActionDetailView.as_view(), name='workflow-action-detail'),
    path('workflow-actions/<uuid:pk>/test-run/', WorkflowActionTestRunView.as_view(), name='workflow-action-test-run'),
    path('workflow-human-tasks/', WorkflowHumanTaskListView.as_view(), name='workflow-human-task-list'),
    path('workflow-human-tasks/<uuid:pk>/', WorkflowHumanTaskDetailView.as_view(), name='workflow-human-task-detail'),
    path('workflow-human-tasks/<uuid:pk>/complete/', WorkflowHumanTaskCompleteView.as_view(), name='workflow-human-task-complete'),
    path('workflow-human-tasks/<uuid:pk>/reject/', WorkflowHumanTaskRejectView.as_view(), name='workflow-human-task-reject'),
    path('workflow-human-tasks/<uuid:pk>/escalate/', WorkflowHumanTaskEscalateView.as_view(), name='workflow-human-task-escalate'),
    path('workflow-versions/', WorkflowVersionListView.as_view(), name='workflow-version-list'),
    path('workflow-versions/<uuid:pk>/', WorkflowVersionDetailView.as_view(), name='workflow-version-detail'),
    path('workflows/<uuid:workflow_id>/draft/', WorkflowDraftGetView.as_view(), name='workflow-draft-get'),
    path('workflows/<uuid:workflow_id>/versions/', WorkflowVersionsByWorkflowView.as_view(), name='workflow-versions-by-workflow'),
    path('workflows/<uuid:workflow_id>/versions/compare/', WorkflowVersionCompareView.as_view(), name='workflow-versions-compare'),
    path('workflows/<uuid:workflow_id>/draft/create/', WorkflowDraftCreateView.as_view(), name='workflow-draft-create'),
    path('workflows/<uuid:workflow_id>/draft/save/', WorkflowDraftSaveView.as_view(), name='workflow-draft-save'),
    path('workflows/<uuid:workflow_id>/draft/publish/', WorkflowDraftPublishView.as_view(), name='workflow-draft-publish'),
    path('workflows/<uuid:workflow_id>/versions/<uuid:version_id>/rollback/', WorkflowVersionRollbackView.as_view(), name='workflow-version-rollback'),
    path('workflows/<uuid:workflow_id>/versions/<uuid:version_id>/clone/', WorkflowVersionCloneView.as_view(), name='workflow-version-clone'),
    path('workflows/<uuid:workflow_id>/draft/discard/', WorkflowDraftDiscardView.as_view(), name='workflow-draft-discard'),
    path('workflow-templates/', WorkflowTemplateListView.as_view(), name='workflow-template-list'),
    path('workflow-templates/<uuid:pk>/', WorkflowTemplateDetailView.as_view(), name='workflow-template-detail'),
    path('workflow-templates/<uuid:pk>/versions/', WorkflowTemplateVersionsView.as_view(), name='workflow-template-versions'),
    path('workflow-templates/<uuid:pk>/clone/', WorkflowTemplateCloneView.as_view(), name='workflow-template-clone'),
    path('workflow-templates/<uuid:pk>/apply/', WorkflowTemplateApplyView.as_view(), name='workflow-template-apply'),
    path('workflow-templates/<uuid:pk>/publish/', WorkflowTemplatePublishView.as_view(), name='workflow-template-publish'),
    path('workflow-templates/<uuid:pk>/archive/', WorkflowTemplateArchiveView.as_view(), name='workflow-template-archive'),
    path('workflow-templates/import/', WorkflowTemplateImportView.as_view(), name='workflow-template-import'),
    path('workflow-templates/<uuid:pk>/export/', WorkflowTemplateExportView.as_view(), name='workflow-template-export'),
    path('workflow-templates/<uuid:pk>/rate/', WorkflowTemplateRateView.as_view(), name='workflow-template-rate'),
    path('workflow-builder/<uuid:workflow_id>/', WorkflowBuilderGraphView.as_view(), name='workflow-builder-graph'),
    path('workflow-builder/node/', WorkflowBuilderNodeCreateView.as_view(), name='workflow-builder-node-create'),
    path('workflow-builder/node/<uuid:pk>/', WorkflowBuilderNodeUpdateDeleteView.as_view(), name='workflow-builder-node-update-delete'),
    path('workflow-builder/connection/', WorkflowBuilderConnectionCreateView.as_view(), name='workflow-builder-connection-create'),
    path('workflow-builder/connection/<uuid:pk>/', WorkflowBuilderConnectionDeleteView.as_view(), name='workflow-builder-connection-delete'),
    path('workflow-builder/validate/', WorkflowBuilderValidateView.as_view(), name='workflow-builder-validate'),
    path('workflow-builder/save/', WorkflowBuilderSaveView.as_view(), name='workflow-builder-save'),
    path('workflow-observability/instances/<uuid:instance_id>/timeline/', WorkflowObservabilityInstanceTimelineView.as_view(), name='workflow-observability-instance-timeline'),
    path('workflow-observability/instances/<uuid:instance_id>/trace/', WorkflowObservabilityInstanceTraceView.as_view(), name='workflow-observability-instance-trace'),
    path('workflow-observability/instances/<uuid:instance_id>/snapshot/', WorkflowObservabilityInstanceSnapshotView.as_view(), name='workflow-observability-instance-snapshot'),
    path('workflow-observability/instances/<uuid:instance_id>/metrics/', WorkflowObservabilityInstanceMetricsView.as_view(), name='workflow-observability-instance-metrics'),
    path('workflow-observability/instances/<uuid:instance_id>/health/', WorkflowObservabilityInstanceHealthView.as_view(), name='workflow-observability-instance-health'),
    path('workflow-observability/workflows/<uuid:workflow_id>/summary/', WorkflowObservabilityWorkflowSummaryView.as_view(), name='workflow-observability-workflow-summary'),
    path('workflow-observability/workflows/<uuid:workflow_id>/failures/', WorkflowObservabilityWorkflowFailuresView.as_view(), name='workflow-observability-workflow-failures'),
    path('workflow-observability/workflows/<uuid:workflow_id>/sla-risks/', WorkflowObservabilityWorkflowSLARisksView.as_view(), name='workflow-observability-workflow-sla-risks'),
    path('workflow-recovery/cases/', WorkflowRecoveryCaseListView.as_view(), name='workflow-recovery-case-list'),
    path('workflow-recovery/cases/<uuid:pk>/', WorkflowRecoveryCaseDetailView.as_view(), name='workflow-recovery-case-detail'),
    path('workflow-recovery/policies/', WorkflowRecoveryPolicyListCreateView.as_view(), name='workflow-recovery-policy-list-create'),
    path('workflow-recovery/cases/<uuid:pk>/retry/', WorkflowRecoveryCaseRetryView.as_view(), name='workflow-recovery-case-retry'),
    path('workflow-recovery/cases/<uuid:pk>/escalate/', WorkflowRecoveryCaseEscalateView.as_view(), name='workflow-recovery-case-escalate'),
    path('workflow-recovery/cases/<uuid:pk>/manual-resume/', WorkflowRecoveryCaseManualResumeView.as_view(), name='workflow-recovery-case-manual-resume'),
    path('workflow-recovery/cases/<uuid:pk>/manual-skip/', WorkflowRecoveryCaseManualSkipView.as_view(), name='workflow-recovery-case-manual-skip'),
    path('workflow-recovery/cases/<uuid:pk>/manual-fail/', WorkflowRecoveryCaseManualFailView.as_view(), name='workflow-recovery-case-manual-fail'),
    path('workflow-analytics/workflows/', WorkflowAnalyticsWorkflowListView.as_view(), name='workflow-analytics-workflows'),
    path('workflow-analytics/workflows/<uuid:workflow_id>/summary/', WorkflowAnalyticsSummaryView.as_view(), name='workflow-analytics-summary'),
    path('workflow-analytics/workflows/<uuid:workflow_id>/timeline/', WorkflowAnalyticsTimelineView.as_view(), name='workflow-analytics-timeline'),
    path('workflow-analytics/workflows/<uuid:workflow_id>/bottlenecks/', WorkflowAnalyticsBottlenecksView.as_view(), name='workflow-analytics-bottlenecks'),
    path('workflow-analytics/workflows/<uuid:workflow_id>/failures/', WorkflowAnalyticsFailuresView.as_view(), name='workflow-analytics-failures'),
    path('workflow-analytics/workflows/<uuid:workflow_id>/stages/', WorkflowAnalyticsStagesView.as_view(), name='workflow-analytics-stages'),
    path('workflow-analytics/workflows/<uuid:workflow_id>/actions/', WorkflowAnalyticsActionsView.as_view(), name='workflow-analytics-actions'),
    path('workflow-analytics/workflows/<uuid:workflow_id>/impact/', WorkflowAnalyticsImpactView.as_view(), name='workflow-analytics-impact'),
    path('workflow-analytics/workflows/<uuid:workflow_id>/trends/', WorkflowAnalyticsTrendsView.as_view(), name='workflow-analytics-trends'),
    path('company/external/agency-submission/', CompanyAgencySubmissionCallbackView.as_view(), name='company-external-agency-submission'),
    path('company/external/agency-coordination-response/', CompanyAgencyCoordinationCallbackView.as_view(), name='company-external-agency-coordination-response'),
    path('company/external/candidate-response/', CompanyCandidateResponseCallbackView.as_view(), name='company-external-candidate-response'),
    path('company/external/candidate-interview-confirm/', CompanyCandidateInterviewConfirmCallbackView.as_view(), name='company-external-candidate-interview-confirm'),
    path('company/external/candidate-offer-response/', CompanyCandidateOfferResponseCallbackView.as_view(), name='company-external-candidate-offer-response'),
    path('company/external/candidate-document-uploaded/', CompanyCandidateDocumentUploadedCallbackView.as_view(), name='company-external-candidate-document-uploaded'),
    path('company/external/candidate-document-signed/', CompanyCandidateDocumentSignedCallbackView.as_view(), name='company-external-candidate-document-signed'),
    path('company/external/hrms-handoff/', CompanyHRMSHandoffCallbackView.as_view(), name='company-external-hrms-handoff'),
    path('company/external/hrms-handoff-ack/', CompanyHRMSHandoffAckCallbackView.as_view(), name='company-external-hrms-handoff-ack'),
]
