# Generated by Django 6.0.3 on 2026-03-20 11:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('whatsapp', models.CharField(blank=True, max_length=20)),
                ('linkedin_url', models.TextField(blank=True)),
                ('current_title', models.CharField(blank=True, max_length=255)),
                ('current_company', models.CharField(blank=True, max_length=255)),
                ('current_city', models.CharField(blank=True, max_length=100)),
                ('current_country', models.CharField(blank=True, max_length=100)),
                ('experience_years', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('expected_salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('expected_salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('salary_currency', models.CharField(default='INR', max_length=10)),
                ('notice_period_days', models.IntegerField(blank=True, null=True)),
                ('availability_date', models.DateField(blank=True, null=True)),
                ('is_actively_looking', models.BooleanField(default=True)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('source_detail', models.TextField(blank=True)),
                ('passport_id', models.UUIDField(blank=True, null=True)),
                ('global_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('is_duplicate', models.BooleanField(default=False)),
                ('duplicate_of', models.UUIDField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('languages', models.JSONField(blank=True, default=list)),
                ('assigned_to', models.UUIDField(blank=True, null=True)),
                ('owner_user_id', models.UUIDField(blank=True, null=True)),
                ('owner_tenant_id', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'db_table': 'candidates_candidate',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CandidateNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('candidate_id', models.UUIDField(db_index=True)),
                ('note_text', models.TextField()),
                ('note_type', models.CharField(choices=[('general', 'General'), ('call_log', 'Call Log'), ('email_log', 'Email Log'), ('interview_note', 'Interview Note'), ('warning', 'Warning'), ('positive', 'Positive')], default='general', max_length=50)),
                ('is_private', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'candidates_note',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CandidateProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('candidate_id', models.UUIDField(db_index=True, unique=True)),
                ('summary', models.TextField(blank=True)),
                ('work_experience', models.JSONField(blank=True, default=list)),
                ('education', models.JSONField(blank=True, default=list)),
                ('certifications', models.JSONField(blank=True, default=list)),
                ('projects', models.JSONField(blank=True, default=list)),
                ('awards', models.JSONField(blank=True, default=list)),
                ('cv_url', models.TextField(blank=True)),
                ('cv_parsed_data', models.JSONField(blank=True, default=dict)),
                ('cv_uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('portfolio_url', models.TextField(blank=True)),
                ('github_url', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'candidates_profile',
            },
        ),
    ]
