# Generated by Django 6.0.3 on 2026-03-22 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0005_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='graduation_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='highest_education',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='candidate',
            name='nationality',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='candidate',
            name='preferred_locations',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='candidate',
            name='relocation_willing',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='candidate',
            name='resume_url',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='work_authorization',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
