# Generated by Django 6.0.3 on 2026-03-24 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0006_candidate_graduation_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='phone_country_code',
            field=models.CharField(blank=True, default='IN', max_length=10),
        ),
        migrations.AddField(
            model_name='candidate',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
