# Generated by Django 6.0.3 on 2026-03-24 10:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0007_candidate_phone_country_code_candidate_phone_number'),
        ('jobs', '0001_initial'),
        ('pipeline', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatenote',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidate_notes', to='pipeline.application'),
        ),
        migrations.AddField(
            model_name='candidatenote',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='candidatenote',
            name='note_context',
            field=models.CharField(choices=[('general', 'General'), ('call', 'Call Note'), ('email', 'Email Note'), ('submission', 'Submission Note'), ('client_visible', 'Client Visible'), ('interview', 'Interview Feedback'), ('offer', 'Offer / Negotiation')], default='general', max_length=50),
        ),
        migrations.AddField(
            model_name='candidatenote',
            name='visibility',
            field=models.CharField(choices=[('internal', 'Internal Only'), ('client', 'Client Visible'), ('panel', 'Interview Panel'), ('system', 'System Generated'), ('private', 'Private to Author')], default='internal', max_length=50),
        ),
        migrations.CreateModel(
            name='CandidateEngagement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('engagement_type', models.CharField(choices=[('lead', 'New Lead'), ('job_sourced', 'Sourced for Job'), ('reapplied', 'Reapplied'), ('resurface', 'Resurfaced from Database'), ('revival', 'Revived Previous Candidate'), ('referral', 'Referral'), ('direct_approach', 'Direct Approach')], default='lead', max_length=50)),
                ('stage', models.CharField(choices=[('new', 'New Lead'), ('contacted', 'Contacted'), ('interested', 'Interested'), ('not_interested', 'Not Interested'), ('follow_up', 'Follow Up Due'), ('shortlisted', 'Shortlisted Internally'), ('submitted', 'Submitted to Client'), ('client_review', 'Client Review'), ('interviewing', 'Interviewing'), ('offered', 'Offered'), ('placed', 'Placed'), ('closed', 'Closed'), ('lost', 'Lost'), ('revived', 'Revived')], default='new', max_length=50)),
                ('priority', models.CharField(choices=[('hot', 'Hot'), ('warm', 'Warm'), ('cold', 'Cold')], default='warm', max_length=10)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('source_channel', models.CharField(blank=True, max_length=100, null=True)),
                ('follow_up_at', models.DateTimeField(blank=True, null=True)),
                ('last_activity_at', models.DateTimeField(blank=True, null=True)),
                ('closure_reason', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(default=dict)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='engagements', to='candidates.candidate')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_engagements', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='engagements', to='jobs.jobrequisition')),
                ('owner_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_engagements', to=settings.AUTH_USER_MODEL)),
                ('resurrected_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resurrections', to='candidates.candidateengagement')),
            ],
            options={
                'db_table': 'candidate_engagements',
            },
        ),
        migrations.AddField(
            model_name='candidatenote',
            name='engagement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to='candidates.candidateengagement'),
        ),
        migrations.CreateModel(
            name='CandidateWorkspace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('priority', models.CharField(choices=[('hot', 'Hot'), ('warm', 'Warm'), ('cold', 'Cold')], default='warm', max_length=10)),
                ('relationship_status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('do_not_contact', 'Do Not Contact'), ('blacklisted', 'Blacklisted'), ('favourite', 'Favourite')], default='active', max_length=50)),
                ('tags', models.JSONField(default=list)),
                ('local_rating', models.IntegerField(blank=True, null=True)),
                ('source_for_tenant', models.CharField(blank=True, max_length=100, null=True)),
                ('talent_pool_ids', models.JSONField(default=list)),
                ('last_worked_at', models.DateTimeField(blank=True, null=True)),
                ('custom_fields', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(default=dict)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workspaces', to='candidates.candidate')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_workspaces', to=settings.AUTH_USER_MODEL)),
                ('owner_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_workspaces', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'candidate_workspaces',
            },
        ),
        migrations.AddField(
            model_name='candidateengagement',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='engagements', to='candidates.candidateworkspace'),
        ),
        migrations.CreateModel(
            name='CandidateTimelineEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('event_type', models.CharField(db_index=True, max_length=100)),
                ('payload', models.JSONField(default=dict)),
                ('source', models.CharField(choices=[('user', 'User Action'), ('system', 'System'), ('agency', 'Agency'), ('import', 'Import'), ('candidate', 'Candidate')], default='user', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidate_timeline_actions', to=settings.AUTH_USER_MODEL)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='timeline_events', to='candidates.candidate')),
                ('engagement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timeline_events', to='candidates.candidateengagement')),
            ],
            options={
                'db_table': 'candidate_timeline_events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant_id', 'candidate', '-created_at'], name='candidate_t_tenant__ebcf45_idx'), models.Index(fields=['tenant_id', 'engagement'], name='candidate_t_tenant__812953_idx'), models.Index(fields=['event_type'], name='candidate_t_event_t_713891_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='candidateworkspace',
            index=models.Index(fields=['tenant_id', 'priority'], name='candidate_w_tenant__cef0cc_idx'),
        ),
        migrations.AddIndex(
            model_name='candidateworkspace',
            index=models.Index(fields=['tenant_id', 'relationship_status'], name='candidate_w_tenant__5566ec_idx'),
        ),
        migrations.AddIndex(
            model_name='candidateworkspace',
            index=models.Index(fields=['tenant_id', 'owner_user'], name='candidate_w_tenant__3b1812_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='candidateworkspace',
            unique_together={('tenant_id', 'candidate')},
        ),
        migrations.AddIndex(
            model_name='candidateengagement',
            index=models.Index(fields=['tenant_id', 'is_active'], name='candidate_e_tenant__a27208_idx'),
        ),
        migrations.AddIndex(
            model_name='candidateengagement',
            index=models.Index(fields=['tenant_id', 'stage'], name='candidate_e_tenant__dad0d7_idx'),
        ),
        migrations.AddIndex(
            model_name='candidateengagement',
            index=models.Index(fields=['tenant_id', 'priority', 'is_active'], name='candidate_e_tenant__6e6f44_idx'),
        ),
        migrations.AddIndex(
            model_name='candidateengagement',
            index=models.Index(fields=['tenant_id', 'owner_user', 'is_active'], name='candidate_e_tenant__a4f05d_idx'),
        ),
        migrations.AddIndex(
            model_name='candidateengagement',
            index=models.Index(fields=['tenant_id', 'follow_up_at'], name='candidate_e_tenant__177569_idx'),
        ),
        migrations.AddIndex(
            model_name='candidateengagement',
            index=models.Index(fields=['candidate', 'is_active'], name='candidate_e_candida_718355_idx'),
        ),
    ]
