# Generated by Django 6.0.3 on 2026-03-24 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0008_candidatenote_application_candidatenote_is_pinned_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateengagement',
            name='engagement_type',
            field=models.CharField(choices=[('lead', 'New Lead'), ('job_sourced', 'Sourced for Job'), ('sourced', 'Sourced'), ('imported', 'Imported'), ('applied', 'Applied'), ('invited', 'Invited'), ('reapplied', 'Reapplied'), ('resurface', 'Resurfaced from Database'), ('revival', 'Revived Previous Candidate'), ('referral', 'Referral'), ('direct_approach', 'Direct Approach')], default='lead', max_length=50),
        ),
    ]
