# Generated by Django 6.0.3 on 2026-03-24 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0009_alter_candidateengagement_engagement_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateengagement',
            name='engagement_type',
            field=models.CharField(choices=[('lead', 'Lead'), ('job_sourced', 'Sourced for Job'), ('sourced', 'Sourced'), ('reapplied', 'Reapplied'), ('resurface', 'Resurfaced from Database'), ('revival', 'Revived Previous Candidate'), ('referral', 'Referral'), ('direct_approach', 'Direct Approach'), ('direct', 'Direct'), ('imported', 'Imported'), ('applied', 'Applied'), ('invited', 'Invited')], default='lead', max_length=50),
        ),
    ]
