# Generated by Django 6.0.3 on 2026-03-25 11:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0010_alter_candidateengagement_engagement_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='active_job_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='auto_followup_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='candidate',
            name='auto_nurture_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='candidate',
            name='auto_stage_suggestions_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='automation_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='candidate',
            name='duplicate_review_status',
            field=models.CharField(choices=[('not_flagged', 'Not Flagged'), ('pending_review', 'Pending Review'), ('confirmed_duplicate', 'Confirmed Duplicate'), ('merged', 'Merged'), ('ignored', 'Ignored')], db_index=True, default='not_flagged', max_length=30),
        ),
        migrations.AddField(
            model_name='candidate',
            name='engagement_stage',
            field=models.CharField(choices=[('new_lead', 'New Lead'), ('contacted', 'Contacted'), ('follow_up', 'Follow Up'), ('qualified', 'Qualified'), ('interested', 'Interested'), ('sourced_for_job', 'Sourced for Job'), ('submitted', 'Submitted'), ('interviewing', 'Interviewing'), ('offered', 'Offered'), ('closed_or_nurture', 'Closed / Nurture')], db_index=True, default='new_lead', max_length=30),
        ),
        migrations.AddField(
            model_name='candidate',
            name='fit_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='is_in_active_work',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='candidate',
            name='last_activity_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='last_contact_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='lifecycle_state',
            field=models.CharField(choices=[('new', 'New'), ('active', 'Active'), ('nurture', 'Nurture'), ('dormant', 'Dormant'), ('archived', 'Archived')], db_index=True, default='new', max_length=30),
        ),
        migrations.AddField(
            model_name='candidate',
            name='next_follow_up_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='passport_linked',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='candidate',
            name='passport_visibility_mode',
            field=models.CharField(choices=[('internal_only', 'Internal Only'), ('shared_with_client', 'Shared with Client'), ('private', 'Private')], default='internal_only', max_length=30),
        ),
        migrations.AddField(
            model_name='candidate',
            name='priority_level',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], db_index=True, default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='candidate',
            name='profile_completeness',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='candidate',
            name='readiness_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='source_subtype',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='candidate',
            name='source_type',
            field=models.CharField(blank=True, choices=[('direct', 'Direct'), ('agency', 'Agency'), ('referral', 'Referral'), ('job_board', 'Job Board'), ('passport', 'Passport'), ('import', 'Import'), ('internal', 'Internal'), ('other', 'Other')], max_length=50),
        ),
        migrations.AddField(
            model_name='candidate',
            name='workflow_mode',
            field=models.CharField(choices=[('manual', 'Manual'), ('semi_automated', 'Semi Automated'), ('fully_automated', 'Fully Automated')], db_index=True, default='manual', max_length=30),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='initial_entry_type',
            field=models.CharField(blank=True, choices=[('self', 'Self Registered'), ('invite', 'Invite Link'), ('manual', 'Manual Add'), ('passport_import', 'Passport Import'), ('agency_submission', 'Agency Submission'), ('quick_add', 'Quick Add'), ('detailed_add', 'Detailed Add'), ('invite_candidate', 'Invite Candidate'), ('import_passport', 'Import Passport'), ('upload_resume', 'Upload Resume'), ('agency_submit', 'Agency Submit')], max_length=20),
        ),
        migrations.AlterField(
            model_name='candidateengagement',
            name='stage',
            field=models.CharField(choices=[('new_lead', 'New Lead'), ('contacted', 'Contacted'), ('follow_up', 'Follow Up'), ('qualified', 'Qualified'), ('interested', 'Interested'), ('sourced_for_job', 'Sourced for Job'), ('submitted', 'Submitted to Client'), ('interviewing', 'Interviewing'), ('offered', 'Offered'), ('closed_or_nurture', 'Closed / Nurture'), ('new', 'New (Legacy)'), ('not_interested', 'Not Interested (Legacy)'), ('shortlisted', 'Shortlisted Internally (Legacy)'), ('client_review', 'Client Review (Legacy)'), ('placed', 'Placed'), ('closed', 'Closed'), ('lost', 'Lost'), ('revived', 'Revived')], default='new_lead', max_length=50),
        ),
        migrations.CreateModel(
            name='CandidateWorkflowPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('team_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('recruiter_user_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('default_candidate_workflow_mode', models.CharField(choices=[('manual', 'Manual'), ('semi_automated', 'Semi Automated'), ('fully_automated', 'Fully Automated')], default='manual', max_length=30)),
                ('candidate_auto_assignment_mode', models.CharField(choices=[('manual', 'Manual'), ('round_robin', 'Round Robin'), ('rule_based', 'Rule Based')], default='manual', max_length=30)),
                ('candidate_auto_followup_mode', models.CharField(choices=[('manual', 'Manual'), ('suggest_only', 'Suggest Only'), ('automatic', 'Automatic')], default='suggest_only', max_length=30)),
                ('candidate_auto_nurture_days', models.PositiveIntegerField(default=30)),
                ('candidate_stale_days', models.PositiveIntegerField(default=21)),
                ('candidate_focus_rules', models.JSONField(blank=True, default=dict)),
                ('candidate_stage_templates', models.JSONField(blank=True, default=list)),
                ('candidate_required_fields_policy', models.JSONField(blank=True, default=dict)),
                ('candidate_scoring_policy', models.JSONField(blank=True, default=dict)),
                ('candidate_active_work_policy', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'candidate_workflow_policies',
                'indexes': [models.Index(fields=['tenant_id', 'team_id'], name='candidate_w_tenant__f3893f_idx'), models.Index(fields=['tenant_id', 'recruiter_user_id'], name='candidate_w_tenant__4166bf_idx'), models.Index(fields=['tenant_id', 'is_active'], name='candidate_w_tenant__d4031c_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('recruiter_user_id__isnull', True), ('team_id__isnull', True)), fields=('tenant_id',), name='uniq_candidate_policy_tenant_default'), models.UniqueConstraint(condition=models.Q(('recruiter_user_id__isnull', True), ('team_id__isnull', False)), fields=('tenant_id', 'team_id'), name='uniq_candidate_policy_team'), models.UniqueConstraint(condition=models.Q(('recruiter_user_id__isnull', False), ('team_id__isnull', True)), fields=('tenant_id', 'recruiter_user_id'), name='uniq_candidate_policy_recruiter')],
            },
        ),
    ]
