# Generated by Django 6.0.3 on 2026-03-25 19:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0012_alter_candidate_engagement_stage_and_more'),
        ('jobs', '0002_jobrequisition_auto_followup_after_source_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='candidateengagement',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_deleted', False), ('job__isnull', True)), fields=('tenant_id', 'candidate'), name='unique_active_general_engagement'),
        ),
    ]
