# Generated by Django 6.0.3 on 2026-03-26 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0016_alter_candidate_availability_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='availability_status',
            field=models.CharField(blank=True, choices=[('available_now', 'Available Now'), ('notice_period', 'Serving Notice Period'), ('open_to_offers', 'Open to Offers'), ('not_looking', 'Not Currently Looking')], max_length=50),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='highest_education',
            field=models.CharField(blank=True, choices=[('high_school', 'High School / Secondary'), ('diploma', 'Diploma / Certificate'), ('bachelor', "Bachelor's Degree"), ('master', "Master's Degree"), ('phd', 'PhD / Doctorate'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='work_authorization',
            field=models.CharField(blank=True, choices=[('citizen', 'Citizen / National'), ('permanent_resident', 'Permanent Resident'), ('work_visa', 'Work Visa / Work Permit'), ('sponsorship_required', 'Requires Sponsorship'), ('not_specified', 'Prefer not to say')], max_length=50),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='work_mode_preference',
            field=models.CharField(blank=True, choices=[('any', 'Open to Any'), ('remote', 'Remote Only'), ('hybrid', 'Hybrid'), ('onsite', 'On-site Only')], default='any', max_length=20),
        ),
    ]
