# Generated by Django 6.0.3 on 2026-04-04 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0020_candidateengagement_intent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatepipelinestatus',
            name='intent',
            field=models.CharField(choices=[('specific_job', 'For Specific Job'), ('future_jobs', 'For Future Jobs'), ('looking_for_job', 'Candidate Looking for Job'), ('just_lead', 'Just Lead / Not Sure')], default='just_lead', max_length=50),
        ),
        migrations.AlterField(
            model_name='candidatepipelinestatus',
            name='status',
            field=models.CharField(choices=[('new_lead', 'New Lead'), ('nurturing', 'Nurturing'), ('qualified', 'Qualified'), ('ready_to_submit', 'Ready to Submit'), ('submitted', 'Submitted'), ('placed', 'Placed'), ('lost', 'Lost')], default='new_lead', max_length=20),
        ),
    ]
