# Generated by Django 6.0.3 on 2026-04-05 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automation_recovery', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='workflowdeadletteritem',
            new_name='wf_dead_let_tenant__49e6db_idx',
            old_name='wf_dl_tenant_status_idx',
        ),
        migrations.RenameIndex(
            model_name='workflowdeadletteritem',
            new_name='wf_dead_let_tenant__5ca18b_idx',
            old_name='wf_dl_tenant_wf_idx',
        ),
        migrations.RenameIndex(
            model_name='workflowfallbackrule',
            new_name='wf_fallback_tenant__208d7c_idx',
            old_name='wf_fb_tenant_wf_node_idx',
        ),
        migrations.RenameIndex(
            model_name='workflowfallbackrule',
            new_name='wf_fallback_tenant__59bbbe_idx',
            old_name='wf_fb_tenant_active_idx',
        ),
        migrations.RenameIndex(
            model_name='workflowrecoveryattempt',
            new_name='wf_recovery_tenant__0f1623_idx',
            old_name='wf_rec_att_tenant_case_idx',
        ),
        migrations.RenameIndex(
            model_name='workflowrecoverycase',
            new_name='wf_recovery_tenant__6941cb_idx',
            old_name='wf_rec_case_tenant_status_idx',
        ),
        migrations.RenameIndex(
            model_name='workflowrecoverycase',
            new_name='wf_recovery_tenant__cca9dd_idx',
            old_name='wf_rec_case_tenant_wf_idx',
        ),
        migrations.RenameIndex(
            model_name='workflowrecoverycase',
            new_name='wf_recovery_tenant__d48eca_idx',
            old_name='wf_rec_case_tenant_exec_idx',
        ),
        migrations.RenameIndex(
            model_name='workflowrecoveryinsight',
            new_name='wf_recovery_tenant__3101f7_idx',
            old_name='wf_ins_tenant_status_idx',
        ),
        migrations.RenameIndex(
            model_name='workflowrecoveryinsight',
            new_name='wf_recovery_tenant__34a4e6_idx',
            old_name='wf_ins_tenant_type_idx',
        ),
    ]
