# Generated by Django 6.0.3 on 2026-03-20 11:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('requirements', models.TextField(blank=True)),
                ('responsibilities', models.TextField(blank=True)),
                ('job_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract'), ('internship', 'Internship'), ('freelance', 'Freelance')], default='full_time', max_length=50)),
                ('work_mode', models.CharField(choices=[('onsite', 'Onsite'), ('remote', 'Remote'), ('hybrid', 'Hybrid')], default='onsite', max_length=50)),
                ('experience_min', models.IntegerField(default=0)),
                ('experience_max', models.IntegerField(blank=True, null=True)),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('salary_currency', models.CharField(default='INR', max_length=10)),
                ('salary_visible', models.BooleanField(default=False)),
                ('headcount', models.IntegerField(default=1)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('is_confidential', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('active', 'Active'), ('paused', 'Paused'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='draft', max_length=50)),
                ('skills_required', models.JSONField(blank=True, default=list)),
                ('department_id', models.UUIDField(blank=True, null=True)),
                ('location_id', models.UUIDField(blank=True, null=True)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('closed_reason', models.CharField(blank=True, max_length=255)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.UUIDField(blank=True, null=True)),
                ('budget_code', models.CharField(blank=True, max_length=100)),
                ('product', models.CharField(choices=[('ats', 'ATS'), ('cafe', 'Cafe'), ('marketplace', 'Marketplace')], default='ats', max_length=20)),
            ],
            options={
                'db_table': 'jobs_job',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobStage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('job_id', models.UUIDField(db_index=True)),
                ('name', models.CharField(max_length=100)),
                ('stage_order', models.IntegerField(default=0)),
                ('stage_type', models.CharField(choices=[('sourcing', 'Sourcing'), ('screening', 'Screening'), ('interview', 'Interview'), ('assessment', 'Assessment'), ('offer', 'Offer'), ('joined', 'Joined'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='screening', max_length=50)),
                ('action_deadline_hours', models.IntegerField(default=48)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'jobs_stage',
                'ordering': ['stage_order'],
            },
        ),
        migrations.CreateModel(
            name='CustomFieldDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('entity_type', models.CharField(choices=[('job', 'Job'), ('candidate', 'Candidate'), ('application', 'Application'), ('organisation', 'Organisation'), ('interview', 'Interview')], max_length=50)),
                ('field_name', models.CharField(max_length=100)),
                ('field_label', models.CharField(max_length=255)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('boolean', 'Boolean'), ('date', 'Date'), ('dropdown', 'Dropdown'), ('multiselect', 'Multiselect'), ('url', 'URL'), ('email', 'Email')], max_length=20)),
                ('field_options', models.JSONField(blank=True, default=list)),
                ('is_required', models.BooleanField(default=False)),
                ('is_visible', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('placeholder', models.CharField(blank=True, max_length=255)),
                ('help_text', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'db_table': 'custom_field_definitions',
                'unique_together': {('tenant_id', 'entity_type', 'field_name')},
            },
        ),
        migrations.CreateModel(
            name='CustomFieldValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('entity_type', models.CharField(max_length=50)),
                ('entity_id', models.UUIDField(db_index=True)),
                ('field_name', models.CharField(max_length=100)),
                ('field_value', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'custom_field_values',
                'unique_together': {('tenant_id', 'entity_type', 'entity_id', 'field_name')},
            },
        ),
    ]
