# Generated by Django 6.0.3 on 2026-03-26 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_jobrequisition_auto_followup_after_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrequisition',
            name='guarantee_watch_until',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='hiring_status',
            field=models.CharField(choices=[('active_hiring', 'Active Hiring'), ('hiring_complete', 'Hiring Complete'), ('in_guarantee_period', 'In Guarantee Period'), ('replacement_required', 'Replacement Required'), ('fully_closed', 'Fully Closed')], db_index=True, default='active_hiring', max_length=40),
        ),
        migrations.AlterField(
            model_name='jobrequisition',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('active', 'Active'), ('paused', 'Paused'), ('in_guarantee_period', 'In Guarantee Period'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='draft', max_length=50),
        ),
    ]
