# Generated by Django 6.0.3 on 2026-04-01 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_jobrequisition_hiring_manager_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='requirements',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='responsibilities',
            field=models.TextField(blank=True),
        ),
    ]
