# Generated by Django 6.0.3 on 2026-04-01 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_jobposting_requirements_jobposting_responsibilities'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='skills_required',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
