# Generated by Django 6.0.3 on 2026-04-01 17:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_jobposting_skills_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrequisition',
            name='backup_recruiter_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='coordinator_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='job_owner_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.CreateModel(
            name='JobHiringTeamMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('user_id', models.UUIDField(db_index=True)),
                ('role', models.CharField(choices=[('interviewer', 'Interviewer'), ('approver', 'Approver'), ('stakeholder', 'Stakeholder/Viewer'), ('coordinator', 'Coordinator'), ('recruiter', 'Recruiter'), ('hiring_manager', 'Hiring Manager')], default='interviewer', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hiring_team', to='jobs.jobrequisition')),
            ],
            options={
                'db_table': 'jobs_hiring_team_member',
                'unique_together': {('requisition', 'user_id', 'role')},
            },
        ),
    ]
