# Generated by Django 6.0.3 on 2026-04-01 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_jobrequisition_agency_submission_governance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobstage',
            name='is_critical_path',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='jobstage',
            name='is_mandatory',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobstage',
            name='movement_restriction',
            field=models.CharField(choices=[('open', 'Open'), ('job_owner_only', 'Job Owner Only'), ('recruiter_only', 'Recruiter Only'), ('automation_only', 'Automation Only')], default='open', max_length=30),
        ),
        migrations.AddField(
            model_name='jobstage',
            name='sla_target_hours',
            field=models.IntegerField(default=24),
        ),
        migrations.AddField(
            model_name='jobstage',
            name='stage_zone',
            field=models.CharField(choices=[('pre_submission', 'Pre-Submission'), ('submitted', 'Submitted'), ('hiring_flow', 'Hiring Flow'), ('closed', 'Closed')], default='hiring_flow', max_length=50),
        ),
    ]
