# Generated by Django 6.0.3 on 2026-04-01 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_jobrequisition_agency_distribution_policy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrequisition',
            name='agency_commission_fixed_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='agency_commission_model',
            field=models.CharField(choices=[('percentage', 'Percentage of Salary'), ('fixed', 'Fixed Fee'), ('inherited', 'Inherited from Agency Relationship')], default='inherited', max_length=30),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='agency_commission_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='agency_payment_terms_days',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='auto_close_on_fulfillment',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='offer_currency_default',
            field=models.CharField(default='INR', max_length=10),
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='offer_salary_default',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
