# Generated by Django 6.0.3 on 2026-04-05 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0021_jobstage_decision_authority'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                DO $$
                BEGIN
                    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='jobs_requisition' AND column_name='auto_close_on_fulfillment') THEN
                        ALTER TABLE jobs_requisition RENAME COLUMN auto_close_on_fulfillment TO auto_close_on_headcount_met;
                    END IF;
                END $$;
                ALTER TABLE jobs_requisition DROP COLUMN IF EXISTS auto_assign_agencies;
                ALTER TABLE jobs_requisition DROP COLUMN IF EXISTS auto_publish_enabled;
                ALTER TABLE jobs_requisition DROP COLUMN IF EXISTS onboarding_automation_enabled;
                ALTER TABLE jobs_requisition ADD COLUMN IF NOT EXISTS hiring_complete_action varchar(50) NOT NULL DEFAULT 'auto_onboarding';
            """,
            reverse_sql="""
                DO $$
                BEGIN
                    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='jobs_requisition' AND column_name='auto_close_on_headcount_met') THEN
                        ALTER TABLE jobs_requisition RENAME COLUMN auto_close_on_headcount_met TO auto_close_on_fulfillment;
                    END IF;
                END $$;
                ALTER TABLE jobs_requisition ADD COLUMN IF NOT EXISTS auto_assign_agencies boolean NOT NULL DEFAULT false;
                ALTER TABLE jobs_requisition ADD COLUMN IF NOT EXISTS auto_publish_enabled boolean NOT NULL DEFAULT false;
                ALTER TABLE jobs_requisition ADD COLUMN IF NOT EXISTS onboarding_automation_enabled boolean NOT NULL DEFAULT false;
                ALTER TABLE jobs_requisition DROP COLUMN IF EXISTS hiring_complete_action;
            """,
            state_operations=[
                migrations.RenameField(
                    model_name='jobrequisition',
                    old_name='auto_close_on_fulfillment',
                    new_name='auto_close_on_headcount_met',
                ),
                migrations.RemoveField(
                    model_name='jobrequisition',
                    name='auto_assign_agencies',
                ),
                migrations.RemoveField(
                    model_name='jobrequisition',
                    name='auto_publish_enabled',
                ),
                migrations.RemoveField(
                    model_name='jobrequisition',
                    name='onboarding_automation_enabled',
                ),
                migrations.AddField(
                    model_name='jobrequisition',
                    name='hiring_complete_action',
                    field=models.CharField(choices=[('manual', 'Manual Only'), ('auto_onboarding', 'Trigger Onboarding Flow'), ('archive', 'Archive Application')], default='auto_onboarding', max_length=50),
                ),
            ],
        ),
    ]
