# Generated by Django 6.0.3 on 2026-05-01 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0022_rename_auto_close_on_fulfillment_jobrequisition_auto_close_on_headcount_met_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobstage',
            name='stage_type',
            field=models.CharField(choices=[('sourcing', 'Sourcing'), ('shortlisted', 'Shortlisted'), ('screening', 'Screening'), ('interview', 'Interview'), ('assessment', 'Assessment'), ('offer', 'Offer'), ('joined', 'Joined'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='screening', max_length=50),
        ),
    ]
