# Generated by Django 6.0.3 on 2026-05-08 16:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0025_remove_jobstage_responsible_user_id_and_more'),
        ('organisations', '0005_organisation_primary_currency_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='jobhiringteammember',
            unique_together={('requisition', 'user', 'role')},
        ),
        migrations.AlterUniqueTogether(
            name='joblocation',
            unique_together={('requisition', 'location')},
        ),
    ]
