SYSTEM_EMAIL_PURPOSES = {
    'otp',
    'email_verification',
    'password_reset',
    'security_alert',
    'invite_acceptance_link',
    'platform_notification',
    'reminder',
    'automation_alert',
    'escalation_alert',
}

BUSINESS_EMAIL_PURPOSES = {
    'recruiter_outreach',
    'candidate_follow_up',
    'interview_invite',
    'interview_reschedule',
    'interview_reminder',
    'candidate_rejection',
    'shortlist_notification',
    'offer_letter',
    'offer_follow_up',
    'agency_submission_update',
    'company_agency_message',
    'document_request',
    'profile_completion_request',
    'followup',
    'outreach',
}

DEFAULT_SYSTEM_TEMPLATE_DEFINITIONS = [
    ('OTP', 'otp', 'security', 'Your TalentOS verification code'),
    ('Email verification', 'email_verification', 'security', 'Verify your email'),
    ('Password reset', 'password_reset', 'security', 'Reset your password'),
    ('User invitation', 'user_invitation', 'invites', 'You are invited to TalentOS'),
    ('Agency invitation', 'agency_invitation', 'invites', 'Agency collaboration invitation'),
    ('Reminder notification', 'reminder_notification', 'reminders', 'Reminder from TalentOS'),
    ('Escalation alert', 'escalation_alert', 'alerts', 'Escalation alert'),
    ('Security alert', 'security_alert', 'alerts', 'Security alert'),
    ('Welcome email', 'welcome_email', 'onboarding', 'Welcome to TalentOS'),
    ('Platform onboarding reminder', 'platform_onboarding_reminder', 'onboarding', 'Complete your setup'),
    ('Pending action reminder', 'pending_action_reminder', 'reminders', 'Pending action reminder'),
    ('Account connection success/failure notification', 'account_connection_notification', 'accounts', 'Email account connection update'),
]

DEFAULT_BUSINESS_TEMPLATE_DEFINITIONS = [
    ('Candidate outreach intro', 'candidate_outreach_intro', 'candidate_communication'),
    ('Candidate follow-up', 'candidate_followup', 'candidate_communication'),
    ('Profile completion request', 'profile_completion_request', 'candidate_communication'),
    ('Resume request', 'resume_request', 'candidate_communication'),
    ('Interview invite', 'interview_invite', 'interview'),
    ('Interview reminder', 'interview_reminder', 'interview'),
    ('Interview reschedule', 'interview_reschedule', 'interview'),
    ('Interview cancellation', 'interview_cancellation', 'interview'),
    ('Shortlist notification', 'shortlist_notification', 'pipeline'),
    ('Rejection email polite', 'rejection_polite', 'pipeline'),
    ('Rejection email after interview', 'rejection_after_interview', 'pipeline'),
    ('Offer letter email', 'offer_letter_email', 'offer'),
    ('Offer follow-up', 'offer_follow_up', 'offer'),
    ('Document collection request', 'document_collection_request', 'documentation'),
    ('Joining reminder', 'joining_reminder', 'offer'),
    ('Agency introduction', 'agency_introduction', 'agency'),
    ('Company to agency requirement share', 'company_to_agency_requirement_share', 'agency'),
    ('Agency candidate submission acknowledgement', 'agency_candidate_submission_ack', 'agency'),
    ('Agency follow-up on submission', 'agency_followup_submission', 'agency'),
    ('Client feedback request', 'client_feedback_request', 'agency'),
    ('Interview feedback reminder', 'interview_feedback_reminder', 'interview'),
    ('General thank you', 'general_thank_you', 'general'),
    ('Keep in touch / talent pool', 'keep_in_touch_talent_pool', 'talent_pool'),
    ('Quick screening request', 'quick_screening_request', 'candidate_communication'),
    ('Availability check', 'availability_check', 'candidate_communication'),
    ('Salary expectation request', 'salary_expectation_request', 'candidate_communication'),
    ('Reference request', 'reference_request', 'candidate_communication'),
    ('Missing information request', 'missing_information_request', 'candidate_communication'),
]

DEFAULT_QUICK_REPLIES = [
    ('Thanks, we will review and revert.', 'general'),
    ('Please share updated CV.', 'candidate_communication'),
    ('Are you available tomorrow?', 'scheduling'),
    ('Your interview is confirmed.', 'interview'),
    ('We need one more document.', 'documentation'),
    ('Client feedback is pending.', 'agency'),
    ('Please confirm salary expectations.', 'offer'),
    ('We would like to move forward.', 'pipeline'),
    ('This role is on hold.', 'pipeline'),
    ('Thank you for your time.', 'general'),
]
