"""
Default notification rules seeded for every tenant on first access.
These represent the platform's out-of-the-box behaviour.

Structure per rule:
    event_key           str   – matches notification_type in Notification model
    business_label      str   – shown to admin users
    category            str   – NotificationRuleCategory value
    priority            str   – info / medium / high / critical
    in_app_enabled      bool
    email_enabled       bool
    fallback_enabled    bool
    fallback_delay_minutes  int
    escalation_enabled  bool
    escalation_delay_minutes int
    escalation_target_type   str
    admin_notes         str   – help text for admin UI
"""

DEFAULT_NOTIFICATION_RULES = [
    # ── Candidate ────────────────────────────────────────────────────────────
    {
        'event_key':    'passport_viewed',
        'business_label': 'Candidate passport viewed',
        'category':     'candidate',
        'priority':     'info',
        'in_app_enabled':  True,
        'email_enabled':   False,
        'fallback_enabled':         False,
        'fallback_delay_minutes':   0,
        'escalation_enabled':       False,
        'escalation_delay_minutes': 0,
        'escalation_target_type':   'tenant_admin',
        'admin_notes': 'Sent when someone views a candidate passport profile.',
    },

    # ── Application ──────────────────────────────────────────────────────────
    {
        'event_key':    'application_submitted',
        'business_label': 'Candidate submitted',
        'category':     'application',
        'priority':     'medium',
        'in_app_enabled':  True,
        'email_enabled':   True,
        'fallback_enabled':         True,
        'fallback_delay_minutes':   40,
        'escalation_enabled':       False,
        'escalation_delay_minutes': 0,
        'escalation_target_type':   'hiring_manager',
        'admin_notes': 'Triggered when a new application is received for a job.',
    },
    {
        'event_key':    'application_shortlisted',
        'business_label': 'Candidate shortlisted',
        'category':     'application',
        'priority':     'high',
        'in_app_enabled':  True,
        'email_enabled':   True,
        'fallback_enabled':         True,
        'fallback_delay_minutes':   10,
        'escalation_enabled':       True,
        'escalation_delay_minutes': 60,
        'escalation_target_type':   'hiring_manager',
        'admin_notes': 'Sent to relevant parties when a candidate is moved to shortlist.',
    },
    {
        'event_key':    'application_stage_changed',
        'business_label': 'Application stage changed',
        'category':     'application',
        'priority':     'info',
        'in_app_enabled':  True,
        'email_enabled':   False,
        'fallback_enabled':         False,
        'fallback_delay_minutes':   0,
        'escalation_enabled':       False,
        'escalation_delay_minutes': 0,
        'escalation_target_type':   'tenant_admin',
        'admin_notes': 'General pipeline stage change notification.',
    },
    {
        'event_key':    'application_rejected',
        'business_label': 'Application rejected',
        'category':     'application',
        'priority':     'medium',
        'in_app_enabled':  True,
        'email_enabled':   True,
        'fallback_enabled':         True,
        'fallback_delay_minutes':   40,
        'escalation_enabled':       False,
        'escalation_delay_minutes': 0,
        'escalation_target_type':   'recruiter_lead',
        'admin_notes': 'Sent when a candidate is rejected from the pipeline.',
    },

    # ── Interview ────────────────────────────────────────────────────────────
    {
        'event_key':    'interview_scheduled',
        'business_label': 'Interview scheduled',
        'category':     'interview',
        'priority':     'high',
        'in_app_enabled':  True,
        'email_enabled':   True,
        'fallback_enabled':         True,
        'fallback_delay_minutes':   10,
        'escalation_enabled':       True,
        'escalation_delay_minutes': 60,
        'escalation_target_type':   'hiring_manager',
        'admin_notes': 'Sent to interviewer and candidate when an interview is booked.',
    },
    {
        'event_key':    'interview_rescheduled',
        'business_label': 'Interview rescheduled',
        'category':     'interview',
        'priority':     'high',
        'in_app_enabled':  True,
        'email_enabled':   True,
        'fallback_enabled':         True,
        'fallback_delay_minutes':   10,
        'escalation_enabled':       False,
        'escalation_delay_minutes': 0,
        'escalation_target_type':   'hiring_manager',
        'admin_notes': 'Sent when an existing interview is moved to a new time.',
    },
    {
        'event_key':    'interview_cancelled',
        'business_label': 'Interview cancelled',
        'category':     'interview',
        'priority':     'high',
        'in_app_enabled':  True,
        'email_enabled':   True,
        'fallback_enabled':         True,
        'fallback_delay_minutes':   10,
        'escalation_enabled':       False,
        'escalation_delay_minutes': 0,
        'escalation_target_type':   'recruiter_lead',
        'admin_notes': 'Sent when an interview is cancelled.',
    },
    {
        'event_key':    'interview_completed',
        'business_label': 'Interview completed',
        'category':     'interview',
        'priority':     'medium',
        'in_app_enabled':  True,
        'email_enabled':   False,
        'fallback_enabled':         True,
        'fallback_delay_minutes':   40,
        'escalation_enabled':       False,
        'escalation_delay_minutes': 0,
        'escalation_target_type':   'recruiter_lead',
        'admin_notes': 'Sent after an interview is marked complete.',
    },
    {
        'event_key':    'interview_feedback_pending',
        'business_label': 'Interview feedback overdue',
        'category':     'interview',
        'priority':     'high',
        'in_app_enabled':  True,
        'email_enabled':   True,
        'fallback_enabled':         True,
        'fallback_delay_minutes':   10,
        'escalation_enabled':       True,
        'escalation_delay_minutes': 60,
        'escalation_target_type':   'recruiter_lead',
        'admin_notes': 'Reminder when post-interview feedback has not been submitted.',
    },

    # ── Offer ────────────────────────────────────────────────────────────────
    {
        'event_key':    'offer_sent',
        'business_label': 'Offer sent',
        'category':     'offer',
        'priority':     'high',
        'in_app_enabled':  True,
        'email_enabled':   True,
        'fallback_enabled':         True,
        'fallback_delay_minutes':   10,
        'escalation_enabled':       True,
        'escalation_delay_minutes': 60,
        'escalation_target_type':   'hiring_manager',
        'admin_notes': 'Sent when a formal offer is issued to a candidate.',
    },
    {
        'event_key':    'offer_accepted',
        'business_label': 'Offer accepted',
        'category':     'offer',
        'priority':     'high',
        'in_app_enabled':  True,
        'email_enabled':   True,
        'fallback_enabled':         True,
        'fallback_delay_minutes':   10,
        'escalation_enabled':       False,
        'escalation_delay_minutes': 0,
        'escalation_target_type':   'hiring_manager',
        'admin_notes': 'Sent when a candidate accepts an offer.',
    },
    {
        'event_key':    'offer_declined',
        'business_label': 'Offer declined',
        'category':     'offer',
        'priority':     'high',
        'in_app_enabled':  True,
        'email_enabled':   True,
        'fallback_enabled':         True,
        'fallback_delay_minutes':   10,
        'escalation_enabled':       True,
        'escalation_delay_minutes': 60,
        'escalation_target_type':   'hiring_manager',
        'admin_notes': 'Sent when a candidate declines an offer. Escalates for re-engagement.',
    },

    # ── Approval ─────────────────────────────────────────────────────────────
    {
        'event_key':    'approval_requested',
        'business_label': 'Approval requested',
        'category':     'approval',
        'priority':     'high',
        'in_app_enabled':  True,
        'email_enabled':   True,
        'fallback_enabled':         True,
        'fallback_delay_minutes':   10,
        'escalation_enabled':       True,
        'escalation_delay_minutes': 60,
        'escalation_target_type':   'tenant_admin',
        'admin_notes': 'Sent when an approval step is awaiting a decision.',
    },
    {
        'event_key':    'approval_overdue',
        'business_label': 'Approval overdue',
        'category':     'approval',
        'priority':     'critical',
        'in_app_enabled':  True,
        'email_enabled':   True,
        'fallback_enabled':         True,
        'fallback_delay_minutes':   1,
        'escalation_enabled':       True,
        'escalation_delay_minutes': 5,
        'escalation_target_type':   'tenant_admin',
        'admin_notes': 'Urgent: an approval is past its deadline.',
    },

    # ── Agency ───────────────────────────────────────────────────────────────
    {
        'event_key':    'agency_candidate_submitted',
        'business_label': 'Agency candidate submitted',
        'category':     'agency',
        'priority':     'medium',
        'in_app_enabled':  True,
        'email_enabled':   True,
        'fallback_enabled':         True,
        'fallback_delay_minutes':   40,
        'escalation_enabled':       False,
        'escalation_delay_minutes': 0,
        'escalation_target_type':   'recruiter_lead',
        'admin_notes': 'Sent when an agency submits a candidate for a job.',
    },
    {
        'event_key':    'agency_no_response',
        'business_label': 'Agency no response (SLA breach)',
        'category':     'agency',
        'priority':     'high',
        'in_app_enabled':  True,
        'email_enabled':   True,
        'fallback_enabled':         True,
        'fallback_delay_minutes':   10,
        'escalation_enabled':       True,
        'escalation_delay_minutes': 60,
        'escalation_target_type':   'recruiter_lead',
        'admin_notes': 'Triggered when an agency breaches a response SLA.',
    },

    # ── Messaging ────────────────────────────────────────────────────────────
    {
        'event_key':    'message.created',
        'business_label': 'New message received',
        'category':     'messaging',
        'priority':     'medium',
        'in_app_enabled':  True,
        'email_enabled':   False,
        'fallback_enabled':         True,
        'fallback_delay_minutes':   40,
        'escalation_enabled':       False,
        'escalation_delay_minutes': 0,
        'escalation_target_type':   'tenant_admin',
        'admin_notes': 'Sent when a new in-app message is received.',
    },
    {
        'event_key':    'message.high_priority',
        'business_label': 'High-priority message received',
        'category':     'messaging',
        'priority':     'high',
        'in_app_enabled':  True,
        'email_enabled':   True,
        'fallback_enabled':         True,
        'fallback_delay_minutes':   10,
        'escalation_enabled':       False,
        'escalation_delay_minutes': 0,
        'escalation_target_type':   'tenant_admin',
        'admin_notes': 'Sent for messages flagged as high priority.',
    },

    # ── Deadline / SLA ───────────────────────────────────────────────────────
    {
        'event_key':    'deadline_reminder',
        'business_label': 'Deadline reminder',
        'category':     'deadline',
        'priority':     'medium',
        'in_app_enabled':  True,
        'email_enabled':   False,
        'fallback_enabled':         True,
        'fallback_delay_minutes':   40,
        'escalation_enabled':       False,
        'escalation_delay_minutes': 0,
        'escalation_target_type':   'tenant_admin',
        'admin_notes': 'Proactive reminder before a deadline hits.',
    },
    {
        'event_key':    'deadline_overdue',
        'business_label': 'Deadline overdue',
        'category':     'deadline',
        'priority':     'critical',
        'in_app_enabled':  True,
        'email_enabled':   True,
        'fallback_enabled':         True,
        'fallback_delay_minutes':   1,
        'escalation_enabled':       True,
        'escalation_delay_minutes': 5,
        'escalation_target_type':   'tenant_admin',
        'admin_notes': 'Urgent: a tracked deadline has passed with no action taken.',
    },
]
