# Generated by Django 6.0.3 on 2026-04-03 11:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemIntelligenceMemory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('category', models.CharField(db_index=True, max_length=64)),
                ('entity_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('entity_name', models.CharField(blank=True, max_length=255)),
                ('attribute_key', models.CharField(db_index=True, max_length=64)),
                ('attribute_value', models.JSONField(default=dict)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('learned_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Intelligence Memory',
                'verbose_name_plural': 'System Intelligence Memories',
                'db_table': 'icc_system_intelligence_memory',
                'ordering': ['-learned_at'],
            },
        ),
    ]
