# Generated by Django 6.0.3 on 2026-04-05 12:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executive_automation', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='executiveautomationdepartment',
            new_name='exec_automa_tenant__24318f_idx',
            old_name='exec_dept_tenant_date_idx',
        ),
        migrations.RenameIndex(
            model_name='executiveautomationdepartment',
            new_name='exec_automa_tenant__9552f0_idx',
            old_name='exec_dept_tenant_name_idx',
        ),
        migrations.RenameIndex(
            model_name='executiveautomationopportunity',
            new_name='exec_automa_tenant__db6ed6_idx',
            old_name='exec_opp_tenant_status_idx',
        ),
        migrations.RenameIndex(
            model_name='executiveautomationopportunity',
            new_name='exec_automa_tenant__56ad5a_idx',
            old_name='exec_opp_tenant_priority_idx',
        ),
        migrations.RenameIndex(
            model_name='executiveautomationopportunity',
            new_name='exec_automa_tenant__125037_idx',
            old_name='exec_opp_tenant_type_idx',
        ),
        migrations.RenameIndex(
            model_name='executiveautomationrisk',
            new_name='exec_automa_tenant__367dca_idx',
            old_name='exec_risk_tenant_status_idx',
        ),
        migrations.RenameIndex(
            model_name='executiveautomationrisk',
            new_name='exec_automa_tenant__1f7290_idx',
            old_name='exec_risk_tenant_severity_idx',
        ),
        migrations.RenameIndex(
            model_name='executiveautomationrisk',
            new_name='exec_automa_tenant__5902cf_idx',
            old_name='exec_risk_tenant_type_idx',
        ),
        migrations.RenameIndex(
            model_name='executiveautomationroi',
            new_name='exec_automa_tenant__85f15d_idx',
            old_name='exec_roi_tenant_period_idx',
        ),
        migrations.RenameIndex(
            model_name='executiveautomationsummary',
            new_name='exec_automa_tenant__75e826_idx',
            old_name='exec_sum_tenant_date_idx',
        ),
        migrations.AddField(
            model_name='executiveautomationdepartment',
            name='created_by',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='executiveautomationopportunity',
            name='created_by',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='executiveautomationrisk',
            name='created_by',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='executiveautomationroi',
            name='created_by',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='executiveautomationsummary',
            name='created_by',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='executiveautomationdepartment',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='executiveautomationdepartment',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='executiveautomationdepartment',
            name='tenant_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='executiveautomationopportunity',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='executiveautomationopportunity',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='executiveautomationopportunity',
            name='opportunity_type',
            field=models.CharField(choices=[('automate_manual_process', 'Automate Manual Process'), ('expand_existing_workflow', 'Expand Existing Workflow'), ('enable_cross_module', 'Enable Cross-Module Automation'), ('improve_reliability', 'Improve Reliability'), ('enable_ai', 'Enable AI Automation')], max_length=40),
        ),
        migrations.AlterField(
            model_name='executiveautomationopportunity',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='executiveautomationopportunity',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('dismissed', 'Dismissed')], db_index=True, default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='executiveautomationopportunity',
            name='tenant_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='executiveautomationrisk',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='executiveautomationrisk',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='executiveautomationrisk',
            name='risk_type',
            field=models.CharField(choices=[('failure_spike', 'Failure Spike'), ('dependency_risk', 'Dependency Risk'), ('workflow_conflict', 'Workflow Conflict'), ('governance_gap', 'Governance Gap'), ('manual_gap', 'Manual Gap'), ('overload_risk', 'Overload Risk')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='executiveautomationrisk',
            name='severity',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='executiveautomationrisk',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('acknowledged', 'Acknowledged'), ('mitigated', 'Mitigated'), ('resolved', 'Resolved'), ('ignored', 'Ignored')], db_index=True, default='open', max_length=20),
        ),
        migrations.AlterField(
            model_name='executiveautomationrisk',
            name='tenant_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='executiveautomationroi',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='executiveautomationroi',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='executiveautomationroi',
            name='period',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=10),
        ),
        migrations.AlterField(
            model_name='executiveautomationroi',
            name='tenant_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='executiveautomationsummary',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='executiveautomationsummary',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='executiveautomationsummary',
            name='tenant_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
