# Generated by Django 6.0.3 on 2026-05-07 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_offerletter_refinements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerletter',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approval_pending', 'Approval Pending'), ('approved', 'Approved'), ('sent', 'Sent'), ('negotiation', 'Negotiation / Counter-Offer'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('withdrawn', 'Withdrawn'), ('revoked', 'Revoked')], default='draft', max_length=50),
        ),
    ]
