# Generated by Django 6.0.3 on 2026-04-08 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow_execution', '0010_workflownotificationrule_workflownotificationlog_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='workflownotificationlog',
            new_name='wf_exec_wfn_workflo_6429c1_idx',
            old_name='wf_exec_not_workflo_300e52_idx',
        ),
        migrations.RenameIndex(
            model_name='workflownotificationlog',
            new_name='wf_exec_wfn_channel_2fbd80_idx',
            old_name='wf_exec_not_channel_58fd01_idx',
        ),
        migrations.RenameIndex(
            model_name='workflownotificationqueue',
            new_name='wf_exec_wfn_status_494dbd_idx',
            old_name='wf_exec_not_status_6f4faf_idx',
        ),
        migrations.RenameIndex(
            model_name='workflownotificationqueue',
            new_name='wf_exec_wfn_workflo_1ae0d2_idx',
            old_name='wf_exec_not_workflo_ca59dd_idx',
        ),
        migrations.RenameIndex(
            model_name='workflownotificationrule',
            new_name='wf_exec_wfn_workflo_a1f320_idx',
            old_name='wf_exec_not_workflo_d2a4c8_idx',
        ),
        migrations.RenameIndex(
            model_name='workflownotificationrule',
            new_name='wf_exec_wfn_workflo_d44d66_idx',
            old_name='wf_exec_not_workflo_cbf91c_idx',
        ),
    ]
