# Generated by Django 6.0.3 on 2026-04-08 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_backfill_reference_ids'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=120, unique=True)),
                ('category', models.CharField(db_index=True, default='general', max_length=80)),
                ('value_json', models.JSONField(blank=True, default=dict)),
                ('description', models.TextField(blank=True)),
                ('is_editable', models.BooleanField(default=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tenants_platform_setting',
                'ordering': ['category', 'key'],
            },
        ),
    ]
