# Generated by Django 6.0.3 on 2026-04-01 12:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_registry', '0003_nextmodulecandidatescore_nextmoduledecisionaudit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedPrompt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('prompt_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('prompt_title', models.CharField(db_index=True, max_length=255)),
                ('prompt_scope', models.TextField()),
                ('prompt_dependencies', models.JSONField(blank=True, default=list)),
                ('prompt_status', models.CharField(choices=[('draft', 'Draft'), ('generated', 'Generated'), ('approved', 'Approved'), ('locked', 'Locked')], db_index=True, default='draft', max_length=20)),
                ('prompt_version', models.PositiveIntegerField(db_index=True, default=1)),
                ('generated_by', models.CharField(blank=True, max_length=120)),
                ('approved_by', models.CharField(blank=True, max_length=120)),
                ('prompt_body', models.TextField()),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_prompts', to='module_registry.moduleregistry')),
            ],
            options={
                'db_table': 'tos_generated_prompt',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromptContext',
            fields=[
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('module_key', models.CharField(db_index=True, max_length=120)),
                ('context_payload', models.JSONField(blank=True, default=dict)),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contexts', to='module_registry.generatedprompt')),
            ],
            options={
                'db_table': 'tos_prompt_context',
            },
        ),
        migrations.CreateModel(
            name='PromptDependency',
            fields=[
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notes', models.TextField(blank=True)),
                ('depends_on', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompt_dependents', to='module_registry.moduleregistry')),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies_map', to='module_registry.generatedprompt')),
            ],
            options={
                'db_table': 'tos_prompt_dependency',
            },
        ),
        migrations.CreateModel(
            name='PromptHistory',
            fields=[
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(db_index=True, max_length=120)),
                ('actor_name', models.CharField(blank=True, max_length=200)),
                ('event_payload', models.JSONField(blank=True, default=dict)),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='module_registry.generatedprompt')),
            ],
            options={
                'db_table': 'tos_prompt_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromptScope',
            fields=[
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope_type', models.CharField(db_index=True, max_length=120)),
                ('scope_payload', models.JSONField(blank=True, default=dict)),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scopes', to='module_registry.generatedprompt')),
            ],
            options={
                'db_table': 'tos_prompt_scope',
            },
        ),
        migrations.CreateModel(
            name='PromptVersion',
            fields=[
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prompt_version', models.PositiveIntegerField(db_index=True, default=1)),
                ('version_snapshot', models.JSONField(blank=True, default=dict)),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='module_registry.generatedprompt')),
            ],
            options={
                'db_table': 'tos_prompt_version',
                'ordering': ['-prompt_version'],
            },
        ),
    ]
