# Generated by Django 6.0.3 on 2026-03-28 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prequalification', '0002_prequal_scoring_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prequalquestion',
            name='question_type',
            field=models.CharField(choices=[('yes_no', 'Yes / No'), ('single_select', 'Single Choice'), ('multi_select', 'Multiple Choice'), ('short_text', 'Short Answer'), ('long_text', 'Paragraph'), ('number', 'Number'), ('dropdown', 'Dropdown'), ('date', 'Date'), ('file_upload', 'File Upload'), ('multiple_choice', 'Multiple Choice (legacy)'), ('text', 'Text (legacy)')], default='yes_no', max_length=50),
        ),
        migrations.AlterField(
            model_name='prequalrule',
            name='action_type',
            field=models.CharField(choices=[('reject', 'Auto Reject'), ('next_question', 'Continue to Next'), ('skip_section', 'Skip to Section'), ('manual_review', 'Flag for Manual Review'), ('show_question', 'Show Question'), ('hide_question', 'Hide Question'), ('route_to_outcome', 'Route to Outcome'), ('end_form', 'End Form')], default='next_question', max_length=50),
        ),
        migrations.AlterField(
            model_name='prequalrule',
            name='condition_type',
            field=models.CharField(choices=[('equals', 'Equals'), ('not_equals', 'Not Equals'), ('greater_than', 'Greater Than'), ('less_than', 'Less Than'), ('contains', 'Contains'), ('is_empty', 'Is Empty'), ('is_not_empty', 'Is Not Empty'), ('in', 'Is One Of'), ('not_in', 'Is Not One Of')], default='equals', max_length=50),
        ),
    ]
