# Generated by Django 6.0.3 on 2026-03-29 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prequalification', '0003_alter_prequalquestion_question_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prequalquestion',
            name='question_text',
            field=models.TextField(blank=True),
        ),
    ]
