# Generated by Django 6.0.3 on 2026-03-25 10:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('user_id', models.UUIDField(db_index=True)),
                ('email_address', models.EmailField(max_length=254)),
                ('provider', models.CharField(choices=[('gmail', 'Gmail'), ('outlook', 'Outlook'), ('smtp', 'Custom SMTP')], max_length=20)),
                ('is_default', models.BooleanField(default=False)),
                ('smtp_host', models.CharField(blank=True, max_length=255)),
                ('smtp_port', models.IntegerField(blank=True, null=True)),
                ('smtp_username', models.CharField(blank=True, max_length=255)),
                ('smtp_password', models.TextField(blank=True)),
                ('smtp_encryption', models.CharField(choices=[('none', 'None'), ('ssl', 'SSL'), ('tls', 'TLS')], default='tls', max_length=10)),
                ('from_name', models.CharField(blank=True, max_length=255)),
                ('signature', models.TextField(blank=True)),
                ('oauth_token_encrypted', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'communications_email_account',
                'unique_together': {('user_id', 'email_address')},
            },
        ),
    ]
