# Generated by Django 6.0.3 on 2026-05-07 19:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0012_analytics_indexes'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='notificationchannelsetting',
            name='unique_channel_setting_per_tenant',
        ),
        migrations.RemoveConstraint(
            model_name='notificationrule',
            name='unique_notification_rule_per_tenant',
        ),
        migrations.RemoveConstraint(
            model_name='threadparticipant',
            name='unique_thread_user_participant',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='comms_msg_thread_timeline_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='comms_msg_entity_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='comms_msg_sender_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='comms_msg_channel_type_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='comms_msg_type_sent_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='comms_msg_entity_sent_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='comms_msg_sender_workload_idx',
        ),
        migrations.RemoveIndex(
            model_name='messagethread',
            name='comms_thread_archive_idx',
        ),
        migrations.RemoveIndex(
            model_name='messagethread',
            name='comms_thread_purge_idx',
        ),
        migrations.RemoveIndex(
            model_name='messagethread',
            name='comms_thread_legal_hold_idx',
        ),
        migrations.RemoveIndex(
            model_name='messagethread',
            name='comms_thread_entity_filter_idx',
        ),
        migrations.RemoveIndex(
            model_name='messagethread',
            name='comms_thread_inbox_order_idx',
        ),
        migrations.RemoveIndex(
            model_name='messagethread',
            name='comms_thread_analytics_idx',
        ),
        migrations.RemoveIndex(
            model_name='messagethread',
            name='comms_thread_type_analytics_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='comms_notif_history_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='comms_notif_unread_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='comms_notif_entity_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='comms_notif_severity_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='comms_notif_type_analytics_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='comms_notif_severity_read_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='comms_notif_fallback_email_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='comms_notif_escalation_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='comms_notif_read_latency_idx',
        ),
        migrations.RemoveIndex(
            model_name='notificationdelivery',
            name='comms_nd_channel_analytics_idx',
        ),
        migrations.RemoveIndex(
            model_name='notificationescalationlog',
            name='comms_esclog_analytics_idx',
        ),
        migrations.RenameIndex(
            model_name='communicationdelivery',
            new_name='comms_commu_tenant__4c0e1b_idx',
            old_name='comms_delivery_tid_ch_stat',
        ),
        migrations.RenameIndex(
            model_name='communicationdelivery',
            new_name='comms_commu_tenant__0c76ad_idx',
            old_name='comms_delivery_tid_created',
        ),
        migrations.RenameIndex(
            model_name='communicationdelivery',
            new_name='comms_commu_notific_80190c_idx',
            old_name='comms_delivery_notif_ch',
        ),
        migrations.RenameIndex(
            model_name='communicationdelivery',
            new_name='comms_commu_tenant__7e0630_idx',
            old_name='comms_delivery_tid_user_ch',
        ),
        migrations.RenameIndex(
            model_name='communicationdelivery',
            new_name='comms_commu_automat_0864a7_idx',
            old_name='comms_delivery_job_id',
        ),
        migrations.RenameIndex(
            model_name='emaildelivery',
            new_name='comms_email_tenant__cb7d55_idx',
            old_name='comms_edel_tenant_status_idx',
        ),
        migrations.RenameIndex(
            model_name='emaildelivery',
            new_name='comms_email_tenant__99de32_idx',
            old_name='comms_edel_tenant_created_idx',
        ),
        migrations.RenameIndex(
            model_name='message',
            new_name='communicati_tenant__73202c_idx',
            old_name='comm_msg_tenant_sent_idx',
        ),
        migrations.RenameIndex(
            model_name='message',
            new_name='communicati_tenant__11fbfb_idx',
            old_name='comm_msg_tenant_system_idx',
        ),
        migrations.RenameIndex(
            model_name='messagethread',
            new_name='communicati_tenant__c7a300_idx',
            old_name='comm_thread_tenant_type_del_idx',
        ),
        migrations.RenameIndex(
            model_name='messagethread',
            new_name='communicati_tenant__3375b0_idx',
            old_name='comm_thread_entity_idx',
        ),
        migrations.RenameIndex(
            model_name='messagethread',
            new_name='communicati_tenant__6b759f_idx',
            old_name='comm_thread_tenant_last_msg_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='communicati_user_id_d1973f_idx',
            old_name='comm_notif_user_unread_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='communicati_tenant__1e7f35_idx',
            old_name='comm_notif_tenant_read_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='communicati_user_id_581b2b_idx',
            old_name='comm_notif_user_expiry_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='communicati_user_id_581b2b_idx',
            old_name='comms_notif_expiry_idx',
        ),
        migrations.RenameIndex(
            model_name='notificationautomationjob',
            new_name='comms_notif_tenant__feedff_idx',
            old_name='comms_naj_tenant_status_idx',
        ),
        migrations.RenameIndex(
            model_name='notificationautomationjob',
            new_name='comms_notif_notific_f9edb4_idx',
            old_name='comms_naj_notification_idx',
        ),
        migrations.RenameIndex(
            model_name='notificationautomationjob',
            new_name='comms_notif_tenant__188e50_idx',
            old_name='comms_naj_type_idx',
        ),
        migrations.RenameIndex(
            model_name='notificationautomationjob',
            new_name='comms_notif_related_19a905_idx',
            old_name='comms_naj_entity_idx',
        ),
        migrations.RenameIndex(
            model_name='notificationchannelsetting',
            new_name='comms_notif_tenant__25a07d_idx',
            old_name='nc_channel_tenant_idx',
        ),
        migrations.RenameIndex(
            model_name='notificationdelivery',
            new_name='communicati_notific_5b3ddf_idx',
            old_name='comm_delivery_notif_channel_idx',
        ),
        migrations.RenameIndex(
            model_name='notificationdelivery',
            new_name='communicati_tenant__9ae95a_idx',
            old_name='comm_delivery_tenant_status_idx',
        ),
        migrations.RenameIndex(
            model_name='notificationescalationlog',
            new_name='comms_notif_tenant__3ac347_idx',
            old_name='comms_nel_notification_idx',
        ),
        migrations.RenameIndex(
            model_name='notificationescalationlog',
            new_name='comms_notif_tenant__7ff7d4_idx',
            old_name='comms_nel_target_idx',
        ),
        migrations.RenameIndex(
            model_name='notificationrule',
            new_name='comms_notif_tenant__466547_idx',
            old_name='nc_rule_tenant_cat_idx',
        ),
        migrations.RenameIndex(
            model_name='notificationrule',
            new_name='comms_notif_tenant__946d32_idx',
            old_name='nc_rule_tenant_key_idx',
        ),
        migrations.RenameIndex(
            model_name='tenantchannelconfig',
            new_name='comms_tenan_tenant__38fb71_idx',
            old_name='comms_chcfg_tid_ch_active',
        ),
        migrations.RenameIndex(
            model_name='tenantchannelconfig',
            new_name='comms_tenan_tenant__0a258e_idx',
            old_name='comms_chcfg_tid_ch_del',
        ),
        migrations.RenameIndex(
            model_name='threadparticipant',
            new_name='communicati_tenant__1db70d_idx',
            old_name='comm_participant_user_idx',
        ),
        migrations.RenameIndex(
            model_name='threadparticipant',
            new_name='communicati_thread__e25710_idx',
            old_name='comm_participant_thread_user_idx',
        ),
        migrations.AlterField(
            model_name='communicationdelivery',
            name='channel_type',
            field=models.CharField(choices=[('in_app', 'In-App'), ('email', 'Email'), ('whatsapp', 'WhatsApp'), ('sms', 'SMS'), ('push', 'Push')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='communicationdelivery',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='communicationdelivery',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='communicationdelivery',
            name='recipient_identifier',
            field=models.CharField(blank=True, help_text='Normalised phone (E.164), push token, or user_id for push', max_length=255),
        ),
        migrations.AlterField(
            model_name='communicationdelivery',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed'), ('bounced', 'Bounced'), ('deferred', 'Deferred'), ('cancelled', 'Cancelled'), ('skipped', 'Skipped')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='message',
            name='body',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('system_event', 'System Event'), ('note', 'Note'), ('attachment', 'Attachment'), ('template_log', 'Template Generated'), ('file', 'File'), ('template', 'Template'), ('whatsapp', 'WhatsApp'), ('email', 'Email'), ('sms', 'SMS')], default='text', max_length=50),
        ),
        migrations.AlterField(
            model_name='message',
            name='sent_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='thread',
            field=models.ForeignKey(blank=True, db_column='thread_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='communications.messagethread'),
        ),
        migrations.AlterField(
            model_name='messagethread',
            name='last_message_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='messagethread',
            name='related_entity_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='messagethread',
            name='related_entity_type',
            field=models.CharField(blank=True, db_index=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='messagethread',
            name='thread_type',
            field=models.CharField(choices=[('internal', 'Internal'), ('company_agency', 'Company ↔ Agency'), ('recruiter_candidate', 'Recruiter ↔ Candidate'), ('company_candidate', 'Company ↔ Candidate'), ('agency_candidate', 'Agency ↔ Candidate'), ('interview_coordination', 'Interview Coordination'), ('submission_context', 'Submission / Application Context'), ('ai_chat', 'AI Assistant Chat'), ('broadcast', 'Broadcast / Announcement'), ('general', 'General')], db_index=True, default='general', max_length=40),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='notification',
            name='related_entity_type',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='notificationautomationjob',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='notificationautomationjob',
            name='job_type',
            field=models.CharField(choices=[('fallback_email', 'Fallback Email'), ('escalation', 'Escalation'), ('reminder', 'Reminder'), ('digest', 'Digest'), ('whatsapp_fallback', 'WhatsApp Fallback'), ('sms_escalation', 'SMS Escalation'), ('push_notification', 'Push Notification'), ('channel_delivery', 'Channel Delivery')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='notificationautomationjob',
            name='notification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='automation_jobs', to='communications.notification'),
        ),
        migrations.AlterField(
            model_name='notificationchannelsetting',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='notificationescalationlog',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='notificationescalationlog',
            name='notification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalation_logs', to='communications.notification'),
        ),
        migrations.AlterField(
            model_name='notificationrule',
            name='allow_user_override',
            field=models.BooleanField(default=True, help_text='Whether users can individually turn this notification off'),
        ),
        migrations.AlterField(
            model_name='notificationrule',
            name='business_label',
            field=models.CharField(help_text='Human-friendly label shown in admin UI', max_length=200),
        ),
        migrations.AlterField(
            model_name='notificationrule',
            name='escalation_delay_minutes',
            field=models.PositiveIntegerField(default=60, help_text='Minutes after fallback before escalation fires'),
        ),
        migrations.AlterField(
            model_name='notificationrule',
            name='escalation_target_type',
            field=models.CharField(choices=[('assigned_manager', "Assigned User's Manager"), ('hiring_manager', 'Hiring Manager'), ('recruiter_lead', 'Recruiter Lead'), ('tenant_admin', 'Tenant Admin')], default='tenant_admin', max_length=40),
        ),
        migrations.AlterField(
            model_name='notificationrule',
            name='event_key',
            field=models.CharField(db_index=True, help_text='Internal event key (e.g. application_shortlisted)', max_length=120),
        ),
        migrations.AlterField(
            model_name='notificationrule',
            name='fallback_delay_minutes',
            field=models.PositiveIntegerField(default=40, help_text='Minutes after creation before fallback email is sent'),
        ),
        migrations.AlterField(
            model_name='notificationrule',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='notificationrule',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='Locked rules cannot be edited'),
        ),
        migrations.AlterField(
            model_name='notificationrule',
            name='is_system',
            field=models.BooleanField(default=False, help_text='System rules cannot be deleted by tenants'),
        ),
        migrations.AlterField(
            model_name='notificationrule',
            name='template_id',
            field=models.UUIDField(blank=True, help_text='Linked email template UUID', null=True),
        ),
        migrations.AlterField(
            model_name='tenantchannelconfig',
            name='channel_type',
            field=models.CharField(choices=[('whatsapp', 'WhatsApp'), ('sms', 'SMS'), ('push', 'Push')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='tenantchannelconfig',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tenantchannelconfig',
            name='sender_identifier',
            field=models.CharField(blank=True, help_text='Phone number (E.164), sender ID, or push project ID', max_length=200),
        ),
        migrations.AlterField(
            model_name='tenantnotificationpreferencedefaults',
            name='allow_user_override',
            field=models.BooleanField(default=True, help_text='Allow users to change their own notification preferences'),
        ),
        migrations.AlterField(
            model_name='tenantnotificationpreferencedefaults',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='notificationchannelsetting',
            unique_together={('tenant_id', 'channel_type')},
        ),
        migrations.AlterUniqueTogether(
            name='notificationrule',
            unique_together={('tenant_id', 'event_key')},
        ),
        migrations.AlterUniqueTogether(
            name='threadparticipant',
            unique_together={('thread', 'user_id')},
        ),
        migrations.RemoveField(
            model_name='message',
            name='thread_id',
        ),
        migrations.RemoveField(
            model_name='message',
            name='thread_id_legacy',
        ),
    ]
