# Generated by Django 6.0.3 on 2026-03-22 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0002_remove_agencyperformancescore_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencyclientrelationship',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='agencyclientrelationship',
            name='contact_person_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='agencyclientrelationship',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='agencyclientrelationship',
            name='contract_file_url',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='agencyclientrelationship',
            name='industry',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='agencyclientrelationship',
            name='invited_by',
            field=models.CharField(blank=True, choices=[('company', 'Company'), ('agency', 'Agency')], max_length=10),
        ),
        migrations.AddField(
            model_name='agencyclientrelationship',
            name='invited_via',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='agencyclientrelationship',
            name='payment_terms',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='agencyclientrelationship',
            name='recruitment_policy_url',
            field=models.TextField(blank=True),
        ),
    ]
