# Generated by Django 6.0.3 on 2026-03-23 09:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0003_agencyclientrelationship_contact_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTrackingConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agency_tenant_id', models.UUIDField(db_index=True)),
                ('client_name', models.CharField(max_length=255)),
                ('email_domain', models.CharField(max_length=255)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_name', models.CharField(blank=True, max_length=255)),
                ('their_ats_url', models.CharField(blank=True, max_length=500)),
                ('receive_via_email', models.BooleanField(default=True)),
                ('receive_via_portal', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'agencies_email_tracking',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GuestPortal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('portal_type', models.CharField(choices=[('agency_guest', 'Agency Guest Portal'), ('client_guest', 'Client Guest Portal')], max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('contact_name', models.CharField(blank=True, max_length=255)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('created_by_tenant_id', models.UUIDField(db_index=True)),
                ('created_by_user_id', models.UUIDField(blank=True, null=True)),
                ('invite_token', models.CharField(blank=True, max_length=64, unique=True)),
                ('invite_sent_at', models.DateTimeField(blank=True, null=True)),
                ('invite_expires_at', models.DateTimeField(blank=True, null=True)),
                ('invite_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('invite_message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Invite Pending'), ('active', 'Active'), ('expired', 'Invite Expired'), ('upgraded', 'Upgraded to Full Tenant')], default='pending', max_length=20)),
                ('upgraded_tenant_id', models.UUIDField(blank=True, null=True)),
                ('upgraded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'agencies_guest_portal',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='agencyclientrelationship',
            name='connection_type',
            field=models.CharField(blank=True, choices=[('full_full', 'Both Full Tenants'), ('agency_guest', 'Agency on Guest Portal'), ('client_guest', 'Client on Guest Portal'), ('email_tracking', 'Email Tracking Only'), ('offline', 'Offline Client')], default='full_full', max_length=20),
        ),
        migrations.AddField(
            model_name='agencyclientrelationship',
            name='email_tracking_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agencyclientrelationship',
            name='guest_portal_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agencyclientrelationship',
            name='last_activity_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agencyclientrelationship',
            name='their_ats_url',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
