# Generated by Django 6.0.3 on 2026-05-08 19:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0003_agencyclientrelationship_contact_email_and_more'),
        ('organisations', '0005_organisation_primary_currency_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTrackingConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('client_name', models.CharField(max_length=255)),
                ('email_domain', models.CharField(max_length=255)),
                ('tracking_email', models.EmailField(max_length=254, unique=True)),
                ('forward_to_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'agencies_email_tracking',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GuestPortal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('portal_type', models.CharField(choices=[('agency_guest', 'Agency Guest'), ('client_guest', 'Client Guest')], max_length=50)),
                ('contact_email', models.EmailField(max_length=254)),
                ('invite_token', models.CharField(max_length=100, unique=True)),
                ('invite_expires_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('created_by_tenant_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'agencies_guest_portal',
            },
        ),
        migrations.RemoveField(
            model_name='agencyclientrelationship',
            name='contract_end_date',
        ),
        migrations.RemoveField(
            model_name='agencyclientrelationship',
            name='contract_start_date',
        ),
        migrations.RemoveField(
            model_name='agencyclientrelationship',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='agencyclientrelationship',
            name='tier',
        ),
        migrations.AddField(
            model_name='agencyclientrelationship',
            name='allocated_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocated_client_relationships', to='organisations.team'),
        ),
        migrations.AddField(
            model_name='agencyclientrelationship',
            name='allocated_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocated_client_relationships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agencyclientrelationship',
            name='auto_accept_jobs',
            field=models.BooleanField(default=False, help_text='Automatically accept job assignments from this client'),
        ),
        migrations.AddField(
            model_name='agencyclientrelationship',
            name='client_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='agencyclientrelationship',
            name='connection_type',
            field=models.CharField(blank=True, choices=[('full_full', 'Both Full Tenants'), ('agency_guest', 'Agency on Guest Portal'), ('client_guest', 'Client on Guest Portal'), ('email_tracking', 'Email Tracking Only'), ('offline', 'Offline Client')], default='full_full', max_length=20),
        ),
        migrations.AddField(
            model_name='agencyclientrelationship',
            name='contact_country_code',
            field=models.CharField(blank=True, default='IN', max_length=10),
        ),
        migrations.AddField(
            model_name='agencyclientrelationship',
            name='contact_phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='agencyclientrelationship',
            name='contract_snapshot',
            field=models.JSONField(blank=True, help_text='Snapshot of terms at the moment of acceptance', null=True),
        ),
        migrations.AddField(
            model_name='agencyclientrelationship',
            name='email_domain',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='agencyclientrelationship',
            name='email_tracking_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agencyclientrelationship',
            name='guarantee_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='agencyclientrelationship',
            name='guarantee_period_days',
            field=models.IntegerField(default=90, help_text='Replacement guarantee period'),
        ),
        migrations.AddField(
            model_name='agencyclientrelationship',
            name='guest_portal_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agencyclientrelationship',
            name='last_activity_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agencyclientrelationship',
            name='payment_schedule',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='agencyclientrelationship',
            name='refund_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='agencyclientrelationship',
            name='refund_type',
            field=models.CharField(blank=True, choices=[('full_refund', 'Full Refund'), ('partial_refund', 'Partial Refund'), ('pro_rated_refund', 'Pro-rated Refund')], max_length=50),
        ),
        migrations.AddField(
            model_name='agencyclientrelationship',
            name='replacement_attempt_limit',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('unlimited', 'Unlimited')], default='1', max_length=20),
        ),
        migrations.AddField(
            model_name='agencyclientrelationship',
            name='retention_days',
            field=models.IntegerField(default=90, help_text='How many days agency owns candidate after submission'),
        ),
        migrations.AddField(
            model_name='agencyclientrelationship',
            name='their_ats_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='agencyjobassignment',
            name='acceptance_mode',
            field=models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatic')], default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='agencyjobassignment',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agencyjobassignment',
            name='accepted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agencyjobassignment',
            name='assigned_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_agency_jobs', to='organisations.team'),
        ),
        migrations.AddField(
            model_name='agencyjobassignment',
            name='internal_recruiter_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='agencyclientrelationship',
            name='commission_type',
            field=models.CharField(choices=[('percentage', 'Percentage of CTC'), ('fixed', 'Fixed Fee')], default='percentage', max_length=20),
        ),
        migrations.AlterField(
            model_name='agencyclientrelationship',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Invite'), ('active', 'Active Partnership'), ('suspended', 'Suspended'), ('declined', 'Declined'), ('archived', 'Archived')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='agencyclientrelationship',
            name='tenant_id',
            field=models.UUIDField(db_index=True),
        ),
        migrations.AlterField(
            model_name='agencyjobassignment',
            name='status',
            field=models.CharField(choices=[('pending_acceptance', 'Pending Acceptance'), ('active', 'Active'), ('declined', 'Declined'), ('paused', 'Paused'), ('closed', 'Closed')], default='pending_acceptance', max_length=50),
        ),
        migrations.AlterField(
            model_name='agencyperformancescore',
            name='avg_submission_time_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='AgencyBillingTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('application_id', models.UUIDField(db_index=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(default='INR', max_length=5)),
                ('transaction_type', models.CharField(choices=[('commission', 'Commission'), ('refund', 'Refund')], max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('invoiced', 'Invoiced'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='pending', max_length=50)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('relationship', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billing_transactions', to='agencies.agencyclientrelationship')),
            ],
            options={
                'db_table': 'agencies_billing_transaction',
            },
        ),
        migrations.CreateModel(
            name='AgencyMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agency_tenant_id', models.UUIDField(db_index=True)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('recruiter', 'Recruiter'), ('sourcer', 'Sourcer')], default='recruiter', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agency_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'agencies_membership',
                'unique_together': {('agency_tenant_id', 'user')},
            },
        ),
    ]
