# Generated by Django 6.0.3 on 2026-03-26 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0006_agencyclientrelationship_contact_country_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencyclientrelationship',
            name='retention_days',
            field=models.PositiveIntegerField(default=90),
        ),
        migrations.AddField(
            model_name='agencyclientrelationship',
            name='retention_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agencyclientrelationship',
            name='retention_post_expiry',
            field=models.CharField(choices=[('shared', 'Shared Ownership'), ('company_use', 'Company Can Use Candidate'), ('consent_required', 'Require Candidate Consent')], default='shared', max_length=40),
        ),
        migrations.AddField(
            model_name='agencyclientrelationship',
            name='retention_scope',
            field=models.CharField(choices=[('job_only', 'Job Only'), ('view_only', 'View Only'), ('limited_company_access', 'Limited Company Access')], default='job_only', max_length=40),
        ),
        migrations.AddField(
            model_name='agencyclientrelationship',
            name='retention_start_type',
            field=models.CharField(choices=[('submission_date', 'Submission Date'), ('rejection_date', 'Rejection Date'), ('last_activity_date', 'Last Activity Date')], default='submission_date', max_length=40),
        ),
    ]
