# Generated by Django 6.0.3 on 2026-04-03 15:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComparisonSet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('name', models.CharField(max_length=255)),
                ('requisition_id', models.UUIDField(db_index=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('frozen', 'Frozen'), ('archived', 'Archived')], default='active', max_length=50)),
                ('weights_enabled', models.BooleanField(default=False)),
                ('weights_config', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'hdc_comparison_set',
            },
        ),
        migrations.CreateModel(
            name='HiringCommittee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('name', models.CharField(max_length=255)),
                ('requisition_id', models.UUIDField(db_index=True)),
                ('candidate_id', models.UUIDField(db_index=True)),
                ('application_id', models.UUIDField(db_index=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('voting', 'Voting'), ('split', 'Split'), ('escalated', 'Escalated'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=50)),
                ('mode', models.CharField(default='Standard', max_length=50)),
                ('quorum_required', models.IntegerField(default=1)),
                ('result', models.CharField(blank=True, max_length=50)),
                ('decision_trail', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'hdc_hiring_committee',
            },
        ),
        migrations.CreateModel(
            name='NegotiationCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('application_id', models.UUIDField(db_index=True, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('agreed', 'Agreed'), ('failed', 'Failed'), ('paused', 'Paused'), ('handed_off', 'Handed Off'), ('closed', 'Closed')], default='active', max_length=50)),
                ('current_round', models.IntegerField(default=0)),
                ('candidate_ask', models.TextField(blank=True)),
                ('company_counter', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'hdc_negotiation_case',
            },
        ),
        migrations.CreateModel(
            name='OfferRecommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('application_id', models.UUIDField(db_index=True, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scenario_modeling', 'Scenario Modeling'), ('recommended', 'Recommended'), ('locked', 'Locked')], default='draft', max_length=50)),
                ('selected_scenario_id', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'db_table': 'hdc_offer_recommendation',
            },
        ),
        migrations.CreateModel(
            name='OfferReleasePacket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('application_id', models.UUIDField(db_index=True, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('assembled', 'Assembled'), ('frozen', 'Frozen'), ('released', 'Released'), ('scheduled', 'Scheduled'), ('recalled', 'Recalled'), ('rework', 'Rework')], default='draft', max_length=50)),
                ('packet_data', models.JSONField(blank=True, default=dict)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('released_by', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'db_table': 'hdc_offer_release_packet',
            },
        ),
        migrations.CreateModel(
            name='ComparisonCandidate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('candidate_id', models.UUIDField(db_index=True)),
                ('application_id', models.UUIDField(db_index=True)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('risk_flag', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('comparison_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='hdc.comparisonset')),
            ],
            options={
                'db_table': 'hdc_comparison_candidate',
            },
        ),
        migrations.CreateModel(
            name='CommitteeMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user_id', models.UUIDField(db_index=True)),
                ('role', models.CharField(default='Reviewer', max_length=50)),
                ('has_voted', models.BooleanField(default=False)),
                ('vote', models.CharField(blank=True, max_length=50)),
                ('review_notes', models.TextField(blank=True)),
                ('voted_at', models.DateTimeField(blank=True, null=True)),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='hdc.hiringcommittee')),
            ],
            options={
                'db_table': 'hdc_committee_member',
            },
        ),
        migrations.CreateModel(
            name='NegotiationRound',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('round_number', models.IntegerField()),
                ('candidate_ask_payload', models.JSONField(blank=True, default=dict)),
                ('company_counter_payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(default='open', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('negotiation_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='hdc.negotiationcase')),
            ],
            options={
                'db_table': 'hdc_negotiation_round',
            },
        ),
        migrations.CreateModel(
            name='OfferScenario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('name', models.CharField(max_length=255)),
                ('ctc_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('market_position', models.CharField(blank=True, max_length=100)),
                ('risk_level', models.CharField(default='Low', max_length=50)),
                ('readiness', models.CharField(default='Draft', max_length=50)),
                ('is_exception', models.BooleanField(default=False)),
                ('components', models.JSONField(blank=True, default=dict)),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to='hdc.offerrecommendation')),
            ],
            options={
                'db_table': 'hdc_offer_scenario',
            },
        ),
    ]
