# Generated by Django 6.0.3 on 2026-04-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hdc', '0003_offerreleasepacket_response_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerreleasepacket',
            name='status',
            field=models.CharField(
                choices=[
                    ('draft', 'Draft'),
                    ('assembled', 'Assembled'),
                    ('frozen', 'Frozen'),
                    ('released', 'Released'),
                    ('accepted', 'Accepted'),
                    ('declined', 'Declined'),
                    ('query', 'Query Raised'),
                    ('scheduled', 'Scheduled'),
                    ('recalled', 'Recalled'),
                    ('rework', 'Rework'),
                ],
                default='draft',
                max_length=50,
            ),
        ),
    ]
