# Generated by Django 6.0.3 on 2026-04-04 20:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hdc', '0004_alter_offerreleasepacket_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='DecisionApproval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('application_id', models.UUIDField(db_index=True, unique=True)),
                ('requisition_id', models.UUIDField(db_index=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('revoked', 'Revoked')], default='pending', max_length=50)),
                ('approver_id', models.UUIDField(db_index=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('comments', models.TextField(blank=True)),
                ('is_final', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'hdc_decision_approval',
            },
        ),
    ]
