# Generated by Django 6.0.3 on 2026-03-25 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_emailotp_attempts_emailotp_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('tenant_admin', 'Tenant Admin'), ('hr_manager', 'HR Manager'), ('hiring_manager', 'Hiring Manager'), ('recruiter', 'Recruiter'), ('interviewer', 'Interviewer'), ('agency_owner', 'Agency Owner'), ('agency_admin', 'Agency Admin'), ('agency_recruiter', 'Agency Recruiter'), ('candidate', 'Candidate'), ('viewer', 'Viewer')], default='viewer', max_length=50),
        ),
    ]
