# Generated by Django 6.0.3 on 2026-04-05 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automation_permissions', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='workflowaccessaudit',
            new_name='automation__tenant__f1002b_idx',
            old_name='wf_audit_tenant_created_idx',
        ),
        migrations.RenameIndex(
            model_name='workflowaccessaudit',
            new_name='automation__tenant__d8944c_idx',
            old_name='wf_audit_tenant_user_idx',
        ),
        migrations.RenameIndex(
            model_name='workflowaccessaudit',
            new_name='automation__tenant__d8c4e4_idx',
            old_name='wf_audit_tenant_decision_idx',
        ),
        migrations.RenameIndex(
            model_name='workflowpermissionpolicy',
            new_name='automation__tenant__05e984_idx',
            old_name='wf_perm_policy_tenant_active_idx',
        ),
        migrations.RenameIndex(
            model_name='workflowpermissionrule',
            new_name='automation__policy__310fa4_idx',
            old_name='wf_perm_rule_policy_role_idx',
        ),
        migrations.RenameIndex(
            model_name='workflowpermissionrule',
            new_name='automation__role_co_cc105e_idx',
            old_name='wf_perm_rule_role_res_act_idx',
        ),
        migrations.RenameIndex(
            model_name='workflowrestrictedaction',
            new_name='automation__tenant__d53116_idx',
            old_name='wf_restricted_tenant_sev_idx',
        ),
    ]
