# Generated by Django 6.0.3 on 2026-04-07 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency_workflows', '0002_agencyworkfloweventdefinition_agencyworkfloweventlog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencyworkfloweventdebugtrace',
            name='event_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='traces', to='agency_workflows.agencyworkfloweventlog'),
        ),
    ]
