# Generated by Django 6.0.3 on 2026-03-25 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0002_permission_label_permission_module_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='based_on_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_roles', to='rbac.role'),
        ),
    ]
