# Generated by Django 6.0.3 on 2026-04-03 16:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hdc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JoiningCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('application_id', models.UUIDField(db_index=True, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Joining Pending'), ('joined', 'Joined'), ('postponed', 'Postponed'), ('withdrawn', 'Offer Withdrawn'), ('no_show', 'No Show')], default='pending', max_length=50)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('actual_joining_date', models.DateField(blank=True, null=True)),
                ('handoff_notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'hdc_joining_case',
            },
        ),
    ]
