# Generated by Django 6.0.3 on 2026-04-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hdc', '0002_joiningcase'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerreleasepacket',
            name='candidate_response',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='offerreleasepacket',
            name='responded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
