# Generated by Django 6.0.3 on 2026-04-04 20:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hdc', '0005_decisionapproval'),
    ]

    operations = [
        migrations.CreateModel(
            name='HDCAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('application_id', models.UUIDField(db_index=True)),
                ('requisition_id', models.UUIDField(db_index=True)),
                ('action_type', models.CharField(max_length=100)),
                ('previous_status', models.CharField(blank=True, max_length=50)),
                ('new_status', models.CharField(blank=True, max_length=50)),
                ('performed_by_id', models.UUIDField(db_index=True)),
                ('comments', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'hdc_audit_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
