# Generated by Django 6.0.3 on 2026-04-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hdc', '0006_hdcauditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='joiningcase',
            name='assigned_hr_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='joiningcase',
            name='candidate_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='joiningcase',
            name='job_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='joiningcase',
            name='offer_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='joiningcase',
            name='status',
            field=models.CharField(
                choices=[
                    ('pending', 'Pending'),
                    ('in_progress', 'In Progress'),
                    ('documents_pending', 'Documents Pending'),
                    ('completed', 'Completed'),
                    ('handed_off', 'Handed Off'),
                    ('joined', 'Joined'),
                    ('postponed', 'Postponed'),
                    ('withdrawn', 'Offer Withdrawn'),
                    ('no_show', 'No Show'),
                ],
                default='pending',
                max_length=50,
            ),
        ),
    ]
